### ISSUE TITLE
How to decode NMEA 2000 PGNs ?

### ISSUE THREAD

**Issue by captcha1** [hardbyte/python-can#1004]
I'm trying to make a decode file for NMEA 2000 PGNs (eg : 0x1F801 is position, 0x1F50B is depth).

I can play back a log file (using canplayer and this data : https://gitlab.com/gpsd/gpsd/-/tree/master/test/nmea2000) and view the raw data w/ can_viewer.py : 

```
Count   Time           dt          ID          DLC  Data
107     12.080583      0.100003    0x09F80102  8    D6 71 9A 16 87 1A B8 0D
```

When I try to decode with : 

-d '9F80102:<BHL'

... it just ignores it.

Any tips ?

Thanks

**Comment by felixdivo** [comment]
I just found this: [gpsdio](https://github.com/GlobalFishingWatch/gpsdio) (dunno if related). There are more, like [j1939](https://github.com/benkfra/j1939) (which is built on python-can). [canboat](https://github.com/canboat/canboat) is also a neat tool.

However, supporting protocols above CAN is definitely beyond the scope of this library.
