### ISSUE TITLE
SimpleSerialLoopTest.test_rx_tx_min_max_data fails

### ISSUE THREAD

**Issue by zariiii9003** [hardbyte/python-can#1014]
Test fails with pypy3 under ubuntu-latest and windows-latest. [Failed test](https://github.com/hardbyte/python-can/pull/1013/checks?check_run_id=2356807637#step:5:338)

<details>
<summary>pytest traceback</summary>
<pre>

_________________ SimpleSerialLoopTest.test_rx_tx_min_max_data _________________

self = <test.serial_test.SimpleSerialLoopTest testMethod=test_rx_tx_min_max_data>

    def test_rx_tx_min_max_data(self):
        """
        Tests the transfer from 0x00 to 0xFF for a 1 byte payload
        """
        for b in range(0, 255):
            msg = can.Message(data=[b])
            self.bus.send(msg)
\>           msg_receive = self.bus.recv()

test/serial_test.py:58: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
can/bus.py:87: in recv
    msg, already_filtered = self._recv_internal(timeout=time_left)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <can.interfaces.serial.serial_can.SerialBus object at 0x00007f17a840a2f8>
timeout = None

    def _recv_internal(self, timeout):
        """
        Read a message from the serial device.
    
        :param timeout:
    
            .. warning::
                This parameter will be ignored. The timeout value of the channel is used.
    
        :returns:
            Received message and False (because not filtering as taken place).
    
            .. warning::
                Flags like is_extended_id, is_remote_frame and is_error_frame
                will not be set over this function, the flags in the return
                message are the default values.
    
        :rtype:
            Tuple[can.Message, Bool]
        """
        try:
            # ser.read can return an empty string
            # or raise a SerialException
            rx_byte = self.ser.read()
        except serial.SerialException:
            return None, False
    
        if rx_byte and ord(rx_byte) == 0xAA:
            s = bytearray(self.ser.read(4))
\>           timestamp = (struct.unpack("<I", s))[0]
E           struct.error: unpack str size too short for format

can/interfaces/serial/serial_can.py:143: error
</pre>
</details>

**Comment by felixdivo** [comment]
I already fixed it in 90ca9fdae061b83f82d4de1918d985320d4d6a73 as part of #1010.
