### ISSUE TITLE
Upload 4.0.0-dev.1 to pypi

### ISSUE THREAD

**Issue by sashko** [hardbyte/python-can#1022]

**Comment by felixdivo** [comment]
Will do that on Friday.

**Comment by hardbyte** [comment]
Oh yes at the moment pypi just has @christiansandberg and myself. Let me know your pypi account and I'll add you @felixdivo

**Comment by felixdivo** [comment]
@hardbyte Nice, my name is [felix.divo](https://pypi.org/user/felix.divo/).

[This Travis CI job](https://github.com/hardbyte/python-can/blob/develop/.travis.yml#L96-L107) should also publish it automatically. It might be easiest to re-run the pipeline for the tagged commit. I'll try that tomorrow.

**Comment by hardbyte** [comment]
Cool, you've now got the maintainer bit on pypi

**Comment by felixdivo** [comment]
You can now install version `4.0.0.dev2`.
