### ISSUE TITLE
Add support for Lin to Blf Reader

### ISSUE THREAD

**Issue by lampenrecht** [hardbyte/python-can#1037]
Is there any possibility to add Lin to the Blf Reader?
Or whats the problem with Lin, why it is not supported?
Maybe there is already another tool with this purpose.

**Comment by christiansandberg** [comment]
This library is focused on CAN only, so trying to squeeze in LIN may not be a very good idea. If you could represent a LIN frame as a CAN message then maybe it could be acceptable.

**Comment by felixdivo** [comment]
As in #967, we might link to such a tool in the documentation

**Comment by felixdivo** [comment]
I added this idea to #1041. It will be tracked there.
