### ISSUE TITLE
can`t use pyinstaller Packaged into EXE

### ISSUE THREAD

**Issue by lifeng5478** [hardbyte/python-can#1038]
Excuse me, I made a mistake when I packaged the exe file with pyinstaller!
i dont know how to fix it[](url)

**Comment by lifeng5478** [comment]
![1619536864(1)](https://user-images.githubusercontent.com/3992865/116267752-45608180-a7af-11eb-99e6-64e94806a692.png)

**Comment by felixdivo** [comment]
Please reopen if you have more details.
