### ISSUE TITLE
Add documentation page on related tools

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#1041]
It is crucial to limit the scope of the `python-can` library to keep the maintenance effort manageable. However, many users will probably look in the docs of this library seeking some related functionality. It could be useful to add a page on such related tools.

Examples of ideas that came up
- #1037
- #967
- #1104
- #1004

**Comment by zariiii9003** [comment]
I like this, this could help reduce new issues in this repo. I would suggest mentioning popular libraries for common problem domains like

- J1939
- ISO-TP
- DBC/ARXML
- UDS
- CANopen
- XCP

Of course the mentioned libraries should be actively maintained and have python-can as a dependency.

**Comment by hardbyte** [comment]
I'm a fan of this idea too, I wouldn't restrict it to things using python-can e.g. could include:

- directly using python `sockets`
- Micropython's CAN api

**Comment by felixdivo** [comment]
I also think that mentioning some external tools and alternatives would be useful. Someone has to write it though ;)
