### ISSUE TITLE
Doesn't send CAN error frame

### ISSUE THREAD

**Issue by MaratSabitov** [hardbyte/python-can#1043]
**Describe the bug**
I'm just tying to send error frame using 'is_error_frame' for can.Message initialization.
But looks like it is ignored when sending.
Is it for incoming frames only?
Can i send error frame at all?

**To Reproduce**
import can
canbus = can.ThreadSafeBus(bustype='socketcan', channel='can0')
payload = b'\x00\x01\x02'
can_message = can.Message(arbitration_id=0x123, data=payload, is_error_frame = True)
canbus.send(can_message)
print(can_message)

printout:
Timestamp:        0.000000    ID: 00000123    X E              DLC:  3    00 01 02

In tcpdump:
..0. .... .... .... .... .... .... .... = Error Message Flag: False

**Expected behavior**
In tcpdump:
Error Message Flag: True

**Comment by christiansandberg** [comment]
You can't send error frames except for virtual CAN buses.

**Comment by MaratSabitov** [comment]
Thanks,
