### ISSUE TITLE
pcan timestamps are silently incorrect on windows, (without uptime installed)

### ISSUE THREAD

**Issue by mjfwest** [hardbyte/python-can#1053]
**Describe the bug**
A fresh install of python-can, using a pcan device results in incorrect timestamps as `uptime` is not a requirement and the code below is designed to fail silently.
```python
try:    # use the "uptime" library if available
    import uptime
    import datetime
    # boottime() and fromtimestamp() are timezone offset, so the difference is not. 
    boottimeEpoch = (uptime.boottime() - datetime.datetime.fromtimestamp(0)).total_seconds()
except ImportError:
    boottimeEpoch = 0
```
**To Reproduce**
any code as described above

**Expected behaviour**
Raise the exception, or give a warning that the timestamps will be incorrect.

**Additional context**

OS-version: Windows
Python version: 3.9
python-can version: '3.1.0'
python-can interface/s: PCAN

  
<details><summary>Traceback and logs</summary>

  

  

```python
def func():
    return 'hello, world!'
```
</details>

**Comment by mjfwest** [comment]
of course manually installing uptime solves this.

**Comment by felixdivo** [comment]
As it's [just 6.6 kB](https://pypi.org/project/uptime/3.0.1/#files), we might add it as a `python-can[pcan]` addition.
