### ISSUE TITLE
Codecov in CI often fails without apparent reason

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#1078]
This was notable in many of the recent pull requests. For example: #1075 essentially only removed comments, so it should have nearly no impact on the coverage. However, this is what the codecov bot reports ([here](https://github.com/hardbyte/python-can/pull/1075#issuecomment-856841414)): 

![image](https://user-images.githubusercontent.com/4403130/121216427-2a3e6280-c881-11eb-8b13-3283e9265152.png)

Besides being annoying, ~it also breaks the mergify auto-merge rule~. Furthermore, it makes determining whether a PR is good to be merged quite hard.

**Comment by felixdivo** [comment]
@zariiii9003 mentioned this issue and a possible solution [here](https://github.com/hardbyte/python-can/issues/951#issuecomment-821872240).

**Comment by hardbyte** [comment]
Fixed in #1430

**Comment by felixdivo** [comment]
Thanks @hardbyte! :partying_face:
