### ISSUE TITLE
No tasks displayed when trying to print "_periodic_tasks" 

### ISSUE THREAD

**Issue by catmemo** [hardbyte/python-can#1097]
**Describe the bug**

I tried to send a message with below code:
bus.send_periodic(msg_vehspd, 0.01, duration=None, store_task=True)

When I tried to send another data, I would like to stop this task, so I print _periodic_tasks before I call this code again.
However, [] was displayed.

**To Reproduce**
Steps to reproduce the behavior (please add longer code examples below):
```
from dearpygui.core import *
from dearpygui.simple import *
import threading
import can
import math
from time import sleep

add_additional_font('simsun.ttc', 16, glyph_ranges = 'chinese_full')


def get_values(sender, data):
    
    BCS_VehSpd = get_value("vehicle_speed")
    
    period_can_messages_thread = threading.Thread(target=send_period_can_messages, args=(BCS_VehSpd))
    period_can_messages_thread.start()
    

def send_period_can_messages(BCS_VehSpd):
    
    bus = can.interface.Bus(bustype='vector', app_name='CANalyzer', channel=0, bitrate=500000)
    print(_periodic_tasks)
    bus.stop_all_periodic_tasks(remove_tasks=True)

    BCS_VehSpd = hex(math.ceil(BCS_VehSpd/0.05625))[2:]

    BCS_VehSpd = str(BCS_VehSpd).zfill(4)
    BCS_VehSpd = str(int(BCS_VehSpd[0]) + 2) + BCS_VehSpd[1:]
    msg_vehspd_data = bytearray([0, 0, 0, 0, int(BCS_VehSpd[:2], 16), int(BCS_VehSpd[-2:], 16), 0, 0])
    msg_vehspd = can.Message(arbitration_id=0x260, data=msg_vehspd_data, is_extended_id=False)
    
    Send_BCS_VehSpd = bus.send_periodic(msg_vehspd, 0.01, duration=None, store_task=True)
    

with window("Vehicle_Speed", width=200, height=200, x_pos=20, y_pos=20):

    add_input_float("vehicle_speed", callback=get_values, on_enter=True)

set_main_window_size(850, 600)    
start_dearpygui()
```

**Expected behavior**
Stop task "Send_BCS_VehSpd " before sending another data

**Additional context**

OS-version: Win10
Python version: 3.7.2
python-can version: 3.3.4
python-can interface/s: _periodic_tasks

  
<details><summary>Traceback and logs</summary>

  

  

```python
Refer to To Reproduce
```
</details>

**Comment by felixdivo** [comment]
@catmemo Could you please remove any code that is not related to the problem, like the GUI setup? That would make finding the issue a lot easier.

**Comment by catmemo** [comment]
@felixdivo Done, thks~

**Comment by catmemo** [comment]
@felixdivo Done, thks~

> @catmemo Could you please remove any code that is not related to the problem, like the GUI setup? That would make finding the issue a lot easier.

Done, thks~

**Comment by felixdivo** [comment]
Ah, thanks for the cleanup. Now I see the issue: The periodic tasks are bound to the instance of `can.interface.Bus`, but you create a new one in each iteration of the timer. However, you should use the *same* bus instance in all invocations of the timer callback. That should do what you want. And also you should close the bus once you are done using it, e.g. with `bus.shutdown()` at the very end of your script.

**Comment by felixdivo** [comment]
@catmemo If there is another issue with the setup where you suggest there is a bug lurking in the library, please feel free to open a new issue.

**Comment by catmemo** [comment]
> Ah, thanks for the cleanup. Now I see the issue: The periodic tasks are bound to the instance of `can.interface.Bus`, but you create a new one in each iteration of the timer. However, you should use the _same_ bus instance in all invocations of the timer callback. That should do what you want. And also you should close the bus once you are done using it, e.g. with `bus.shutdown()` at the very end of your script.

Thank you for your quickly reply！

**Comment by catmemo** [comment]
> @catmemo If there is another issue with the setup where you suggest there is a bug lurking in the library, please feel free to open a new issue.

Well, I will. Thanks again.
