### ISSUE TITLE
Extend Functionality With OBD2/OBD-II Data Interface 

### ISSUE THREAD

**Issue by kklouzal** [hardbyte/python-can#1104]
As you may know, the python-obd library exists https://github.com/brendan-w/python-OBD and merging functionality into this library would provide quick and easy access to OBD2/OBD-II data.
For instance, when using this module with a RaspberryPI https://copperhilltech.com/pican3-can-bus-board-for-raspberry-pi-4-with-3a-smps-and-rtc/

**Comment by felixdivo** [comment]
Please refer to #1041. It is not in the scope of this library.
