### ISSUE TITLE
FileNotFoundError: Could not find module 'usb2can.dll' (or one of the dependencies)

### ISSUE THREAD

**Issue by MasterCodeIT** [hardbyte/python-can#1106]
I do not see a usb2can.py in the repository. I attempted to put the USB2CAN CANAL DLL in the USB2CAN library in the usb2can directory but I still get the error:

FileNotFoundError: Could not find module 'usb2can.dll' (or one of the dependencies). Try using the full path with the constructor syntax.

**Comment by felixdivo** [comment]
See [the docs](https://python-can.readthedocs.io/en/master/interfaces/usb2can.html) for how to install it. You have to do it manually.
