### ISSUE TITLE
Decoding DM1s

### ISSUE THREAD

**Issue by tractorDan** [hardbyte/python-can#1124]
For blfreader:

It appears that it is not possible to obtain FECAh (DM1s) in this format unless they are 8 bytes or less.
If a DM1 is greater than 8 bytes, it is necessary to manually decode ECFF and EBFF TP messages to obtain the multi-packet DTC information.

It would be good to be able to access DM1 objects and internal fields.

e.g. 
log = can.BLFReader(filename)
for msg in log:
    if msg.type == DM1: 
        print msg.dm1.lamp_states.red_mil
        print msg.dm1.dtc1.spn
        print msg.dm1.dtc1.fmi
        print msg.dm1.dtc2.spn
        print msg.dm1.dtc2.fmi
etc

or similar.

**Comment by christiansandberg** [comment]
This is specific to J1939 and this library deliberately only handles raw CAN. The idea is that protocol specific libraries can be built on top of python-can.
