### ISSUE TITLE
New release (4.0.0)

### ISSUE THREAD

**Issue by danielhrisca** [hardbyte/python-can#1133]
Hello all, is there some target release date for version 4.0.0 final?

**Comment by felixdivo** [comment]
Now, #1046 is "only" waiting for reviews of the changes and merges. The implementation is done.

**Comment by felixdivo** [comment]
Yay, #1046 is complete. I'll provide a release candidate soon (when time permits).

**Comment by felixdivo** [comment]
#1216 adds a changelog

**Comment by felixdivo** [comment]
Waits for a regression to be fixed by #1221. Then there will be version `4.0.0-rc.0` and an announcement issue.

**Comment by felixdivo** [comment]
Okay, so the blocking #1221 and #1230 are resolved. Everything is implemented for the release.

**Comment by felixdivo** [comment]
A new release candidate is available, [`4.0.0rc0`](https://github.com/hardbyte/python-can/releases/tag/4.0.0rc0)! :partying_face:

You can install it with `pip install python-can==4.0.0rc0`.

**Comment by felixdivo** [comment]
Btw, #1249 is not included in that release. It will be in the next one or the full release, depending of whether we need a second *rc* build at all.

**Comment by felixdivo** [comment]
See  #1250. Thank you for your patience. :smiley:
