### ISSUE TITLE
Python-can consume an asc file

### ISSUE THREAD

**Issue by Kheffache** [hardbyte/python-can#1162]
Hello, i have a projet where i need to decode a raw CAN Trace log that is saved into an asc file, the decoding should be done offline (at the end of the test execution). The can Trace log contains 3 type of CAN-Data:

- CAN - TP
- CAN
- CAN FD

**My Question is:** I want to know if the Python-can can consume a CAN log file (.asc .txt ...) to extract the payload of the frame that are CAN TP data frames. If not any help on a possible solution ?

**Comment by felixdivo** [comment]
It should be possible to read these files but CAN TP "decoding" would have to be done manually or with other libraries. For the file reading, have a look `can.ASCReader` and the other readers [here](https://python-can.readthedocs.io/en/master/listeners.html). Usage is simple:

```python
for message in ASCReader("my/path/to/the/file.asc"):
    if message.data[0] == 0x11:
        print("something")
```
