### ISSUE TITLE
python-can 4.0.x can/util.py timing configuration do not allow int

### ISSUE THREAD

**Issue by nedlukasz** [hardbyte/python-can#1175]
tseg1, tseg2, sjw cannot be configured as int.

Issue is located in file util.py in function _create_bus_config in line 235:
`timing_conf[key] = int(config[key], base=0)`

For example:
```python
config["tseg1"] = int(5)
timing_conf["tseg1"] = int(config["tseg1"], base=0)  #  here will be exception
#  TypeError: int() can't convert non-string with explicit base
```

**Expected behavior**
For config[key] specified as string use int(config[key], base=0)
For config[key] specified as not string use int(config[key])

**Comment by Tbruno25** [comment]
I'll take this issue!
