### ISSUE TITLE
Vector hardware in ubuntu : ImportError: The Vector API has not been loaded

### ISSUE THREAD

**Issue by temp369** [hardbyte/python-can#1185]
Hi,

While checking with python-can in ubuntu 18.04, I am receiving this error:
ImportError: The Vector API has not been loaded

I hope this is an driver issue. How can I get the driver for Vector devices in Linux?

**Comment by zariiii9003** [comment]
Vector interfaces are only supported on Windows ([see docs](https://python-can.readthedocs.io/en/develop/interfaces/vector.html)). 
As far as i know Vector Informatik does not provide any linux drivers.

**Comment by felixdivo** [comment]
Indeed, you'll probably have to use different hardware or contact Vector and demand better platform support.
