### ISSUE TITLE
Windows compatibility for Lawicel CANUSB

### ISSUE THREAD

**Issue by remusmp** [hardbyte/python-can#119]
Hello,

Is `python-can` compatible with [Lawicel CANUSB](http://www.can232.com/)? What configuration should I use (interface, channel)?

I'm running Windows python 3.5 x64.

Many thanks!

**Comment by hardbyte** [comment]
It depends if you're running on a reasonably modern linux then yes it is supported via socketcan. 

On windows would take a small amount of work to wrap their DLL. Contributions welcome!

**Comment by remusmp** [comment]
Thanks. I'll look into it and wrap their dll.

**Comment by krixkrix** [comment]
Did you wrap it or find another python solution for Lawicel CANUSB on windows? I am looking for the same.

**Comment by remusmp** [comment]
I started on wrapping it but the thing is Lawicel only provides .net 2.0 dlls for x64. I didn't want my project to depend on .net so my choice was to switch to Linux for the entire project where CAN just worked with no head aches. I found Lawicel CANUSB very outdated from a software point of view.

**Comment by grodansparadis** [comment]
The USB2CAN is CANAL and the Lawicel driver should export a CANAL interface (http://www.vscp.org/docs/vscpd/doku.php?id=level1_driver_canusb) but there is also a CANAL interface for the serial channel of it (http://www.vscp.org/docs/vscpd/doku.php?id=level1_driver_can232).

The naming of the "USB2CAN" interface is a bit bad. Should have been "CANAL" IMHO as it is just one device that export this interface (http://www.vscp.org/docs/vscpd/doku.php?id=vscp_daemon_level_i_drivers).

I just found out the existent of python-can today. Great work!

**Comment by grodansparadis** [comment]
Sorry for jumping in on the thread btw.

**Comment by yegorich** [comment]
Why not just implementing ASCII protocol using python-serial? This way you can handle both serial based devices as also devices talking ASCII protocol via TCP/IP.
