### ISSUE TITLE
Thread Safe SocketCan Implementation

### ISSUE THREAD

**Issue by NasrulhaqAbdullah** [hardbyte/python-can#1193]
Hi, can someone tell
me how to use this function? I am quite new to Python and it would be really helpful when there is an example on how to use it in a programming. I know that it is well written in the document but an example code would help me better in understanding the whole function of Thread Safe function. I intend to make can nodes possible to listen and also at the same time transmit can messages. Need help thanks in advance 🙌🏻

**Comment by felixdivo** [comment]
Does [this class](https://python-can.readthedocs.io/en/master/bus.html#thread-safe-bus) help? The syntax highlighting is rather messed up, I'll fix that.
