### ISSUE TITLE
Can I use this with ELM327 USB? 

### ISSUE THREAD

**Issue by ayushmankumar7** [hardbyte/python-can#1202]
### Is your feature request related to a problem? Please describe.

On Connecting my ELM327 with the car and laptop, I don't find "can0" on doing ifconfig -a .

**Comment by felixdivo** [comment]
Apparently `socketcan` does not support it, and we probably don't either. You might get it to run with [norly/elmcan](https://github.com/norly/elmcan).

If you have more problems with this library once it is recognized by the Linux kernel, feel free to comment again or reopen this issue.
