### ISSUE TITLE
Types from typechecking.py should be exported for plugin interfaces

### ISSUE THREAD

**Issue by John-Titor** [hardbyte/python-can#1205]
### Describe the bug
An interface plugin cannot fully implement typechecking due to not having access to some internal types; at least AutoDetectedConfig, Channel, and CanFilters could be exported in __init__.py to make this possible.

python-can version: HEAD

**Comment by zariiii9003** [comment]
```python3
from can.typechecking import AutoDetectedConfig, Channel, CanFilters
```
This doesn't work for you? Are you using the develop branch?

**Comment by John-Titor** [comment]
Well, that's embarrassing. It certainly didn't when I tried earlier, but in attempting to reproduce in order to respond it's clearly working now, so I must have been doing something else wrong. Sorry about that!
