### ISSUE TITLE
Vector hardware,no ack can not raise can.CanError

### ISSUE THREAD

**Issue by XXIN0** [hardbyte/python-can#1211]
### Describe the bug

HI,
I want to test the can transmit without ack,but it can raise can.CanError.
![image](https://user-images.githubusercontent.com/41498132/149438037-b9fbbf65-9e73-4c90-b634-df8bbfdbf94d.png)

### Additional context

Python version:3.7.9
python-can version: 3.3.4
python-can interface/s (if applicable): Vector CANcaseXL

```python
import can

my_bus = can.interface.Bus(bustype='vector', channel='0,1', app_name='Python Can',bitrate=500000, receive_own_messages=False)
msg = can.Message(arbitration_id=0x123, data=[1, 2, 3, 4, 5, 6, 7, 8], channel="0,1",)
my_bus.send(msg, timeout=0.5)

```

**Comment by zariiii9003** [comment]
You need a another device on the physical CAN bus to acknowledge your messages. Otherwise you have the option to use the Virtual Channel in Vector HW config. Then you don't need any receivers.

Would you mind posting your Traceback?

**Comment by XXIN0** [comment]
Hi，
It didn't have Traceback,if use my way to send message.I think when the bus timeout,it will raise an error.

If I use the software:"Busmaster",it will raise an error,I don‘t know the diffrence between the "python-can" and "busmaster"
![image](https://user-images.githubusercontent.com/41498132/149702977-5cb7b3af-be9d-46a0-bc66-0845dcb2f618.png)
![image](https://user-images.githubusercontent.com/41498132/149703101-16640234-f01a-4f98-9345-17026144341d.png)

**Comment by felixdivo** [comment]
Sorry @XXIN0, but I do not understand how python-can comes into play here where the problem is that you want to report or get assistance with.

**Comment by XXIN0** [comment]
for example，if I don't connect any devices,when I send an can message,it will raise an error that tell me the send is not ok.

**Comment by zariiii9003** [comment]
Which one of these options is your problem?

1. You expect an error, but you don't get any.
2. You excpect no error, but you get can.CanError.

**Comment by XXIN0** [comment]
1 is my expect

**Comment by geynis** [comment]
Hi, having the same issue, I see there is no implementation in the python canlib for raising errors when sending can frames with Vector interface. Will this be resolved soon?

**Comment by geynis** [comment]
@XXIN0 I have found a work around, open the bus with receive_own_messages=True and use the receive function to get an error frame for an error on transmitted frames.
I'm checking Vector's API to see if how can we fix this issue, will let you know.

**Comment by zariiii9003** [comment]
for CAN you can check `Message.is_error_frame`. I don't think there is a way to get the exact kind of error.
For CAN FD you can get the error type [like this](https://github.com/hardbyte/python-can/issues/909#issuecomment-703072365).

**Comment by geynis** [comment]
@zariiii9003 thanks, i didn't look on the latest version. I still think there should be a better way to get the Tx error on send function and not throw the receive function.

**Comment by XXIN0** [comment]
> @XXIN0 I have found a work around, open the bus with receive_own_messages=True and use the receive function to get an error frame for an error on transmitted frames. I'm checking Vector's API to see how can we fix this issue, will let you know.

@geynis Thanks,I'll try your  suggestion.
