### ISSUE TITLE
Add mypy typing support

### ISSUE THREAD

**Issue by brent-stone** [hardbyte/python-can#1227]
### Problem
Downstream projects using mypy and other automated tooling need can.Message to have proper type hints

### Solution
Accept my pull request from brent-stone:mypy_support

### Alternatives
Gradually introduce modern (3.9+) typing into the python-can package.

**Comment by brent-stone** [comment]
This is being implemented with the type hinting the dev branch. Closing.

**Comment by felixdivo** [comment]
Still thank you for your quick effort in #1226!

**Comment by zariiii9003** [comment]
@felixdivo We might need to include a [py.typed](https://www.python.org/dev/peps/pep-0561/#id13) file so mypy works for downstream packages. But i'm not sure if it causes problems since `can.interfaces` is not really well annotated.
