### ISSUE TITLE
Add bus and message padding support

### ISSUE THREAD

**Issue by keelung-yang** [hardbyte/python-can#1237]
Some vehicle manufacturers require padding all messages in their diagnstic CAN bus.
And as described in ISO 15765-2-2011 `9.4.2.1 CAN frame data padding`:

> If this solution is used, the DLC is always set to 8, even if the N_PDU to be transmitted is shorter than 8 bytes. The sender has to pad any unused bytes in the frame.

So padding in bus level should be supported.
And also padding in message level should be supported too, for mixed padding/no padding CAN messages, such as cycle message no padding but diagnostic have in a same bus.

**Comment by zariiii9003** [comment]
ISO-TP is out of scope for this library. [Here is an iso-tp package](https://github.com/pylessard/python-can-isotp) that is supposedly compatible with python-can.
