### ISSUE TITLE
4.0.0rc0 blf conversion

### ISSUE THREAD

**Issue by Rampagy** [hardbyte/python-can#1255]
### Describe the bug

If I convert a .blf to .asc and then back to .blf my expectation is that the original and resulting blf would be very similar in size.  Version 3.3.4  produces a blf that is much more similar in size than what 4.0.0 does.  What is all the extra data?

Version 3.3.4:
![version3 3 4](https://user-images.githubusercontent.com/32419459/152867062-2bac306a-98f4-403b-88c5-7eb3c48c8618.PNG)

Version 4.0.0rc0:
![Version4 0 0-rc](https://user-images.githubusercontent.com/32419459/152867096-f926141f-801d-4713-9b0a-13e59b610757.PNG)

### To Reproduce

1. Convert a large blf file (>= 5MB) to an asc 
    *  For some reason this issue doesn't occur on smaller files for me
2. Convert the resulting asc back to blf
3. Compare the original blf to the resulting blf

### Expected behavior

The original and resulting blf should be very similar in size.

### Additional context

OS and version: Windows10 2009.1
Python version: 3.9.6
python-can version: 4.0.0rc0
python-can interface/s (if applicable): Vector Hardware

<details><summary>Traceback and logs</summary>

```python
import can
import filecmp

FILE_NAME = 'example'

# read in BLF file
msgIterator = can.BLFReader(FILE_NAME + '.blf')

# convert BLF to .asc
with can.ASCWriter(FILE_NAME + '.asc') as asc_writer:
    for msg in msgIterator:
        asc_writer.on_message_received(msg)

# read in ASC file
msgIterator = can.ASCReader(FILE_NAME + '.asc')

# convert ASC back to .blf
with can.BLFWriter(FILE_NAME + '_0.blf') as blf_writer:
    for msg in msgIterator:
        blf_writer.on_message_received(msg)



if filecmp.cmp(FILE_NAME + '.blf', FILE_NAME + '_0.blf'):
    print('Files are the same!')
else:
    print('Files are not the same!')
```
</details>

**Comment by christiansandberg** [comment]
The default compression level has changed from max (9) to the default of zlib (6 I think). This is because while 9 gives slightly smaller files it is much slower, so for most applications it is not worth it. But you can still pass that as an argument to BLFWriter.

**Comment by Rampagy** [comment]
I tried and now the results match my expectation!
