### ISSUE TITLE
XNET library not installed

### ISSUE THREAD

**Issue by Heistberg** [hardbyte/python-can#1277]
Hello everyone, I tried to use this library to control some CAN peripherals with a PXI and I found that when installing the python can library, NI-XNET is not added as a dependency so when you try to run it, it always raises an error. Would be very helpful if someone could add it in the dependencies or at least give a helpful error message when the library is not found, would help a lot newbies like me.

PD: Sorry if I skipped some formality. This is my first time in github.

**Comment by zariiii9003** [comment]
You need to install the optional dependency: `pip install python-can[nixnet]`
