### ISSUE TITLE
receiving old messages

### ISSUE THREAD

**Issue by matze4949** [hardbyte/python-can#1307]
### Describe the bug
Hi,
I  am waiting on the CAN bus to send me certain error messages. The message i am waiting for is send once for each error of the system. When i receive the messages with the following code i am receiving a bunch of old error messages, which dont care anymore.
```
for msg in canBus:
   if msg.arbitration_id == rxID:
      print(msg)
```
With CANoe i am only receiving one message, as I expect

### Expected behavior
Receiving only one Message, not recv old messages

### Additional context
When shutdown the bus before receivig I only receive one message, but I cant shutdown the bus in my project.
Also i just recv one message when  I received all of the not wanted messages.

Is there a command to clear that rx buffer or whatever it is so that i just recv one message?

OS and version: Win10 21H2
Python version: 3.8.5
python-can version: 4.0.0
python-can interface/s (if applicable): Vector VN1630A

**Comment by zariiii9003** [comment]
There is a command in the Vector XL API to flush the rx buffer. But it is not implemented in python-can.

But you could also do
```python3
while canBus.recv(timeout=0):
    continue
```
to clear the buffer.

That said, your application should always read all the messages. You don't want the buffer to overflow and miss messages.

**Comment by matze4949** [comment]
Now everything works like i was expecting, thanks for the fast answer

**Comment by matze4949** [comment]
> There is a command in the Vector XL API to flush the rx buffer. But it is not implemented in python-can.
> 
> But you could also do
> 
> ```python
> while canBus.recv(timeout=0):
>     continue
> ```
> 
> to clear the buffer.
> 
> That said, your application should always read all the messages. You don't want the buffer to overflow and miss messages.

After a few weeks of testing i found out that in certain cases the suggested method takes a long time to clear the rx buffer.
Is there a way to implement a command like flush_tx_buffer?

**Comment by zariiii9003** [comment]
You could try to implement it yourself. Look at the call signature of `xlFlushReceiveQueue` in your vxlapi.h file and add it to `xldriver.py` in this library. But i'm not sure whether that command actually works for all interfaces.

If it works, feel free to create a pull request.
