### ISSUE TITLE
Custom Interfaces

### ISSUE THREAD

**Issue by jagauthier** [hardbyte/python-can#1311]
Hello,

 There is documentation about some custom interface here:
https://python-can.readthedocs.io/en/develop/interfaces.html

Given these two issues:
https://github.com/hardbyte/python-can/pull/1110
https://github.com/hardbyte/python-can/pull/1233

Is this method still valid?

I really don't quite understand how to implement a custom interface. It's a bit deeper into Python than I usually get.
So, I'm looking for a little guidance.  IE: I've copied over an existing interface and I am going to modify it.

**Comment by zariiii9003** [comment]
The docs should still be valid.

**Comment by jagauthier** [comment]
Thanks. I've never created an installable python module.  I went through the docs, and I did it.  I added 
    entry_points={
        'can.interface': [
            "interface_name=slcan_custom:slcan_customBus",
        ]
    },

to the setup.py file in the setuptools.setup() function.

I created a small virtualenv, and tried to use it:
bus = can.interface.Bus(bustype='slcan_custom', bitrate=500000, channel='/dev/tty0')

But got this:
can.exceptions.CanInterfaceNotImplementedError: Unknown interface type "slcan_custom"

This is a different realm for me. I am going to go read about entry_points.  But thought I'd post here for a little guidance as well.

**Comment by jagauthier** [comment]
Yup, and I cannot do that either.  I will re-evaluate the structure and try to figure it out.   Python's import nuances have never been a strength for me.  Like.. apparently, trying to do the import forces ```__init__.py```  to run, when I look at the other interfaces, seems to do the import as well. Well, thanks. I will continue to fight it!
