### ISSUE TITLE
Add documentation for how to build the docs to README

### ISSUE THREAD

**Issue by j-c-cook** [hardbyte/python-can#1320]
### Is your feature request related to a problem? Please describe.

Contributors often need to edit documentation. It is nice to be able to build the documentation locally prior to pushing up changes to make sure everything looks okay. I don't currently see any documentation for how to build the docs. 

### Describe the solution you'd like

A new section in the README dedicated to building the docs.

**Comment by zariiii9003** [comment]
There's a [section in the docs](https://python-can.readthedocs.io/en/master/development.html#building-installing) for it.

**Comment by j-c-cook** [comment]
I hadn't noticed that. I should have looked into the contributing docs closer.
