### ISSUE TITLE
Harden `can.logger` functionality to write last received message to file without prod

### ISSUE THREAD

**Issue by j-c-cook** [hardbyte/python-can#1329]
### Describe the bug

The current implementation of `can.logger` rolling logger functions such that the most recent message sent on the bus is held in memory and not written to the file unless there is a `KeyboardInterrupt` or another message appears on the bus. What if power is killed without notice and a shutdown procedure for the logger is not able to occur? I have simulated that by using the `kill <PID>` in Linux and have shown that the last CAN message is lost when this occurs (see Section To Reproduce). (I was on the fence as to whether this should be labeled a bug or enhancement and went with bug.)

### To Reproduce

The following are steps to to recreate what I am discussing. 

Set up a virtual CAN bus. 
```
sudo ip link add dev vcan0 type vcan
sudo ip link set up vcan0
```

Create a script, `issue1329.py`, that sends two messages on the virtual CAN bus. 
<details><summary>issue1329.py</summary>

```python
import can
import time


def main():
    bitrate = 250000

    # --------------------------------------------------------------------------
    # Define the bus
    # --------------------------------------------------------------------------
    bus = can.Bus(
        interface='socketcan', channel='vcan0', receive_own_messages=True)

    # --------------------------------------------------------------------------
    # Send data
    # --------------------------------------------------------------------------

    data = [0, 0, 0, 0, 135, 214, 18, 0]
    print(''.join('{:02x}'.format(x) for x in data))

    arbitration_id = 0x11FF1100
    msg = can.Message(
        arbitration_id=arbitration_id, data=data, is_extended_id=True)

    bus.send(msg)
    time.sleep(1 / (bitrate - 1))  # Min sleep time

    # --------------------------------------------------------------------------
    # Send data
    # --------------------------------------------------------------------------

    arbitration_id = 0x10FF1000
    msg = can.Message(
        arbitration_id=arbitration_id, data=data, is_extended_id=True)

    bus.send(msg)
    time.sleep(1 / (bitrate - 1))  # Min sleep time


if __name__ == '__main__':
    main()

```
</details>

Check the `file.txt` contents after stopping the logger with a keyboard interrupt.

<details><summary>Stopping the logger with keyboard interrupt</summary>

Start logging the CAN bus.
```
user@beowulf:~/Documents/python-can$ python -m can.logger -c vcan0 -i socketcan -b 250000 -f file.txt -s 5000
Connected to SocketcanBus: socketcan channel 'vcan0'
Can Logger (Started on 2022-06-08 15:31:28.750509)
```
Send the two CAN messages from another terminal window.
```
user@beowulf:~/Documents/python-can$ python issue1329.py
```
View the `file.txt`. There will only be one CAN message in the log file. Now stop the logger. 
```
^C
```
Now that the logger has been interrupted, the last CAN message will be in `file.txt`. 

</details>

Check the `file.txt` contents after stopping the logger with a PID `kill` (simulating a power outage).

<details><summary>Stopping the logger with PID kill</summary>

NOTE: With this method, `kill -SIGINT <PID>` could be utilized and Python registers it as a KeyboardInterrupt, however I am using `kill <PID>` to simulate a power cycle.

First start up the CAN bus logger in the background. 
```
user@beowulf:~/Documents/python-can$ python -m can.logger -c vcan0 -i socketcan -b 250000 -f file.txt -s 5000 &
[1] 1133463
user@beowulf:~/Documents/python-can$ Connected to SocketcanBus: socketcan channel 'vcan0'
Can Logger (Started on 2022-06-08 15:36:58.147940)

user@beowulf:~/Documents/python-can$ logger_pid=$!  # store the PID as logger_pid
```
(You might have to hit the enter key to get a new line to show up on the terminal.)

Now send the two CAN messages from another terminal window. 
```
user@beowulf:~/Documents/python-can$ python issue1329.py
```

Now kill the logger task. 
```
user@beowulf:~/Documents/python-can$ kill $logger_pid
```

Check the `file.txt`. There is only one CAN message in it. 

</details>

### Expected behavior

The `can.logger` rolling logger should write to the log file instantly upon receiving CAN data and should **not** have to be prodded by another CAN message or a `KeyboardInterrupt` to write the most recent message. 

### Additional context

OS and version: Ubuntu 20.04.4 LTS
Python version: Python 3.7.13
python-can version: 4.0.0

**Comment by zariiii9003** [comment]
The rolling logger delegates the file access to the actual logformat implementations. Most logformats do write immediately to file. Only the BLF-Writer uses a buffer.

But python itself uses line buffering for text files. The docs say 

> To disable buffering in TextIOWrapper, consider using the write_through flag for [io.TextIOWrapper.reconfigure()](https://docs.python.org/3/library/io.html#io.TextIOWrapper.reconfigure).

This comes with a performance penalty obviously and i do not see the use case for the majority of users.

**Comment by j-c-cook** [comment]
Good information. Is it something that could be made optional?

Could the buffer size for the BLF-Writer be opened up to the API via **kwargs? I see that there is a `self._buffer` and `self._buffer_size`, but am not clearly seeing the definitions. Surely the `_buffer_size` isn't hard coded to 0?
https://github.com/hardbyte/python-can/blob/0c4dee01a00a9bdd82b71071627b8f2fd2fc929d/can/io/blf.py#L401-L402

**Comment by j-c-cook** [comment]
The premises here is remote CAN logging. Something that commercial companies may charge an arm and a leg for. 

I don't know that it would be worth the effort to open the `max_container_size` for the BLF-Writer to the API, given that a max file size can be defined. It appears that if the max file size is small, then the `max_container_size` is not the defining factor for when the buffer is dumped to a file. If a user were logging hundreds of CAN messages per minute, then the BLF-Writers compression becomes of importance. The greater the number of CAN messages logged, the less important the possibility of losing the buffer becomes. This is something that would have to be decided on a per user basis. Something that depends on the number of CAN messages that are passed through the `--filter`. 

If the number of CAN messages being logged is a small number, say 3 messages per minute, then the BLF-Writer isn't really applicable. A `log` or `txt` format should be acceptable, given a relatively low data rate. In this case, the "buffer" contains the last received message (like described in my original post). 

@zariiii9003 Are you willing to incorporate an optional `write_through` flag into @hardbyte's repository?

**Comment by j-c-cook** [comment]
It appears to me that the only way to turn off the buffer is if a binary file is being written (`mode='w+b'` or `mode='a+b'`). https://docs.python.org/3.7/library/functions.html#open

> buffering is an optional integer used to set the buffering policy. Pass 0 to switch buffering off (only allowed in binary mode), 1 to select line buffering (only usable in text mode), and an integer > 1 to indicate the size in bytes of a fixed-size chunk buffer. When no buffering argument is given, the default buffering policy works as follows:
> 
>  - Binary files are buffered in fixed-size chunks; the size of the buffer is chosen using a heuristic trying to determine the underlying device’s “block size” and falling back on [io.DEFAULT_BUFFER_SIZE](https://docs.python.org/3.7/library/io.html#io.DEFAULT_BUFFER_SIZE). On many systems, the buffer will typically be 4096 or 8192 bytes long.

> - “Interactive” text files (files for which [isatty()](https://docs.python.org/3.7/library/io.html#io.IOBase.isatty) returns True) use line buffering. Other text files use the policy described above for binary files.

**Comment by j-c-cook** [comment]
I'm going to close this and open up a new issue with a proposal for the `.txt` writer to be enhanced to write binary data.
