### ISSUE TITLE
Adding changed frames highlight color in can_viewer

### ISSUE THREAD

**Issue by jwdsoft** [hardbyte/python-can#1337]
Thanks for this great library which I really like
I hope that someone can add this feature it will be really helpfull specially in reverse engineering
The feature is to highlight the changed canbus bytes in the frames in canviewer wherever there is a change

**Comment by MattWoodhead** [comment]
Is it additional functionality over the byte highlighting added in version 4 that you would like? (run the canviewer script, then press the h key once monitoring a bus) 

![image](https://github.com/hardbyte/python-can/blob/develop/doc/images/viewer_changed_bytes_highlighting.png?raw=true)
