### ISSUE TITLE
Include a py.typed file so mypy works for downstream packages

### ISSUE THREAD

**Issue by rumpelsepp** [hardbyte/python-can#1340]
@felixdivo We might need to include a [py.typed](https://www.python.org/dev/peps/pep-0561/#id13) file so mypy works for downstream packages. But i'm not sure if it causes problems since `can.interfaces` is not really well annotated.

_Originally posted by @zariiii9003 in https://github.com/hardbyte/python-can/issues/1227#issuecomment-1019561010_

**Comment by felixdivo** [comment]
Okay, after adding the `py.typed` file, I do not get the following error any more:

```
root@260d806091e3:/home# mypy test.py
test.py:1: error: Skipping analyzing "can": module is installed, but missing library stubs or py.typed marker
test.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```
