### ISSUE TITLE
SLCAN does not support  receive_own_messages 

### ISSUE THREAD

**Issue by Oemm868** [hardbyte/python-can#1350]
I am trying to get my own send messages using the SLCAN Interface. Am I right, that the module does not support this feature?

**Comment by j-c-cook** [comment]
Could you provide more information? What object are you referring to? Do you have a minimal script that I could get started with?

**Comment by wallem89** [comment]
The receive own messages function does work with a SLCAN, at least with a VSCOM adapter that I am using. I expect the problem might be in the listener. Did you try to receive the message without the notifier?

So try something like this:
```
for msg in can_bus:
    print(f"Message ID {msg.arbitration_id} received with data {msg.data}")
```

**Comment by Oemm868** [comment]
Hi wallem89, I have checked your procedure but had no success. I am checking if it is a hardware problem with my adapter. It seems likely that this problem is caused there. I have a great ambition to solve the problem, but the priority of my project is currently low. I close this issue first, in case it is not a "My Hardware Problem" I open the issue again.
