### ISSUE TITLE
Initialize Vector Dongle VN1610 with CAN-FD Fails

### ISSUE THREAD

**Issue by skipper85** [hardbyte/python-can#1353]
### Describe the bug
When I try to initialize the can.bus() for the VN1610 vector dongle with the fd parameter I get the following error.
`
can.interfaces.vector.exceptions.VectorInitializationError: xlCanFdSetConfiguration failed (XL_ERR_WRONG_PARAMETER) [Error Code 101]
`

Without the fd parameters the bus initialize, but for normal CAN.

### To Reproduce
Initialize the bus with the fd parameter.

### Expected behavior
Expect the CAN bus initialized with CAN-FD for the vector dongle.

### Additional context
No issues with the peak-systems PCAN dongle.

OS and version: Windows 10
Python version: 3.9.13
python-can version: python-can==4.0.0
python-can interface/s (if applicable): vector VN1610 dongle, driver version 20.30.14

`
Traceback (most recent call last):
  File "c:\users\documents\hengelo-qlab\dccb_daimler\tests\test_vector.py", line 89, in <module>
    canbus = can.Bus(
  File "C:\Users\Documents\hengelo-qlab\dccb_daimler\ni_env_3_9\lib\site-packages\can\interface.py", line 120, in __new__
    bus = cls(channel, *args, **kwargs)
  File "C:\Users\Documents\hengelo-qlab\dccb_daimler\ni_env_3_9\lib\site-packages\can\util.py", line 320, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Documents\hengelo-qlab\dccb_daimler\ni_env_3_9\lib\site-packages\can\interfaces\vector\canlib.py", line 279, in __init__
    self.xldriver.xlCanFdSetConfiguration(
  File "C:\Users\Documents\hengelo-qlab\dccb_daimler\ni_env_3_9\lib\site-packages\can\interfaces\vector\xldriver.py", line 46, in check_status_initialization
    raise VectorInitializationError(
can.interfaces.vector.exceptions.VectorInitializationError: xlCanFdSetConfiguration failed (XL_ERR_WRONG_PARAMETER) [Error Code 101]
`

``` python
canbus = can.Bus(
            channel=1,
            bustype="vector",
            fd=True, # not set anymore in the xldriver?
            bitrate=500000,
            data_bitrate=5000000,
            sjw_abr=40,
            tseg1_abr=127,
            tseg2_abr=32,
            sjw_dbr=4,
            tseg1_dbr=9,
            tseg2_dbr=6,
        )
```
</details>

**Comment by zariiii9003** [comment]
I'm not sure about this but your arbitration sync jump width seems implausible to me. It cannot be greater than tseg1_abr or tseg2_abr.

**Comment by j-c-cook** [comment]
@skipper85 Were you able to get this functioning based on the comment from @zariiii9003? Is it true that `sjw_abr` must be less than `tseg1_abr` and `tsg2_abr`?

**Comment by skipper85** [comment]
Hi, currently the dongle is in use, I hope I can use it this week and do some debugging. When available I will try @zariiii9003 suggestion with the settings and in the meanwhile I will dig in about those settings.

**Comment by skipper85** [comment]
Hi,

I tried again with the vector dongle VN1610
When I use the following code:
``` Python
canbus = can.Bus(
        channel=1,
        bustype="vector",
        app_name="python_can",
        fd=True,
        bitrate=500000,
        data_bitrate=5000000
    )
```
I still receive the following exception:
`
can.interfaces.vector.exceptions.VectorInitializationError: xlCanFdSetConfiguration failed (XL_ERR_WRONG_PARAMETER) [Error Code 101]
`

**Comment by zariiii9003** [comment]
You need to set the correct bit timings for your bus. We cannot tell you how your bus is configured. If you initialize the bus with valid parameters then it works fine.

```python
import can

bus = can.Bus(
    channel=1,
    bustype="vector",
    fd=True,
    bitrate=500_000,
    data_bitrate=5_000_000,
    sjw_abr=2,
    tseg1_abr=11,
    tseg2_abr=4,
    sjw_dbr=2,
    tseg1_dbr=5,
    tseg2_dbr=2,
)
```

This should should initialize the bus with no exception. But you will get error messages if the settings are wrong for your application.

**Comment by skipper85** [comment]
Hi, thanks for your help, it does work now, also with my own settings I recalculated for the bit timings.
```
'channel':1,
'bustype':"vector",
'fd':True,
'bitrate':500_000,
'data_bitrate':5_000_000,
'sjw_abr':32,
'tseg1_abr':127,
'tseg2_abr':32,
'sjw_dbr':6,
'tseg1_dbr':9,
'tseg2_dbr':6
```
