### ISSUE TITLE
Logging Lib Import

### ISSUE THREAD

**Issue by jakka351** [hardbyte/python-can#1354]
### Describe the bug
AttributeError: module 'logging' has no attribute 'getLogger'

### To Reproduce

I am unable to use the python-can library because of this issue - I have checked that it is not my python installation that has the issue as I swapped from Linux to Windows and have the same error with different python  installations across any code that uses the logging library So this might not be a python-can specific issue

### Expected behavior

I expected my program to run, however it fails due to library import error

### Additional context
Using PySimpleGUI and Python-CAN.
Debian Linux Python 3.9
Windows 10 Python 3.9 
Same laptop Dell Latitude
OS and version:
Python version:
python-can version:
python-can interface/s (if applicable): socketcan/serial

<details><summary>Traceback and logs</summary>

```python
def func():
    return "hello, world!"
```
</details>

**Comment by zariiii9003** [comment]
`logging.getLogger' is a [builtin function](https://docs.python.org/3/library/logging.html#logging.getLogger).
There is another `logging` module or variable in your namespace, rename or remove it.

**Comment by j-c-cook** [comment]
@jakka351 Were you able to resolve this issue?
