### ISSUE TITLE
Timestamp error on python

### ISSUE THREAD

**Issue by AbdulkadirEroglu-81** [hardbyte/python-can#1356]
### Describe the bug

When sending data i am getting struct error.
İt seems like when packing timestamp there is a multiplication step and that gets data to over limit. 

### To Reproduce

send some data with time stamp field filled with python time modules time.time() function.

### Expected behavior

data to be send through serial interface

### Additional context

OS and version: Ubuntu 22.04 - Ubuntu 20.04
Python version: 3.10, 3.9
python-can version: 4.0.0
python-can interface/s (if applicable): virtual can with socat tool

![Screenshot from 2022-08-03 18-00-34](https://user-images.githubusercontent.com/105054290/182641405-45ed917e-3153-493f-b853-e377e08edcc8.png)

<details><summary>Traceback and logs</summary>

![Screenshot from 2022-08-03 18-01-46](https://user-images.githubusercontent.com/105054290/182641725-a515bb02-d273-496b-a958-e1a1f9fdae2b.png)

**Comment by j-c-cook** [comment]
What is the script `tests/SanalCan.py`? Could you please upload a minimal script that triggers the bug you are describing? I am unable to follow your "To Reproduce" section well enough to reproduce your script.

**Comment by AbdulkadirEroglu-AptiRobotics** [comment]
> What is the script tests/SanalCan.py? 

It is a script that sends random data to can network.
Here is a full code to repreduce the error

`import can, time`
`bus = can.interface.Bus(interface="serial", channel="/dev/ttyS11")`
`msg = can.Message(time.time(), 1, False, data=[0x11, 0x22, 0x33], is_rx=False)`
`bus.send(msg)`

**Comment by zariiii9003** [comment]
You can't use the serial bus with `time.time()`. The documentation says [Usually s, ms or µs since start of the device](https://python-can.readthedocs.io/en/master/interfaces/serial.html#serial-frame-format)

**Comment by AbdulkadirEroglu-81** [comment]
Oh, I didn't see that. I am closing the issue.
