### ISSUE TITLE
Detect connected interfaces in PC

### ISSUE THREAD

**Issue by ferranmercader** [hardbyte/python-can#1370]
I would like to have a function that detects if a single or multiple interfaces (and multiple brands) are connected to the computer and returns all possible info. In this way we would be able to perform a HW check for an automated environment.

I did a research but did not find any python library that performs this for common CAN interfaces, neither here in python-can.
I have started a python module for this functionality, so in case there is no implementation here, I could support if you find it appropiate.

**Comment by pierreluctg** [comment]
Please see https://python-can.readthedocs.io/en/master/api.html#can.detect_available_configs
