### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Sharmaranjan** [hardbyte/python-can#1380]
Currently python-can extracts can data only from any blf, what it does to ethernet data?
And on what parameters it is skipping?

If possible can you suggest any way or library which can extract ethernet data as well

**Comment by zariiii9003** [comment]
This library probably supports Ethernet data: https://bitbucket.org/tobylorenz/vector_blf/src/master/
But it's C++.

**Comment by Sharmaranjan** [comment]
I knew about this c++ Library, but anyway thanks.

I am looking for any python Library

**Comment by felixdivo** [comment]
The supported interfaces of this library are listed [here](https://python-can.readthedocs.io/en/master/interfaces.html). You can also interface with C++ code from python.

**Comment by felixdivo** [comment]
I think there is no clear task to complete in this issue.
