### ISSUE TITLE
Vector Hardware Question

### ISSUE THREAD

**Issue by dhje0ng** [hardbyte/python-can#1391]
Hello sir. I'm trying to inject data into a CAN bus via python-can.
Since I am connecting two VN5620 physical hardware to the PC, I think the bus connection method I think is channel 0, 1, 2, 3.

but. Only channels 0 and 1 are available, and an error occurs for the remaining channels.
`can.interfaces.vector.exceptions.VectorInitializationError: xlGetApplConfig failed (XL_ERROR) [Error Code 255]`

Can you please tell me why I am getting this error?

i tried this code.

```py
bus_channel = 0
#bus = VectorBus(bus_channel, bitrate=500000, data_bitrate=2000000, fd=True, receive_own_messages=True)
or
bus = can.interface.Bus(bustype='vector', channel=bus_channel, bitrate=500000, data_bitrate=2000000, fd=True, receive_own_messages=True)
```
![스크린샷 2022-09-13 오후 1 29 56](https://user-images.githubusercontent.com/50125695/189809002-3a07a646-da84-405d-822a-7a26fda495dd.png)

![스크린샷 2022-09-13 오후 1 30 33](https://user-images.githubusercontent.com/50125695/189809210-29b27922-615a-439c-a75a-f6dabdb8695b.png)

**Comment by zariiii9003** [comment]
The default parameter for `app_name` is `"CANalyzer"`. Either you assign the CANalyzer app to your target channel or you can use the `serial` argument instead.

**Comment by dhje0ng** [comment]
thank you sir. this problem is solved.
