### ISSUE TITLE
Add __version__ attribute at module level

### ISSUE THREAD

**Issue by Delgan** [hardbyte/python-can#142]
It is a common practice to add a `__version__` variable in the  `__init__.py` module file, so scripts can easily check it (see [PEP-8](https://www.python.org/dev/peps/pep-0008/#module-level-dunder-names) or [this StackOverflow question](http://stackoverflow.com/questions/20180543/how-to-check-version-of-python-modules)). This would indeed be useful as I found myself in such situation.

```python
>>> import can
>>> can.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'can' has no attribute '__version__'
```

It would be good to avoid repeating with the `setup.py` file, of course (however, I do not know any consensus about how to proceed).

**Comment by hardbyte** [comment]
Thanks @Delgan I've added that and made a new alpha release.
If you try install it with:
```
pip install python-can==2.0.0.a2
```

Then the new version is as you expect:
```
>>> import can
>>> can.__version__
'2.0.0-alpha.2'
```
