### ISSUE TITLE
How to send standard frames？please

### ISSUE THREAD

**Issue by gitPff** [hardbyte/python-can#1450]
I have received arbitration_id 18018a03
wen i forwarded  turn into 203 
![image](https://user-images.githubusercontent.com/25237776/204086544-ebd86541-0a0b-451f-be3e-8b834fd13905.png)

**Comment by j-c-cook** [comment]
The arbitration ID’s you received appear to be extended (29 bit), not standard (11 bit). If you’re referring to standard PGN format, you don’t need to specify PDU1 vs PDU2. Make sure `is_extended_id` is set to true. 

`message = can.Message(arbitration_id=0x18018A03, is_extended_id=True,
                         data=[0x11, 0x22, 0x33]) `

**Comment by felixdivo** [comment]
Nothing to do here. If there is a problem, please open again.
