### ISSUE TITLE
CanInitializationError due to reported can_op_mode = 0

### ISSUE THREAD

**Issue by ntstimio** [hardbyte/python-can#1453]
### Describe the bug
The CAN bus (VectorBus) cannot be created because the can_op_mode value reported by the Vector CANcaseXL driver is set to 0, which is not an expected value.

### To Reproduce
Connect the CANcaseXL to a CAN bus.
Configure the CANcaseXL using Vector HardwareConfiguration tool.
Run the following python code:

```python
from can.interfaces import vector
bus = vector.VectorBus(0)
```

### Expected behavior
The bus object shall be initialized correctly.

### Additional context

OS and version: Windows 10
Python version: 3.8.10
python-can version: 4.1.0
python-can interface/s (if applicable): Vector CANcaseXL

The setup works with BusMaster v3.2.2.

The failing test is in `can/interfaces/vector/canlib.py` line 278:

```python
if not all(
    [
        bus_params.bus_type is xldefine.XL_BusTypes.XL_BUS_TYPE_CAN,
        _can.can_op_mode
        & xldefine.XL_CANFD_BusParams_CanOpMode.XL_BUS_PARAMS_CANOPMODE_CAN20,
        _can.bitrate == bitrate if bitrate else True,
    ]
):
```

This test has been added in commit cd51ec4c07041c7b3a15b999aa4be5ec3829b05e.

Maybe it should be extended to account for the case when `_can.can_op_mode` = 0?

<details><summary>Traceback and logs</summary>

```
Traceback (most recent call last):
  File "C:/Program Files/JetBrains/PyCharm Community Edition 2022.2.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\git\xxx\essai.py", line 6, in <module>
    bus = vector.VectorBus(0)
  File "C:\git\xxx\venv\lib\site-packages\can\util.py", line 337, in wrapper
    return f(*args, **kwargs)
  File "C:\git\xxx\venv\lib\site-packages\can\interfaces\vector\canlib.py", line 286, in __init__
    raise CanInitializationError(
can.exceptions.CanInitializationError: The requested CAN settings could not be set for channel 0. Another application might have set incompatible settings. These are the currently active settings: {'bitrate': 250000, 'sjw': 1, 'tseg1': 10, 'tseg2': 5, 'sam': 1, 'output_mode': <XL_OutputMode.XL_OUTPUT_MODE_NORMAL: 1>, 'can_op_mode': <XL_CANFD_BusParams_CanOpMode.0: 0>}
python-BaseException
```

</details>

**Comment by zariiii9003** [comment]
That one is on me. To be fair, that behavior is not documented:
![image](https://user-images.githubusercontent.com/52598363/204655572-4007f3ca-2081-4922-9a3a-689c8b8976b1.png)

So there are no other applications active on that bus? Do you have init access? Does it work if you comment out just that one line with the canOpMode check?

Btw, thank you for the well written bug report and analysis.

**Comment by zariiii9003** [comment]
@ntstimio Can you check what the value of can_op_mode is, when you are connected via BusMaster?

You could check it like this:
```python3
from can.interfaces.vector import get_channel_configs

for vcc in get_channel_configs():
    print(vcc.name, vcc.bus_params)
```

**Comment by MGoesswein** [comment]
I also have a Vector CanCaseXl equipped with two CAN Piggies and have the same issue.

As already written by ntstimio: 
can_op_mode is zero and checked against 1 (xldefine.XL_CANFD_BusParams_CanOpMode.XL_BUS_PARAMS_CANOPMODE_CAN20) in canlib.py, which raises an exception.

![grafik](https://user-images.githubusercontent.com/46593533/212057076-800e4fa1-117a-4ad9-bf27-a088cf4ddb35.png)

There is no value defined for 0, but it seems that 0 shall also be considered as CAN2.0 compatible. 
Maybe it is only related to older Vector interfaces, because it works if I use a VN7610 interface instead.

**Some Versions as reference:**

**Python:**
Python 3.8.5
python_can-4.1.0

**CanCaseXL:**
Hardware Revision 3.0
Vector Driver/Firmware: 8.7.16 (newest for CanCaseXl)
Internally equipped with 2x CANpiggy 1041Amag (Highspeed), Hardware revision 2

**VN7610:** 
Hardware Revision 2.0
Vector Driver/Firmware: 20.30.14

**Comment by zariiii9003** [comment]
Thanks for the confirmation. You say 

> There is no value defined for 0, but it seems that 0 shall also be considered as CAN2.0 compatible.

Does it work with CAN FD? Or is CanCaseXl incompatible to FD?

**Comment by MGoesswein** [comment]
> Does it work with CAN FD? Or is CanCaseXl incompatible to FD?

CanCaseXL only supports CAN2.0, no CAN FD. 
This interface is quite old and not sold anymore by vector, but works great for CAN2.0 messages.  Maybe CanOpMode is not implemented (or not correctly implemented) in the driver of CanCaseXL. There was no update of the CanCaseXL driver/firmware in the last years.

**Comment by zariiii9003** [comment]
Try #1486 please. I will merge it if it works okay for you.

**Comment by MGoesswein** [comment]
Yes, looks good, the exception is gone.
