### ISSUE TITLE
generate .exe file with auto-py-to-exe tool unable to connect with can hardware

### ISSUE THREAD

**Issue by LucioMater** [hardbyte/python-can#1473]
Hello to everybody I have problems with exe generating from python scrips that use python-can library:

my  simple test script:
"import can

bustype = 'pcan'
channel = 'PCAN_USBBUS1'
bitrate = 250000

bus = can.interface.Bus(
    bustype='pcan', channel='PCAN_USBBUS1', bitrate=250000
)
print("ok")"

the generating command that I have used is:
"pyinstaller --noconfirm --onedir --console  "mypath/test.py"

the scripts works, the executable returned this error:
"Traceback (most recent call last):
  File "provacan.py", line 7, in <module>
  File "can\interface.py", line 104, in __new__
  File "can\interface.py", line 42, in _get_class_for_interface
can.exceptions.CanInterfaceNotImplementedError: Cannot import module can.interfaces.pcan for CAN interface 'pcan': No module named 'can.interfaces.pcan'" 

Thanks

OS and version: Windows 10
Python version:  3.10
python-can version: 4.0.0

**Comment by zariiii9003** [comment]
No code example, no traceback, you don't even mention which interface you are using. 
Does it work without auto-py-to-exe?

**Comment by LucioMater** [comment]
Yes the script works, i have problems only with executables

**Comment by j-c-cook** [comment]
You likely need to look at the documentation of the executable creator package you are using. There are typically limited documentation on writing custom bindings. You may need to write a binding of your own. Python packages that create executables typically ship with the bindings for major packages (e.g. numpy, scipy, etc.). `python-can` is likely not included in their standard package.

**Comment by LucioMater** [comment]
> You likely need to look at the documentation of the executable creator package you are using. There are typically limited documentation on writing custom bindings. You may need to write a binding of your own. Python packages that create executables typically ship with the bindings for major packages (e.g. numpy, scipy, etc.). `python-can` is likely not included in their standard package.

yes thanks with the folllowing command it works:
"pyinstaller --hidden-import=can.interfaces.pcan --onefile test.py"
