### ISSUE TITLE
Issue with can.send_periodic

### ISSUE THREAD

**Issue by EmilianoMaina** [hardbyte/python-can#150]
Hi,
after few months successfully using python can on my heat pump reading data from CAN Bus in a request / sync receive, I am not able to move to a request / async receive.

I was able to implement the listener. The issue is with periodical sending of data on the bus.

This is the error:

`pi@raspberrypi:~/pyHPSU-master $ python3 pyListener.py
Traceback (most recent call last):
  File "pyListener.py", line 88, in <module>
    task = can.send_periodic('can0', msg, 15.0)
  File "/home/pi/pyHPSU-master/can/broadcastmanager.py", line 75, in send_periodic
    return can.interfaces.interface.CyclicSendTask(channel, message, period)
AttributeError: 'module' object has no attribute 'CyclicSendTask'
`
And this is the corresponding source:

`
# ....
try:
    import can
except Exception:
    pass
# ....
dati = [
    [bytes([0x32, 0x10, 0xFA, 0xC0, 0xF6]), "mode",            [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0xC0, 0xFB]), "bpv",             [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0x06, 0x9B]), "posmix",          [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0xC0, 0xF7]), "pump",            [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0xC0, 0xFC]), "t_v1",            [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0xC0, 0xFD]), "t_dhw1",          [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0xC0, 0xFE]), "t_vbh",           [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0xC1, 0x00]), "t_r1",            [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0xC0, 0xF9]), "ehs",             [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x62, 0x10, 0x04, 0x00, 0x00]), "t_hc_set",        [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0x03, 0x00, 0x00]), "t_dhw_set",       [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x62, 0x10, 0xFA, 0x0A, 0x0C]), "t_ext",           [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0xC0, 0xFF]), "t_outdoor_ot1",   [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0xC1, 0x05]), "ta2",             [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0x13, 0x00, 0x00]), "t_dhw_setpoint1", [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0x06, 0x91]), "hyst_hp",         [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0x01, 0x12]), "mode_01",         [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
    [bytes([0x32, 0x10, 0xFA, 0x01, 0xDA]), "flow_rate",       [0.0, 0.0, 0.0, 0.0, 0.0], 0.0, 0.0],
]

# ....

msg = can.Message(arbitration_id=0x190, data=dati[14][0], extended_id=False, dlc=5)
task = can.send_periodic('can0', msg, 15.0)

try:
    while True:
        time.sleep(15)
        power = 1.163 * float(dati[17][2][0]) * 0.1 * ( float(dati[6][2][0]) - float(dati[7][2][0]) + 0.379 + 0.111)
        print(power)
except KeyboardInterrupt:
    bus.shutdown()
`

I am working with Raspberry + PiCAN2 board. Python version 3.4.2

How could I further troubleshoot ?

**Comment by EmilianoMaina** [comment]
Realized that I wasn't using latest python can release. Upgraded but changed only the error:

`Traceback (most recent call last):
  File "pyListener.py", line 88, in <module>
    task = can.send_periodic('can0', msg, 15.0)
  File "/home/pi/pyHPSU-master/can/broadcastmanager.py", line 75, in send_periodic
    return can.interfaces.interface.CyclicSendTask(channel, message, period)
AttributeError: 'module' object has no attribute 'CyclicSendTask'


{'interface': 'socketcan_native', 'channel': 0}
Traceback (most recent call last):
  File "pyListener.py", line 88, in <module>
    task = can.send_periodic('can0', msg, 15.0)
  File "/usr/local/lib/python3.4/dist-packages/can/broadcastmanager.py", line 72, in send_periodic
    return can.interface.CyclicSendTask(channel, message, period)
  File "/usr/local/lib/python3.4/dist-packages/can/interfaces/interface.py", line 99, in __new__
    return cls(channel, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/can/interfaces/socketcan_native.py", line 150, in __init__
    super(CyclicSendTask, self).__init__(channel, message, period)
  File "/usr/local/lib/python3.4/dist-packages/can/interfaces/socketcan_native.py", line 137, in __init__
    self.bcm_socket = create_bcm_socket(channel)
  File "/usr/local/lib/python3.4/dist-packages/can/interfaces/socketcan_native.py", line 122, in create_bcm_socket
    s = socket.socket(socket.PF_CAN, socket.SOCK_DGRAM, socket.CAN_BCM)
  File "/usr/lib/python3.4/socket.py", line 123, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 93] Protocol not supported`

**Comment by EmilianoMaina** [comment]
And this is how can interfface is up:

`sudo /sbin/ip link set can0 up type can bitrate 20000`

**Comment by hardbyte** [comment]
Hi Emiliano

I'm aware of a few issues with `send_periodic` so I've been working on a new version - hopefully with a cleaner api too. Could you try out the branch [feature-periodic-send-api](https://github.com/hardbyte/python-can/tree/feature-periodic-send-api).

Note the code will have to change to:

```
task = bus.send_periodic(msg, 0.20)
```

Please let me know how you get on. I've tested periodic sending with my PiCAN2 board with Python3.5

**Comment by EmilianoMaina** [comment]
Thanks hardbyte.
Just for my clarity: should I download the full branch and substitute current version on my Raspberry ?

**Comment by EmilianoMaina** [comment]
I downloaded the branch and copied the can directory.
Changed the code.

But I still have the same error:

`Traceback (most recent call last):
  File "pyListener.py", line 95, in <module>
    task = bus.send_periodic(msg, 15.0)
  File "/home/pi/pyHPSU-master/can/interfaces/socketcan/socketcan_native.py", line 448, in send_periodic
    task = CyclicSendTask(self.channel, msg, period)
  File "/home/pi/pyHPSU-master/can/interfaces/socketcan/socketcan_native.py", line 202, in __init__
    super(CyclicSendTask, self).__init__(channel, message, period, duration=None)
  File "/home/pi/pyHPSU-master/can/interfaces/socketcan/socketcan_native.py", line 181, in __init__
    self.bcm_socket = create_bcm_socket(channel)
  File "/home/pi/pyHPSU-master/can/interfaces/socketcan/socketcan_native.py", line 126, in create_bcm_socket
    s = socket.socket(socket.PF_CAN, socket.SOCK_DGRAM, socket.CAN_BCM)
  File "/usr/lib/python3.4/socket.py", line 123, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 93] Protocol not supported
`

**Comment by christiansandberg** [comment]
Sounds like an issue with your Linux. Which dist are you using?

**Comment by EmilianoMaina** [comment]
`Linux raspberrypi 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux`

**Comment by EmilianoMaina** [comment]
Upgraded Python to the latest release available but nothing changed:

`Traceback (most recent call last):
  File "pyListener.py", line 95, in <module>
    task = bus.send_periodic(msg, 15.0)
  File "/home/pi/pyHPSU-master/can/interfaces/socketcan/socketcan_native.py", line 448, in send_periodic
    task = CyclicSendTask(self.channel, msg, period)
  File "/home/pi/pyHPSU-master/can/interfaces/socketcan/socketcan_native.py", line 202, in __init__
    super(CyclicSendTask, self).__init__(channel, message, period, duration=None)
  File "/home/pi/pyHPSU-master/can/interfaces/socketcan/socketcan_native.py", line 181, in __init__
    self.bcm_socket = create_bcm_socket(channel)
  File "/home/pi/pyHPSU-master/can/interfaces/socketcan/socketcan_native.py", line 126, in create_bcm_socket
    s = socket.socket(socket.PF_CAN, socket.SOCK_DGRAM, socket.CAN_BCM)
  File "/usr/local/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 93] Protocol not supported
`

**Comment by EmilianoMaina** [comment]
Hello, any hints on my problem ? Thanks !

**Comment by altran-git** [comment]
I had the same issues with RaspberryPi.  I've posted my findings at this thread:

https://bitbucket.org/hardbyte/python-can/issues/60/problem-using-cyclic-message

**Comment by EmilianoMaina** [comment]
In fact I didn't to anything different from what described above but retrying now after a few days retrying is now working. Thanks for the support !
