### ISSUE TITLE
Arbitration ID corruption and extended id mishandling with socketcand

### ISSUE THREAD

**Issue by faisal-shah** [hardbyte/python-can#1504]
### Describe the bug
socketcand uses the length of the arbitration id field to indicate whether a frame is using extended id or not. 3 characters for standard, 8 for extended.

Prior to this fix, the arbitration id would be truncated to the lower 11 bits, or at times even garbage. This is because the length of the arbitration id string was not controlled. The is_extended_id attribute of the Message was also not set properly upon receiving a frame from socketcand.

### To Reproduce
Create a bridge between socketcan (vcan1) and socketcand (vcan0). Use cangen (standard) and cangen -e (extended) to generate can frames on each interface, and see the resulting mismatch in can frames. See code example below for such a bridge.

### Expected behavior
The correct arbitration id and whether or not the frame is standard or extended should be reflected on the bus.

### Additional context

<details><summary>Traceback and logs</summary>

```python
#!/usr/bin/env -S python
# test.py

import asyncio
import can

async def rx_loop_gen (bus1, bus2):
    async def loop():
        reader = can.AsyncBufferedReader()
        loop = asyncio.get_running_loop()
        notifier = can.Notifier(bus1, [reader], loop=loop)
        async for msg in reader:
            print(f"id:{msg.arbitration_id:x}, ext={msg.is_extended_id}")
            bus2.send(msg)

    return loop


async def main():
    import argparse
    parser = argparse.ArgumentParser(description='python-can to socketcand bridge')
    parser.add_argument('-i', '--interface', required=False, default='socketcan')
    parser.add_argument('-c', '--channel', required=False, default='vcan1')
    parser.add_argument('-a', '--addr', required=False, default = 'localhost')
    parser.add_argument('-p', '--port', required=False, default = 29536)
    args = parser.parse_args()

    bus_pycan = can.Bus(interface=args.interface, channel=args.channel)
    bus_socketcand = can.Bus(interface='socketcand', host=args.addr, port = args.port, channel='vcan0')

    l1 = await rx_loop_gen(bus_pycan, bus_socketcand)
    l2 = await rx_loop_gen(bus_socketcand, bus_pycan)

    await asyncio.gather(l1(), l2())

if __name__ == '__main__':
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass

```

vcan0: socketcand
vcan1: socketcan
test.py above bridges those two interfaces
```
$ cangen -e vcan1 # This is generating extended frames on the socketcan device
```

Below is the output of the test.
Top window: Output of the bridge above. It is printing the arbitration id, and the is_extended_id attribute upon a message received. In this case that would be the socketcan device notifier.
Middle window: candump vcan0 # socketcand
Bottom window: candump vcan1 # socketcan

![image](https://user-images.githubusercontent.com/37458679/214763764-1f9cd06b-0606-46e8-bd15-7b3d72687fe2.png)

As you can see, the arbitration id is corrupted on the socketcand device. This is due to not formatting the arbitration id properly.

</details>

#1503

**Comment by zariiii9003** [comment]
Fixed by #1508
