### ISSUE TITLE
question: decoding large J1939 messages

### ISSUE THREAD

**Issue by acode-x** [hardbyte/python-can#1513]
Hi,

I have a query regarding handling J1939 messages having length > 8 bytes.
I am using https://github.com/nberlette/canbus/blob/main/dbc/j1939.dbc as a reference.
It has messages:
```bash
BO_ 2633939198 GTFI: 22 Vector__XXX
 SG_ ...

BA_ "GenMsgSendType" BO_ 2633939198 8;
BA_ "VFrameFormat" BO_ 2633939198 3;


BO_ 2633832958 ILI: 200 Vector__XXX
 SG_ ...
 
BA_ "VFrameFormat" BO_ 2633832958 3;
```

I have used python-can (SocketCAN) to decode standard messages of length 8 bytes, but not sure how to read and process length 22 / 200.
Requesting guidance on same.

Thanks

**Comment by j-c-cook** [comment]
I am familiar with a CAN base frame format and an extended frame format (see ISO 11783 part 3). Both of those formats have a 64 bit data field. Can a message with more than 64 bits be sent, or do you have to send multiple messages?

**Comment by zariiii9003** [comment]
J1939 defines a transport protocol, so you don't really need to work on raw CAN message level.
Check https://github.com/juergenH87/python-can-j1939 or https://github.com/danielhrisca/asammdf if you can log to mf4 format.

**Comment by acode-x** [comment]
I was referring to multi frame (TP.CM and TP.DT)
Thanks for sharing above link python-can-j1939.
