### ISSUE TITLE
can.interfaces.serial conflicts with pyserial

### ISSUE THREAD

**Issue by RyanHope** [hardbyte/python-can#1533]
pyserial provides the serial package which has a namespace conflict in the seeedstudio bus (and possibly other interfaces using pyserial) with the can.interfaces.serial package

should probably rename can.interfaces.serial to can.interfaces.serial_can

**Comment by zariiii9003** [comment]
That's a breaking change. Can you provide an example where an aliased import can not solve the problem?

**Comment by RyanHope** [comment]
> That's a breaking change. Can you provide an example where an aliased import can not solve the problem?

I guess I don't care how its fixed, but interfaces are currently broken.

**Comment by zariiii9003** [comment]
> I guess I don't care how its fixed, but interfaces are currently broken.

Could you share the traceback?

**Comment by RyanHope** [comment]
> > I guess I don't care how its fixed, but interfaces are currently broken.
> 
> Could you share the traceback?

instantiate a seeedstudio bus, it will fail because serial.Serial does not exist

**Comment by RyanHope** [comment]
Im gonna close this for now because I can never get inbranch version of the seeedstudio interface to work. I have to rely on my own implementation and that seems to be working right now without renaming any branches.

**Comment by zariiii9003** [comment]
> instantiate a seeedstudio bus, it will fail because serial.Serial does not exist

Did you install pyserial? I cannot reproduce your error. If it was broken, i'm sure we would get complaints about it.
