### ISSUE TITLE
error frames are in wrong channel when writing asc files

### ISSUE THREAD

**Issue by wangdian1167** [hardbyte/python-can#1578]
### Describe the bug
When writing to an asc file, error frames are always written to channel 1.

### To Reproduce
write the asc file and set the error frame to channel 3 by using  `msg.channel = 3`.
then open the generated asc file, you will find the error frame is in channel 1.

### Expected behavior
the error frame in asc file should be in channel 3.

### Additional context
in asc.py file, this should be `msg.channel`, not `self.channel`, because  the self.channel is set to 1 as default.
![Snipaste_2023-04-27_22-00-33](https://user-images.githubusercontent.com/12740725/234885609-c9a14125-d8d2-43aa-b3e2-ba245b6c2cae.png)

OS and version:
Python version:
python-can version: 4.2.0
python-can interface/s (if applicable):

**Comment by zariiii9003** [comment]
Would you like to create a PR?
