### ISSUE TITLE
ASCReader doesn't show messages with negative timestamp

### ISSUE THREAD

**Issue by ghost** [hardbyte/python-can#1595]
### Describe the bug

ASCReader doesn't show messages with negative timestamp

### To Reproduce

open .asc-file which contains messages with negative timestamps
print all messages from the.asc-file

### Expected behavior

every messages gets printed

### Additional context

OS and version: Win
Python version: 3.7
python-can version: 4.2.0
python-can interface/s (if applicable):

<details><summary>Traceback and logs</summary>

```python
def func():
    return "hello, world!"
```
</details>

**Comment by hartkopp** [comment]
Should it?
AFAIK the time in the ASC files is always a positive value. And all the examples in the Vector documents don't show a  negative timestamp.
Do you have an example (created by a Vector tool!) that has a negative timestamp in an ASC file?

**Comment by hartkopp** [comment]
Hi @ITgenieur ,
I'm still not sure if this is the right way to go.

I've never seen negative timestamps so far and I would assume the used MF4 Converter handles timestamps in a wrong way. So what would a negative timestamp mean for the other components in can/io/ ? Will they be able to handle negative values?

Maybe allowing negative timestamps in the ASCReader opens Pandora's box ?!?

**Comment by hartkopp** [comment]
Which MF4 converter are you using? I would check how the MF4 to ASC converter was able to generate negative timestamps.
I would suggest to fix the generator of the unusual data.

If you check out the Vector Documentation it also looks like that timestamps start with 0:
https://support.vector.com/kb?id=kb_article_view&sysparm_article=KB0011969&sys_kb_id=831502281b2614148e9a535c2e4bcb3c&spa=1

**Comment by hartkopp** [comment]
Just for the records: Which MF4 Converter did you use?
