### ISSUE TITLE
Decoding device name with chinese characters fails

### ISSUE THREAD

**Issue by Svalann** [hardbyte/python-can#1612]
### Describe the bug
I have an issue with decoding a kvaser device name with chinese characters.

It has the Device Name:	Kvaser 立富L	

When trying to connect it fails in in canlib.py

```
def get_channel_info(channel):
    name = ctypes.create_string_buffer(80)
    serial = ctypes.c_uint64()
    number = ctypes.c_uint()

    canGetChannelData(
        channel,
        canstat.canCHANNELDATA_DEVDESCR_ASCII,
        ctypes.byref(name),
        ctypes.sizeof(name),
    )
    canGetChannelData(
        channel,
        canstat.canCHANNELDATA_CARD_SERIAL_NO,
        ctypes.byref(serial),
        ctypes.sizeof(serial),
    )
    canGetChannelData(
        channel,
        canstat.canCHANNELDATA_CHAN_NO_ON_CARD,
        ctypes.byref(number),
        ctypes.sizeof(number),
    )

    return f"{name.value.decode('ascii')}, S/N {serial.value} (#{number.value + 1})"
```

### To Reproduce
I'm not able to reproduce this error. On my computer it is replaced with '?' which is fine

My computer:
OS Name 	Microsoft Windows 11 Pro
Version	        10.0.22621 Build 22621

User computer is unknown.

### Additional context
OS and version: unknown
Python version: 3.7.9
python-can version: 4.1.0
python-can interface: Kvaser EAN: 73-30130-00435-1 (i think an older Kvaser leaf light)

### Trace

File "python\lib\site-packages\can\interface.py", line 127, in __new__
  File "python\lib\site-packages\can\interfaces\kvaser\canlib.py", line 441, in __init__
  File "python\lib\site-packages\can\interfaces\kvaser\canlib.py", line 716, in get_channel_info
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)

**Comment by lumagi** [comment]
You are correct, the byte string is decoded as ASCII string, which obviously doesn't accommodate for Chinese characters. Do you know if the string you pasted above is encoded in UTF-8? Can you also provide the device name as hex string?

@zariiii9003 Do you think it would make sense to change to UTF-8 and use `errors='replace'` to avoid such errors in the future? As far as I understand, the value is merely used for printing status information.

**Comment by zariiii9003** [comment]
@lumagi If that works, sure.

It's a bit weird though, the Kvaser docs says for `canCHANNELDATA_DEVDESCR_ASCII`:

> This define is used in [canGetChannelData()](https://www.kvaser.com/canlib-webhelp/group__can__general.html#gab9552d1a588b0dbc144b097acba017b2), buffer mentioned below refers to this functions argument.
> buffer points to a buffer which receives the product name of the device as a zero-terminated ASCII string.

We could also use `canCHANNELDATA_DEVDESCR_UNICODE`, but that is not available on linux.

**Comment by lumagi** [comment]
Ok, then it probably makes the most sense to keep the ASCII character set but make it less susceptible to errors. I opened a PR to test the behavior and change the error handling (see #1613 ).

**Comment by lumagi** [comment]
@Svalann It's interesting that this bug does not occur on your platform. The unit test I wrote for this purpose fails for non-ASCII characters on Windows with Python 3.8. Can you give additional info about your setup?

**Comment by Svalann** [comment]
> @Svalann It's interesting that this bug does not occur on your platform. The unit test I wrote for this purpose fails for non-ASCII characters on Windows with Python 3.8. Can you give additional info about your setup?

Nice weekend response!

I agree, I couldn't figure out why it didn't fail on my platform. I'm not sure what more info I have, I have CANLIB version 5.40. The information from the Kvaser Device Guide displays that I have Windows 10 (Version 10.0, Build 0, 64-bit Edition) but as I mentioned in the report I have Win 11.

I realize I never tried running my program from the exuctable on my computer but only directly from the editor (VS code 1.79.0), don't know If that could make a difference but maybe. I don't have access to the dongle until tomorrow so I can't test anything until then.

In canlib.py line 716: 
`return f"{name.value.decode('ascii')}, S/N {serial.value} (#{number.value + 1})"`
name.value is already b"Kvaser ??L" so it seems it already has been replaced before that. I can't figure out where to trace this so I can see the actual hex string.
