### ISSUE TITLE
canplayer in setup.py clashes with can-utils

### ISSUE THREAD

**Issue by royemmerich** [hardbyte/python-can#162]
The Linux `can-utils` package already has a [`canplayer`](https://github.com/linux-can/can-utils) binary which clashes with the `canplayer` entry point in the latest [`setup.py`](https://github.com/hardbyte/python-can/blob/develop/setup.py#L31).

Trying to compile my yocto image results in the following error:

```
Collected errors:
 * check_data_file_clashes: Package can-utils wants to install file /home/phyvm/yocto_builds_PD16.2.0/build/tmp/work/phyboard_regor_am335x_1-phytec-linux-gnueabi/phytec-headless-image/1.0-r0/rootfs/usr/bin/canplayer
	But that file is already provided by package  * python-can
 * opkg_install: Cannot install package packagegroup-hwtools.
```

Removing it from `setup.py` resolves the problem.

**Comment by christiansandberg** [comment]
What should it be named instead? Maybe canlogplayer?

**Comment by royemmerich** [comment]
what about `pycanplayer` or `python_canplayer`?

**Comment by hardbyte** [comment]
What about removing the scripts and just having them as modules?

```
$ python -m can.player
$ python -m can.logger
$ python -m can.server
```

**Comment by christiansandberg** [comment]
I personally prefer that way since I have control over which interpreter is used. But it is harder to remember.
