### ISSUE TITLE
"No init access" mode - Vector Bus in FD bus

### ISSUE THREAD

**Issue by geynis** [hardbyte/python-can#1707]
https://github.com/hardbyte/python-can/blob/f0634d2445f74f8c5c3b90236975f73fe3d8ba2a/can/interfaces/vector/canlib.py#L228-L229

It seems that the only way to do "no init access" (connect to already setup bus by another process) is with classic CAN.
Why it is needed to test the FD parameter and it is not enough to just check if the user set the bitrate to None or 0?

**Comment by zariiii9003** [comment]
Can you try this branch? https://github.com/zariiii9003/python-can/tree/vector_assert_timings
