### ISSUE TITLE
Add CAN Trove classifier

### ISSUE THREAD

**Issue by cfsok** [hardbyte/python-can#1730]
I recently added a new CAN Trove classifier on PyPI and I think this project could use it too.

```
Topic :: Software Development :: Embedded Systems
Topic :: Software Development :: Embedded Systems :: Controller Area Network (CAN)
```

Reference: https://pypi.org/classifiers/

**Comment by zariiii9003** [comment]
That's nice! Would you submit a PR?

**Comment by cfsok** [comment]
No problem. I added both classifiers in the PR. I'll leave the merge to you.
(I messed the process a little bit as I don't have much experience with contributions... hopefully all good.)
