### ISSUE TITLE
ASCWriter not writing CAN Frames in Vector compatible format (and therefore ASCReader fails to read file back)

### ISSUE THREAD

**Issue by JayTeeBat** [hardbyte/python-can#1779]
Disclaimer: This is my first issue posted here, my apologies if I overlooked some guidelines/conventions!

### Describe the bug
When logging CAN frames to file using ASCWriter, the format is not compliant with the format specified by Vector in the file:
`CAN_LOG_TRIGGER_ASC_Format.pdf` 
Vector format is defined as (Format since v8.0):
`<Time> <Channel> <ID> <Dir> d <DLC> <D0> <D1>...<D8> Length =<MessageDuration> BitCount = <MessageLength> ID = <IDnum><MessageFlags>`

Actual output in .asc sample file:
> date Mon May 13 04:34:22.427 PM 2024  
base hex  timestamps absolute
internal events logged
Begin Triggerblock Thu Jan 01 01:00:00.0 AM 1970
 0.000000 Start of measurement
 0.000000 Timestamp: 1714055256.000000    ID: 18ff3127    X Rx                DL:  6    12 f3 3b 45 cc 6e
End TriggerBlock

When reading the .asc generated using ASCReader, and iterating over the message, nothing is yielded.

### To Reproduce

```
import can
can_msgs = [can.Message(timestamp=1714055256, arbitration_id=419377447, data=[0x12, 0xF3, 0x3b, 0x45, 0xcc, 0x6e])]
asc_writer = can.ASCWriter("dummy_data.asc")
for msg in can_msgs:
    asc_writer.log_event(msg)
asc_writer.stop()
```

### Expected behavior

Format similar to:
> date Thu Mar 28 11:8:34 am 2024
base hex  no internal events logged
// version 7.1.0
40114.200900 1 750 Rx d 8 28 3F 82 1F 3D 3F 82 4A 
40114.208700 1 750 Rx d 8 29 F1 3F 82 48 08 3F 82 
40114.216500 1 100 Rx d 4 FF FF FF 15

### Additional context

OS and version: Windows 11 v10.0
Python version: 3.10.11
python-can version: 4.3.1 & 4.3.2rc4
python-can interface/s (if applicable): N/A

<details><summary>Traceback and logs</summary>

</details>

**Comment by pierreluctg** [comment]
This is because you are not calling the right API

```python
import can
can_msgs = [can.Message(timestamp=1714055256, arbitration_id=419377447, data=[0x12, 0xF3, 0x3b, 0x45, 0xcc, 0x6e])]
asc_writer = can.ASCWriter("dummy_data.asc")
for msg in can_msgs:
    asc_writer.on_message_received(msg)
    # or asc_writer(msg)
    
asc_writer.stop()
```

See examples and doc on how to use Loggers
https://github.com/hardbyte/python-can/blob/main/examples/simple_log_converter.py
https://python-can.readthedocs.io/en/stable/listeners.html#logger

**Comment by JayTeeBat** [comment]
@pierreluctg just looked at the example and the code again, makes perfect sense.

Thanks for taking the time to reply and sorry for the silly question, I realize the proper operation of the reader/writers was duly tested, I just couldn't figure out my mistake.
