### ISSUE TITLE
CAN FD for Vector Hardware Interface

### ISSUE THREAD

**Issue by HumbertBertrandt** [hardbyte/python-can#1783]
### Description:
After many tries I suppose that the Vector Hardware is not implemented in the library for sending can fd messages. I would like to know if that is the case and when it is expected to be implemented.

### Expected solution:
I would like to send CAN FD messages using a Vector Interface and this python module. When the message exceeds 8 bytes the library raises an exception.

### Additional context:
For Automotive software development

**Comment by zariiii9003** [comment]
The vector implementation supports CAN FD since 2018.
