### ISSUE TITLE
Ixxat V3 download?

### ISSUE THREAD

**Issue by mgiaco** [hardbyte/python-can#185]
Hi where can I find the Ixxat v3 driver?  I did not find any download link.

Are there any plans to support v4?
https://www.ixxat.com/products/products-industrial/pc-interfaces/pc-can-interfaces/windows

many thanks

**Comment by cowo78** [comment]
https://www.ixxat.com/support/file-and-documents-download/drivers/vci-v3-driver-download

After a 2-minutes scan it seems the interface has been changed quite a bit. As for future plans I currently don't need V4 package so it's no.

**Comment by mgiaco** [comment]
okay many thanks.
