### ISSUE TITLE
Modules args parser does not accept parameters with numbers

### ISSUE THREAD

**Issue by isaacag** [hardbyte/python-can#1867]
### Describe the bug
This line contains a regex that will fail to parse arguments containing numbers.
[if not re.match(r"^--[a-zA-Z\-]*?=\S*?$", arg):](https://github.com/hardbyte/python-can/blob/d4f3954b726e857528d605ea88888aab322f1750/can/logger.py#L148)
Producing errors like: 
ValueError: Parsing argument --tseg1-abr=127 failed.

### To Reproduce
python -m can.viewer -c 0 -i vector -b 500000 --fd --data_bitrate 2000000 --sjw-abr=32 --tseg1-abr=127 --tseg2-abr=32 --sjw-dbr=8 --tseg1-dbr=31 --tseg2-dbr=8

### Expected behavior
Extra args values are accepted.

### Additional context

OS and version: Windows 10 Pro
Python version: 3.12
python-can version: 4.4.2
python-can interface/s (if applicable): vector

**Comment by zariiii9003** [comment]
Thanks for the report, it should be fixed on main branch now. Could you also try #1869 ? I implemented a `--timing` parameter a few months ago and forgot about it.
