### ISSUE TITLE
documentation errors in usb2can windows instructions

### ISSUE THREAD

**Issue by LivingInSyn** [hardbyte/python-can#193]
I appear to have things working now, but there were a few issues discovered while following the instructions:

1) usb2canWin.py doesn't exist (referenced in find serial number section)

2) usb2can.dll (USB2CAN CANAL DLL) will NOT be loaded if it's in the DLLs directory in python install directory (at least on my machine/setup), it must be in the same directory as usb2can.py

**Comment by MasterCodeIT** [comment]
> 
> 
> I appear to have things working now, but there were a few issues discovered while following the instructions:
> 
>     1. usb2canWin.py doesn't exist (referenced in find serial number section)
> 
>     2. usb2can.dll (USB2CAN CANAL DLL) will NOT be loaded if it's in the DLLs directory in python install directory (at least on my machine/setup), it must be in the same directory as usb2can.py

I do not see a usb2can.py in the repository. I attempted to put the USB2CAN CANAL DLL in the USB2CAN library in the usb2can directory but I still get the error: 

FileNotFoundError: Could not find module 'usb2can.dll' (or one of the dependencies). Try using the full path with the constructor syntax.
