### ISSUE TITLE
Discussion: Should commands like "ip link ..." be part of this library?

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#213]
Many people have to put some lines for setting up the can into their scripts, which is quite error prone (in my opinion). As I am working with socketcan, setting up a virtual can interface works differently than a hardware interface and calling commands und parsing their output can be tedious. 

It would be nice if the library could support this out of the box, or at least for unix-like systems. I think it would be portable enough for most of the popular systems, and there could be a clear statement that it only supports some specific platforms on which it was tested. 

Supporting this might introduce other problems and slightly shifts the scope of this library. But it would also help with abstracting from the underlying system in general (and only the hardware), while having pretty much no performance impact and staying optional.

**Comment by christiansandberg** [comment]
Wouldn't this require the script to be run as root?

**Comment by felixdivo** [comment]
Bah. Didn't think of that. But in general, yes, I think so.

**Comment by felixdivo** [comment]
But in my environment I have set the `NOPASSWD` flag in the `/etc/sudoers` file for `/sbin/ip`. In that case, I would work.

**Comment by felixdivo** [comment]
This does not belong really into this library, and would inflate it a lot. I will not add it to this repo. If someone ever needs this, just comment here.
