### ISSUE TITLE
Vector CAN interfaces

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#22]
Originally reported by: **KotiReddy Marepally (Bitbucket: [kmarepally](https://bitbucket.org/kmarepally), GitHub: Unknown)**

---

Hello,

Is it possible to work with Vector CAN interfaces with same code base?
Could please help to enable Vector CAN interfaces(CanCase, VN1610)?

Regards,
Koti

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/22

**Comment by christiansandberg** [comment]
Should be solved in #182.
