### ISSUE TITLE
test/simplecyclic_test.py often fails

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#243]
The fails can be seen on [Linux](https://travis-ci.org/hardbyte/python-can/jobs/339738832) and [OSX](https://travis-ci.org/hardbyte/python-can/jobs/339866694). It seems like that test works rather non-deterministic.

**Comment by felixdivo** [comment]
`test/back2back_test.py::Back2BackTestCase::test_timestamp` might also be problematic. See [here](https://travis-ci.org/hardbyte/python-can/jobs/339885966).

These tests might fail on the CI server but not on our own machines since the CI servers may be slower and are virtualized.

**Comment by felixdivo** [comment]
bb23d5b adds a better failure message.

**Comment by hardbyte** [comment]
Maybe a better approach would be to skip the tests are running on travis

**Comment by hardbyte** [comment]
How about using the `unittest.skipIf` decorator to always skip running these flaky tests _if_ on travis?

**Comment by felixdivo** [comment]
`unittest.skipIf` would be the simplest and does the job I think.
