### ISSUE TITLE
can_filters should be backported to socketcan_ctypes

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#25]
Originally reported by: **Michael Muldoon (Bitbucket: [mbmuldoon07](https://bitbucket.org/mbmuldoon07), GitHub: [mbmuldoon07](https://github.com/mbmuldoon07))**

---

The can filters does not appear to work at least with socketcan_ctypes.  I've tried anything I can think of when adding the can_filter to the bus but no matter what there appears to be no filtering.

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/25

**Comment by felixdivo** [comment]
Isn't this fixed in #116?
