### ISSUE TITLE
Add testing under Windows

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#260]
Currently our code is automatically tested under Linux and many different Python versions, and under OSX under only two Python 3 versions using Travis CI. (see `python-can/.travis.yml`) 

But no automatic testing under Windows is performed. Should we integrate it into the testing of python-can? Unfortunately Travis CI can't do that, but maybe someone else knows a similar service for Windows.

**Comment by christiansandberg** [comment]
Unfortunately the unit tests we run have very little coverage of the whole project, so testing it on Windows as well won't help much.

What we really need is a physical setup with all the interfaces we support so that we could test them all against each other. Maybe we could ask the different vendors to give us free samples... :)

**Comment by felixdivo** [comment]
Hm yes, maybe you are right. But then we would still need someone running a CI server, something like [buildbot](https://docs.buildbot.net/current/tutorial/firstrun.html) maybe.

**Comment by hardbyte** [comment]
Let's keep this issue just to basic testing support on windows :-) I've created issue https://github.com/hardbyte/python-can/issues/261 for the test rig.

https://www.appveyor.com/ is the closest I've heard of to travis but for windows

**Comment by felixdivo** [comment]
Yeah, that looks nice. I've seen it being used in some other Python projects as well. Could you set it up?

**Comment by hardbyte** [comment]
Happy to make the project now - do you wan to take on creating a branch with a  `.appveyer.yml` config?

https://ci.appveyor.com/project/hardbyte/python-can

**Comment by felixdivo** [comment]
Yeah, I can have a look at it.
