### ISSUE TITLE
old CAN.py

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#267]
Maybe we should print a deprecation warning when importing CAN.py, and say when (or at least that) it will get removed. 

At the top you can find that info: `This API is left intact for version 2.0 to aide with migration.`. So I guess, that at one point it will get removed, right?

**Comment by hardbyte** [comment]
Sounds good. Maybe lets add the warning now for release 2.2. We could upgrade the warning to be a bit more severe for 2.3 then remove in 2.4

**Comment by felixdivo** [comment]
Ok, I'll add the warning.
