### ISSUE TITLE
Building an executable with Pyinstaller 

### ISSUE THREAD

**Issue by ChrisAlphabet** [hardbyte/python-can#287]
Hi all,

I am trying to build an executable for a Python project that uses the Kvaser interface.

Running `pyinstaller canbus_exerciser.py` works fine and creates the executable.
But when I run the executable from a command prompt I get:

```python
ImportError: No module named 'can.interfaces.kvaser'
```

which seems to suggest that the executable can't find the device driver for the Kvaser.

Using `python canbus_exerciser.py` works perfectly so I know that the driver has been installed properly.

A quick look at the pyinstaller docs shows that you can pass in additional binary and non-binary files.

There are a bunch of files in `C:\Program Files\Kvaser\Drivers` but I am not sure which ones need to be used with pyinstaller to make the Kvaser device driver work properly.

Has anyone tried to do anything similar and know which files to select?

Thanks!

**Comment by christiansandberg** [comment]
The problem is that the interface modules are not imported using the `import` statements which is why PyInstaller doesn't find them. You will need to tell PyInstaller explicitly that can.interfaces.kvaser should be included too.

**Comment by ChrisAlphabet** [comment]
I tried adding 'can.interfaces.kvaser' to the hidden imports part of the `.spec` file but I get the error:  

```
Import Error: Cannont import module can.interfaces.kvaser for CAN 
interface 'kvaser' : 'LibraryLoader' object is not callable 
```

Is that the right place to specify an import?

**Comment by ChrisAlphabet** [comment]
That is the right place to add it! :smile: 

I did a clean build using `pyinstaller --clean canbus_exerciser.spec` and everything is working.

Thanks for your help! :+1:

**Comment by gauravagnihotri** [comment]
Man, i spent hours trying to figure this out. Thanks a lot for the solution!

**Comment by pradeeprajalingam** [comment]
Can you please let me know how to add 'can.interfaces.kvaser' to the hidden imports part of the .spec file?

**Comment by JRYman92** [comment]
Can you please let me know how deal it

**Comment by EnzoBurille** [comment]
> Can you please let me know how deal it

pyinstaller --hidden-import=can.interfaces.kvaser your_file.py
