### ISSUE TITLE
Can not send msg with kvaser

### ISSUE THREAD

**Issue by qxc2016** [hardbyte/python-can#289]
I have install the kvaser's canlib file,and when i connect the kvaser's can memorator,run the test_kvaser file,it prompt:Ran 8 times in 0.1S,but the can memorator did not sent out any msg,why?

**Comment by christiansandberg** [comment]
That file is just a unit test and doesn’t interact with the actual driver. Write your own script or start from one of the examples.

**Comment by qxc2016** [comment]
thank you!
