### ISSUE TITLE
Is this support for Vector tool

### ISSUE THREAD

**Issue by mguo8** [hardbyte/python-can#295]
Hi,

I am trying to send out can message with python can using Canalyzer. It shows up it has already sent out but my device did not receive anything.
I configured can.ini file for Canalyzer and i am able to use can.logger to monitor can bus. But I am not able to send out any message.

**Comment by qwertasyx** [comment]
hi,

looking for this? http://python-can.readthedocs.io/en/2.1.0/interfaces/vector.html

**Comment by christiansandberg** [comment]
Please re-open if you can provide some more information.
