### ISSUE TITLE
Configuration file doesn't register in Windows

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#30]
Originally reported by: **Colin Heinzmann (Bitbucket: [DepthDeluxe](https://bitbucket.org/DepthDeluxe), GitHub: [DepthDeluxe](https://github.com/DepthDeluxe))**

---

I am trying to use the PCAN interface on Windows 7 with python-can and have followed the configuration instructions (i.e. https://bitbucket.org/hardbyte/python-can).  When I try to "import can", I get the following error message even when I have explicitly stated to use the pcan interface in the configuration file.

WARNING:root:Kvaser canlib is unavailable.
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Function was not found in library
WARNING:root:Kvaser canlib is unavailable.
ERROR:can.serial:You won't be able to use the serial can backend without the serial module installed!

My can.ini/can.conf file contains:

[default]
interface = pcan
channel = 1

The Kvaser canlib missing error is also strange because while I was trying to fix the issue, I installed the Kvaser canlib SDK.

My Python version is 2.7.10 (32-bit) and I'm running Windows 7.

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/30

**Comment by felixdivo** [comment]
Is this still a problem? I currently do not have a Windows machine connected to a CAN controller.
