### ISSUE TITLE
Release the interface after it's used?

### ISSUE THREAD

**Issue by wangdino** [hardbyte/python-can#301]
Hi, first of all thanks for the lib!

I wonder if there is a way to release the CAN interface if I finished running my program. When I try to run the same code multiple times I'll end up having multiple instances of interface being used by the same application. Taking a Vector virtual CAN as an example:
![image](https://user-images.githubusercontent.com/17481387/39340929-dad4e3c2-499e-11e8-9411-0d3ec8d7f56d.png)

Thanks for any insights!

**Comment by christiansandberg** [comment]
Do you use the .shutdown() method?

**Comment by felixdivo** [comment]
As far as I know, `bus.shutdown()` closes the connection that is tied to that instance of the bus class. If you have multiple connections, you must've had multiple instances. You need to call `shutdown()` on each of them.

**Comment by wangdino** [comment]
Thanks I think for me it's probably easier to keep track if I have a `bus.shutdown()` for each instance in the code so they all eventually get released.

Issue closed.
