### ISSUE TITLE
Messages sent to both Vector virtual CAN channels when specified to be sent to only one channel

### ISSUE THREAD

**Issue by wangdino** [hardbyte/python-can#302]
Hi, I'm testing on Windows platform using Vector's virtual CAN bus. Here's my hardware config:

![image](https://user-images.githubusercontent.com/17481387/39379192-89d5fbd4-4a28-11e8-8d34-7dd184cddb99.png)

I'm using the following code to try to send just one message to each channel:

```python
import can
import time

bus1 = can.interface.Bus(bustype='vector', channel=0, bitrate=500000, app_name='python-can')
bus2 = can.interface.Bus(bustype='vector', channel=1, bitrate=500000, app_name='python-can')

msg1 = can.Message(arbitration_id = 0xa1,
                   data = [1, 2, 3, 4, 5, 6, 7, 8],
                   extended_id = False)
msg2 = can.Message(arbitration_id = 0xa3,
                   data = [8, 7, 6, 5, 4, 3, 2, 1],
                   extended_id = False)
bus1.send(msg1)
time.sleep(1.0)
bus2.send(msg2)

bus1.shutdown()
bus2.shutdown()
```

I use BUSMASTER to read messages on the virtual CAN buses. Here it looks like each time the same message was always sent on both channels:

![image](https://user-images.githubusercontent.com/17481387/39379353-f273f1dc-4a28-11e8-8d27-b2f735fdf01f.png)

I was expecting msg1 on bus1 and msg2 on bus2. Did I miss something here?

**Comment by christiansandberg** [comment]
Try the `develop` branch. I fixed this in #258.

**Comment by christiansandberg** [comment]
This seems to be by design by Vector or BUSMASTER. See [here](https://github.com/rbei-etas/busmaster/issues/690).

**Comment by wangdino** [comment]
Thanks for pointing to the BUSMASTER issue. You're right! By default the Vector CAN driver connects the two virtual CAN buses. If I change the connection to "NO" the messages are sent only to the correct bus.

![image](https://user-images.githubusercontent.com/17481387/45508321-86bcd380-b762-11e8-8960-7f878ff2ab6e.png)

![image](https://user-images.githubusercontent.com/17481387/45508341-920fff00-b762-11e8-8693-5587751960b1.png)

I neglected there's the option to change the virtual CAN channels. Mea culpa!

**Comment by vaishnavi-p** [comment]
Is it possible to transmit/receive messages within two applications using Virtual Can and Vector XL library?
