### ISSUE TITLE
Provide an example in the README.rst

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#339]
We should probably give a *small* example on how to use the library in the `README.rst`. It would be displayed on the GitHub starting page of the repository and would likely tell users whether this is what they are looking for.

**Comment by cowo78** [comment]
Strongly agree

**Comment by christiansandberg** [comment]
Perhaps not related to this but another question you want answered quickly is which devices are supported.

**Comment by felixdivo** [comment]
@christiansandberg Is there such a list somewhere that we could link to, or do we need to create it first? Because then I'm not the right person to do that since I mainly work with SocketCAN.

**Comment by hardbyte** [comment]
In the docs... https://python-can.readthedocs.io/en/develop/interfaces.html
