### ISSUE TITLE
Issues connecting to Lawicel with Python

### ISSUE THREAD

**Issue by virenmahajan5** [hardbyte/python-can#366]
Hello All,

I am new to using Python with CAN. What i am trying to achieve is sending a message to a target using the Lawicel hardware.

So please guide me on which CAN interface and bus type must be selected.
An example of the connection would be of great help. Thanks in anticipation

**Comment by christiansandberg** [comment]
Try slcan.

https://python-can.readthedocs.io/en/stable/interfaces/slcan.html
