### ISSUE TITLE
Fix Travis CI builds before OSX 8.3 builds become unsupported

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#385]
See travis-ci/travis-ci#9929 and #380.

**Comment by christiansandberg** [comment]
By fixing do you mean removing? There is probably not much to test on Mac that we can't test on Linux. There is not much I can see that we test that is OS dependent.

**Comment by felixdivo** [comment]
> By fixing do you mean removing?

I thought you can install Python in an virtualenv, but I don't have much experience with that. 

> There is probably not much to test on Mac that we can't test on Linux. 

Yeah, probably right. I was easy for now, so it didn't hurt. We could leave it in there until it breaks, and not invest much time into fixing it.
