### ISSUE TITLE
Problem with new location of scripts

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#392]
> Calling: `python -m can.logger` does not seem to work on the develop branch? I have to use the full path: `python -m can.scripts.logger`. 

Reported by @Lauszus [over here](https://github.com/hardbyte/python-can/pull/370#issuecomment-412303400).

**Comment by felixdivo** [comment]
Also need to consider newly added script from #390.

**Comment by felixdivo** [comment]
(Note for myself: TODO: Update `setup.cfg`.)

**Comment by felixdivo** [comment]
I added some regression tests to branch `python-can/fix_scripts`, and will merge it together with the fix of this issue once we decided what to do.

**Comment by christiansandberg** [comment]
I would prioritize user interface and external API over internal structure, but that's just my opinion. I didn't see the way it was before as a big issue.

**Comment by felixdivo** [comment]
Well, I guess you're right. Im my opinion it was confusing for people new to the codebase, but that's just how it is now. I'll revert the relevant changes. -.-
