### ISSUE TITLE
Specifying handshake for serial port based CAN interfaces

### ISSUE THREAD

**Issue by yegorich** [hardbyte/python-can#398]
So far we can only pass baudrate to the interface constructor like `/dev/ttyUSB0@115200`. Many adapters run at high baudrates so enabling hardware handshake is a must. There are two issues:

1. what handshake options do we need to support: RTS/CTS, Xon/Xoff etc.
2. depending on the answer to the first issue the syntax must be defined. For example: `/dev/ttyUSB0@115200:rtscts` or something like this.

**Comment by felixdivo** [comment]
Slightly off-topic: Currently #290 is blocking some of the effort on the serial interface I think.

**Comment by yegorich** [comment]
AFAIK #290 will have to be reworked anyway. And introducing handshake support won't interfere with it. I.e. the changes will just have to be ported. At least we can define how and what should be implemented regarding the handshake.

**Comment by felixdivo** [comment]
Yup, that right. I am not familiar with the serial interface though.

**Comment by felixdivo** [comment]
Ah, I see you already commented on the topic of this issue [over there](https://github.com/hardbyte/python-can/pull/290#issuecomment-379528855).

**Comment by yegorich** [comment]
Yes, and as #290 got stuck I've decided at least to implement the features needed for our products.

I'll prepare a PR implementing `/dev/ttyUSB0@115200:rtscts`.
