### ISSUE TITLE
Change extended_id to is_extended_id in Message parameters

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#424]
A trivial change to the `Message` initializer see discussion in https://github.com/hardbyte/python-can/pull/413

As it effects the external api it will need a deprecation period. I suggest we implement an optional new parameter `is_extended_id` now (in v3.0) which if present is used instead of `extended_id`.

In v3.1 we add a warning message, and 4.0 remove the old parameter.

**Comment by felixdivo** [comment]
Next thing would be to add a warning when `extended_id` is used, for version `3.1`.

**Comment by felixdivo** [comment]
Done in #497. The followup issue is #502.
