### ISSUE TITLE
Cannot receive messages with Kvaser

### ISSUE THREAD

**Issue by bessman** [hardbyte/python-can#433]
Python 3.6.5, python-can 2.2.1, Kvaser CANlib 5.24, Windows 10.
bus.recv() does not return anything, even though I can see that messages are present on the bus using Kvaser CanKing. I can however send messages with bus.send() (the message shows up in CanKing).

**Comment by christiansandberg** [comment]
Are the messages being sent from the same computer?

**Comment by hardbyte** [comment]
Can you confirm this is an issue with the upcoming release please?

```
pip install python-can==3.0.0a1
```

**Comment by tthatche** [comment]
The hardware is at work. I’ll try on Monday.

Sent from my iPhone

On Sep 28, 2018, at 6:52 PM, Brian Thorne <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you confirm this is an issue with the upcoming release please?

pip install python-can==3.0.0a1

**Comment by bessman** [comment]
Hmm. I can no longer reproduce this issue. I'll let you know if it reappears and I can figure out what exactly is the cause. I'll close this for now.
