### ISSUE TITLE
Add support for ISO TP

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#45]
Originally reported by: **toonst (Bitbucket: [toonst](https://bitbucket.org/toonst), GitHub: [toonst](https://github.com/toonst))**

---

Support for [ISO TP](https://en.wikipedia.org/wiki/ISO_15765-2) is not yet built in SocketCAN by default, but there exists an implementation:
https://github.com/hartkopp/can-isotp

It would be great to be able to use this from python-can.

Since I really could use this functionality, I might take stab at implementing it. Could someone list the changes that are needed to make it work? I'm not familiar with the python-can code, so I don't know if this is feasible. 

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/45

**Comment by christiansandberg** [comment]
As I understand it ISO TP is a small protocol layer that abstracts away the limitations of regular CAN like the 8 byte limit. Other real protocols like UDS uses this. On one hand it could make sense to have this here since it is closer to the CAN layer and not an actual protocol. On the other hand it makes sense to keep python-can clean from everything but the lowest level.

**Comment by felixdivo** [comment]
> On the other hand it makes sense to keep python-can clean from everything but the lowest level.

I agree with this and would recommend implementing that in a new repository if someone decides to do this. We can still link from one to the other and `python-iso-tp` can depend on `python-can`.

We could also consider making something existing compatible with python-can, like https://github.com/pylessard/python-can-isotp.

I would suppose we close this ancient issue after we decided on that.

**Comment by inorick** [comment]
`python-can-isotp` is only a wrapper around the Linux kernel‘s native ISO-TP implementation and not an implementation of the protocol itself. The only one in pure Python that I could find is part of `pyvit` and it only implements a subset. So I think unless there is another dedicated ISO-TP project, this would be a good place for a platform independent implementation of ISO-TP.

**Comment by felixdivo** [comment]
Okay, I'm fine with that as long as it resides in it's own package (like `isotp`), and not in `can.*`.

**Comment by felixdivo** [comment]
Also see [socket.CAN_ISOTP](https://docs.python.org/3/library/socket.html#socket.CAN_ISOTP).

**Comment by christiansandberg** [comment]
That would also just work for socketcan. I think we can close this issue since it is easy and cleaner to keep protocols in separate packages.

**Comment by felixdivo** [comment]
Well, as long as no one has the time to tackle this, I doesn't matter anyway.

**Comment by hardbyte** [comment]
This also lines up with [what we did for the J1939 protocol](https://bitbucket.org/hardbyte/python-can/issues/65/j1939-what-to-do) which was to put it in an external library - https://github.com/milhead2/python-j1939

Agree we should link to these higher level libraries from our docs.

**Comment by polybassa** [comment]
Hi, I we created an ISOTPSoftSocket inside the Scapy project. This ISOTPSoftSocket can use any python-can interface object for the lower layer. Unfortunately, we didn't wrote the docs, yet. Usage examples can be found in the unit-test-file. Just search for ISOTPSoftSocket https://github.com/secdev/scapy/blob/26eac7e85fd89af2e71c85dcf7fea8416103fbe9/scapy/contrib/isotp.uts#L967. 
Maybe this is useful for someone.

**Comment by christiansandberg** [comment]
@pylessard is implementing support for python-can in udsoncan now and I have implemented an asyncio ISO-TP library.

**Comment by pylessard** [comment]
Actually, the IsoTP layer is implemented in [can-isotp](https://github.com/pylessard/python-can-isotp) module which I use in udsoncan. The IsoTP implementation is functional but not released yet.

**Comment by pylessard** [comment]
Sorry for the confusion. There is a python implementation, I just haven't updated the documentation yet, give me a week or 2.. Vector works, I tested it with some hardware. I'll an example on how to use it with Vector soon. In the mean time, you can have a look at the isotp.stack module, you should find what you are looking for.
