### ISSUE TITLE
Make "typing" dependency conditional for python_version<"3.5"

### ISSUE THREAD

**Issue by maxchill** [hardbyte/python-can#451]
I've noticed in the newest 3.0 python-can release, there is a new "typing" dependency in install_requires.

To quote the pip page https://pypi.org/project/typing/
> This is a backport of the standard library typing module to Python versions older than 3.5. (See note below for newer versions.)

So I'm proposing the following up be made, to eliminate clients from having to install an unnecessary dependency if running a modern python version.

```
install_requires=[
    'typing;python_version<"3.5"',
```

**Comment by felixdivo** [comment]
Fixed in #452.
