### ISSUE TITLE
PCAN hardware is sometimes not released (on Windows)

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#48]
Originally reported by: **SadE (Bitbucket: [SadE](https://bitbucket.org/SadE), GitHub: [SadE](https://github.com/SadE))**

---

After successive connections, debugging a liitle test app , it seems the pcan dongle is not always released correctly. 
My python app is closed , and when I'm trying to connect using PCAN Explorer I get this error :
Error in Connection Connection1: Hardware is already in use (Code 0400h)
Even by unplugging anf plugging it again, I get the same message.

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/48

**Comment by felixdivo** [comment]
Can someone test if this is still a problem? I do not know the PCAN interface but I can imagine that it is fixed by now.

**Comment by mgiaco** [comment]
Hi, I tried that with my app some minutes ago but I rechecked with PCANVIEW.  I found no error so maybe this is fixed.

**Comment by felixdivo** [comment]
Great! :+1: Then let's close it, and if anyone has problems again, he/she can open it again.

**Comment by lalitheranti** [comment]
I have the same issue of the device already in use. what should I do?

**Comment by cathalDGWorld** [comment]
Yeah i also have the same issue. when i close my program. It not getting released and when I open PCAN view. it show that the device is being used by another program. The only way i found of fixing this is to restart my laptop again. If i close the application and do a release when i am closing the application. i dont have a problem. But when i have an error and force the program to close. it doesn't release it.
