### ISSUE TITLE
**config vs **kwargs

### ISSUE THREAD

**Issue by PeteAndersen** [hardbyte/python-can#492]
When naming the keyword arguments variable, the standard convention in python is to call it `kwargs`. Naming it `config` tends to throw off some introspection tools. Would you consider a PR to rename them to `kwargs` across the board?

Example: https://github.com/hardbyte/python-can/blob/develop/can/bus.py#L36

**Comment by hardbyte** [comment]
Sure, I'd merge that

**Comment by PeteAndersen** [comment]
Great! I'll have a PR ready in a couple days after some travel

**Comment by felixdivo** [comment]
@PeteAndersen Any updates on this ❓
