### ISSUE TITLE
How to resolve module not found error in python ?

### ISSUE THREAD

**Issue by Prriyamvradha** [hardbyte/python-can#498]
I tried to send a can message virtually and capture it in Wireshark but I'm not able to import can in python and i get the following error

hp@HP-Notebook:~$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> import can
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'can'
>>>

**Comment by felixdivo** [comment]
How did you install the package? Using `pip install python-can --user` should normally do the job. Alternatively, clone the repo locally and execute this inside the downloaded directory: `python setup.py install --user`. Maybe, you installed it on pip2/python2 but wanted to install it on pip3/python3 or vice versa?

This problem does not seem to come from this library.
