### ISSUE TITLE
Support slcan ASCII protocol

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#5]
Originally reported by: **Brian Thorne (Bitbucket: [hardbyte](https://bitbucket.org/hardbyte), GitHub: [hardbyte](https://github.com/hardbyte))**

---

See https://gitorious.org/linux-can/can-utils

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/5

**Comment by grodansparadis** [comment]
Supported by socketcan on Linux and USB2CAN interface (CANAL) with CAN232 CANAL driver on windows (http://www.vscp.org/docs/vscpd/doku.php?id=level1_driver_can232).

**Comment by felixdivo** [comment]
Isn't this fixed in #195?

**Comment by hardbyte** [comment]
💯
