### ISSUE TITLE
How to send and receive CAN message using CANtact toolkit ?

### ISSUE THREAD

**Issue by Prriyamvradha** [hardbyte/python-can#503]
I am new to this topic. I want to know how to connect the CANtact toolkit to my laptop and program it to send and receive CAN message. I used USB-B cable to connect it to my laptop.

I opened a terminal and installed `pip3 install CANard` and `pip3 install pyserial` then I typed `python3` to go into python shell and typed the following code:

```python
              from canard.hw import socketcan
              dev=socketcan.SocketCanDev('can0')
              dev.start()
              while True:
                     f=dev.recv()
                     dev.send(f)
```
I didnt get any error nor did i get any output.Where should i check the output ?

[asia-15-Evenchick-Hopping-On-The-Can-Bus-wp.pdf](https://github.com/hardbyte/python-can/files/2858969/asia-15-Evenchick-Hopping-On-The-Can-Bus-wp.pdf)

**Comment by hardbyte** [comment]
You're using an unrelated `canard` library and not this one `python-can`.
