### ISSUE TITLE
add MF4 io writer

### ISSUE THREAD

**Issue by danielhrisca** [hardbyte/python-can#506]
I would like to implement support for exporting to asam MF4 files (https://www.asam.net/standards/detail/mdf/). That would require my library as dependency ([asammdf](https://github.com/danielhrisca/asammdf)). Is this acceptable?

**Comment by christiansandberg** [comment]
Wouldn’t that also require decoding raw messages to actual signal values?

**Comment by danielhrisca** [comment]
That is not mandatory. 

The raw messages can be dumped and there are two recording modes that I would like to implement

1. unsorted mode : all messages are placed in the same channel group 
2. sorted mode: each message ID in dedicated channel groups

A database can be embedded in the MF4 file (dbc or arxml) and it can be used to later extract signal values. It is also possible to have anonymous logging if no database is attached.

**Comment by christiansandberg** [comment]
I think it sounds like a good idea. But maybe add the library as an [extra](https://setuptools.readthedocs.io/en/latest/setuptools.html#id16) dependency.

**Comment by felixdivo** [comment]
This sounds like a good idea! As not too many will be using this (i guess) we should add this as an extra. It would probably be a good time to add the allowed extras to a section called *Installation* or something like that in the Readme.

**Comment by felixdivo** [comment]
@danielhrisca Do you need any help with this? I could also write a small tutorial on how to add new `Reader`s/`Writer`s. Would that help?

**Comment by danielhrisca** [comment]
It would help, thank you. Unfortunately I did not have time to tackle this get.

**Comment by felixdivo** [comment]
I wrote some text on that. See: https://github.com/hardbyte/python-can/pull/548/files#diff-200667e0b2eaf351c0585ba21fb7a144R70. Hope it helps. Please ask if questions remain,

**Comment by danielhrisca** [comment]
I have a question regarding the message timestamp: does it always use the local time?

**Comment by felixdivo** [comment]
I think usually [`time.time()`](https://docs.python.org/3/library/time.html#time.time) is used.

**Comment by danielhrisca** [comment]
@felixdivo can you have a look at #554 ?

**Comment by felixdivo** [comment]
Sure
