### ISSUE TITLE
Provide list of presently available buses

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#51]
Originally reported by: **Kyle Altendorf (Bitbucket: [altendky](https://bitbucket.org/altendky), GitHub: [altendky](https://github.com/altendky))**

---

I just created a socketcan/PCAN only bus checker.  It tries to create a bus for each interface/channel and checks for exceptions to filter out the unavailable ones.

https://github.com/altendky/st/blob/7c87276d1bb7b58e8d9c060b40d047fed5a5032d/epyq/busselector.py#L19

It's pretty hacky and hardcoded but I thought I would share it in case anyone wanted to expand on it and integrate it into python-can.

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/51

**Comment by cowo78** [comment]
IMHO we can think about extending the BusABC interface with a detect_hardware static or something like that.
It should report configuration dicts and the available channels for each detected piece of hardware.

**Comment by felixdivo** [comment]
The canal interface already implements that automatic discovery, but as a fallback when no channel was given in `kwargs` or `can.rc`. See #245.

**Comment by felixdivo** [comment]
Let's suppose `BusABC` has a detect method, like Giuseppe proposed. I would call it `detect_available_channels` since not all interfaced work with actual hardware. For example `virtual` or `socketcan`'s `vcan0` only work in software. It could look like this (notice that it is not abstract):

```Python
# in BusABC:
@staticmethod
def _detect_available_channels():
    """Docstring."""
    raise NotImplementedError()
```

Then I would define this method and make it accessible directly from the `can` module:

```Python
# in can/interface.py

from __future__ import absolute_import

import sys
import logging

from .interface import BACKENDS

log = logging.getLogger('can.interface')

if sys.version_info.major > 2:
    basestring = str

def detect_available_channels(search_only_in=None):
    """Dostring.

    :param search_only_in: either
        - the name of an interface as a string,
        - an iterable of interface names, or
        - `None` to search in all known interfaces.
    """

    if search_only_in is None:
        # use an iterator over the keys so we do not have to copy it
        search_only_in = BACKENDS.iterkeys()
    elif isinstance(search_only_in, basestring):
        search_only_in = (search_only_in,)
    # else it is an iterable of strings

    result = []
    for interface in search_only_in:

        # use the same code as in can/interface.py :: Bus.__new__()
        bus_class = get_class_of_this(interface)

        # get available channles
        try:
            result += bus_class._detect_available_channels()
        except NotImplementedError:
            log.debug('interface "%s" does not support detection of available channels', interface)

    return result
```

**Comment by felixdivo** [comment]
See branch `feature-detect-channels`.
