### ISSUE TITLE
problem with use of data dictionaries (keys)

### ISSUE THREAD

**Issue by totocaca123** [hardbyte/python-can#512]
In the following file:
can/util.py some test of keys are not done properly:
```
        for key in cfg:
            if key not in config:
                config[key] = cfg[key]
```

the first line should be replaced with 
```
        for key in cfg.keys():
            if key not in config.keys():
                config[key] = cfg[key]
```

This problem is seen many times in this file.
Need to check all files if same issue is present

**Comment by felixdivo** [comment]
No, please do not do this in Python! Use `if key in cfg`. See the docs on [Python 2](https://docs.python.org/2/library/stdtypes.html#dictionary-view-objects)/[Python 3](https://docs.python.org/3/library/stdtypes.html#dictionary-view-objects) or [this StackOverflow discussion](https://stackoverflow.com/a/1602964/3753684).
