### ISSUE TITLE
Shouldn't BusState be an enum?

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#519]
Currently, `BusState` is defined as

```python
BusState = namedtuple('BusState', 'ACTIVE, PASSIVE, ERROR')
```

But shouldn't it be an enum?

**Comment by felixdivo** [comment]
We could use https://pypi.org/project/enum34/ to make it work with Python < 3.4 as well.

**Comment by hardbyte** [comment]
Yeah let's do it, I'd like to use `Enum` types in a few places if we added the dependency.
