### ISSUE TITLE
Use enum library

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#555]
I'd like to use Enum types in a few places now that we've added the `aenum` dependency in #533 

For example in the `socketcan` interface there is a [file defining constants](https://github.com/hardbyte/python-can/blob/develop/can/interfaces/socketcan/constants.py) - many of which could be enums. Similar files exist for most interfaces e.g., [kvaser constants](https://github.com/hardbyte/python-can/blob/develop/can/interfaces/kvaser/constants.py)

As a good first contribution choose one interface (that you can test locally), make the changes to use the aenum library and create a pull request.

**Comment by felixdivo** [comment]
As this is labeled as a `good first contribution`, we should probably specify where exactly the library can be improved using enums.

**Comment by felixdivo** [comment]
I think this is more or less done in the main API and not very helpful to track in an issue. The code in the interfaces is very ... heterogeneous anyways, so I don't think it's too useful to have one big issue for it.

**Comment by hardbyte** [comment]
Yeah that's fair
