### ISSUE TITLE
PCAN interface documentation

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#56]
Originally reported by: **Brian Thorne (Bitbucket: [hardbyte](https://bitbucket.org/hardbyte), GitHub: [hardbyte](https://github.com/hardbyte))**

---

Add a page to the sphinx docs.

https://python-can.readthedocs.org/en/latest/interfaces.html

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/56

**Comment by felixdivo** [comment]
Isn't that already present over [here](http://python-can.readthedocs.io/en/latest/interfaces/pcan.html)?

**Comment by hardbyte** [comment]
It really doesn't contain enough information though. 
I'd like to see what peak system's devices are supported, a note if drivers are required, what operating system the interface works for (using alternatives like socketcan on linux), and perhaps a few sentances on the design of the interface.

**Comment by felixdivo** [comment]
Can someone with some knowledge on that interface tackle this in the next weeks?

**Comment by Delgan** [comment]
@felixdivo I would love to help the project, but to be honest I do not really know much about PCAN, I just copy-pasted the Peak-System's driver.

**Comment by felixdivo** [comment]
Hm okay. Someone else?
