### ISSUE TITLE
Potentially unused SocketCAN constants?

### ISSUE THREAD

**Issue by karlding** [hardbyte/python-can#574]
I was looking through the SocketCAN constants defined in `can/interfaces/socketcan/constants.py`, and noticed these constants:

```python
REMOTE_FRAME = True
DATA_FRAME = False
WAKEUP_MSG = True
ERROR_FRAME = True

DRIVER_MODE_SILENT = False
DRIVER_MODE_NORMAL = (not DRIVER_MODE_SILENT)
```

What is the purpose of these? Are these just to be backwards compatible so we aren't breaking some old API? I didn't seem to find any documentation about these or a deprecation warning anywhere..

Otherwise, I didn't see any references in the code where they are used, so can they safely be removed? In my local testing it doesn't seem like removing these breaks anything.

I have prepared a patch to remove these, but I thought I'd check first before jumping the gun :joy:

**Comment by hardbyte** [comment]
I think you're right that these are remnants of ancient times. Happy to remove them
