### ISSUE TITLE
Adding a test file for the BlfReader 

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#581]
This idea came up [here](https://github.com/hardbyte/python-can/pull/568#issuecomment-491623203), to create a BLF test file ourselves, that contains all/most of the features we support.

**Comment by felixdivo** [comment]
@christiansandberg Maybe you have the tools for that.

**Comment by christiansandberg** [comment]
Sorry, I don’t have that anymore. But maybe I could create a script that generates a file using python-can and someone else could verify that it is valid.

**Comment by felixdivo** [comment]
Seems like this was done in #734.
