### ISSUE TITLE
Test logger.py

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#585]
See coverage of 40% at release 3.2 - https://codecov.io/gh/hardbyte/python-can/src/7268f49f4ca349464e29bc680e9e42c66e313455/can/logger.py

Ideally this is >90%

**Comment by felixdivo** [comment]
#1036 Factors our common functionality and introduces slightly better coverage.

**Comment by pkess** [comment]
I think this can be closed as converage is 100% now. If you see more tests do be added here i would like to implement this.

**Comment by felixdivo** [comment]
Hey @pkess I've just now seen the **_great_** PR #1196. Sure, you are right!
