### ISSUE TITLE
Module object has no attribute 'bus'

### ISSUE THREAD

**Issue by Dn1234567** [hardbyte/python-can#603]
Hello,
python-can updated to the latest version.
Python 2.7
Raspberry (rasbian 9 stretch)

"
import can
bus = can.Bus(interface='socketcan',...
"
gives  AttributeError: 'module' object has no attribute 'bus'
What is wrong?
Thanks in advance

**Comment by hardbyte** [comment]
My guess is you could be running your code in a folder which contains a `can.py` which is taking precedence over python-can?

**Comment by felixdivo** [comment]
Or a leftover `can.pyc`/`can.pyo`. That was a problem I myself faced once.

**Comment by Dn1234567** [comment]
Thanks.
renamed file from can.py to can_start.py. 
But new error :-) reffering to the same line: "'module" object is not callable.

Candump on "can0" works well.
sorry :-( for silly questions

**Comment by felixdivo** [comment]
Could you post you entire file for this? It's hard to guess without seeing it. ;)

**Comment by felixdivo** [comment]
Please comment if the issue is not solved by the above suggestions. ;)

**Comment by natek512** [comment]
Hello! Running into the same error as well. 
I've create a virtual environment with the module installed. I tried creating a Bus object via the following

```
import can

bus = can.interface.Bus(bustype='pcan', channel='PCAN_USBBUS1', bitrate=250000)
```

and this is the error I receive:

```
runfile('C:/Documents/Python Scripts/can_api_tutorial.py', wdir='C:Documents/Python Scripts')
Traceback (most recent call last):

  File "C:\Documents\Python Scripts\can_api_tutorial.py", line 17, in <module>
    bus = can.interface.Bus(bustype='pcan', channel='PCAN_USBBUS1', bitrate=250000)

  File "C:\.conda\envs\CANenv\lib\site-packages\can\interface.py", line 127, in __new__
    return cls(channel, *args, **config)

  File "C:\.conda\envs\CANenv\lib\site-packages\can\interfaces\pcan\pcan.py", line 97, in __init__
    self.m_objPCANBasic = PCANBasic()

  File "C:\.conda\envs\CANenv\lib\site-packages\can\interfaces\pcan\basic.py", line 359, in __init__
    self.__m_dllBasic = windll.LoadLibrary("PCANBasic")

  File "C:\.conda\envs\CANenv\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)

  File "C:\.conda\envs\CANenv\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] The specified module could not be found
```
Pretty new to this so sorry if this is a silly question! Thanks!
