### ISSUE TITLE
Syntax error socketcan.py

### ISSUE THREAD

**Issue by sbourkedev** [hardbyte/python-can#609]
Syntax error in print statement
socketcan.py
LINE 680

```
675  def receiver(event):
676  receiver_socket = create_socket()
677  bind_socket(receiver_socket, "vcan0")
678  print("Receiver is waiting for a message...")
679  event.set()
680  print(f"Receiver got: {capture_message(receiver_socket)}")
```

**Comment by karlding** [comment]
Are you using a PyPI release? Looking at the tagged releases for [3.2.1-alpha.1](https://github.com/hardbyte/python-can/blob/3.2.1-alpha.1/can/interfaces/socketcan/socketcan.py#L722-L727), [3.2.1-alpha.2](https://github.com/hardbyte/python-can/blob/3.2.1-alpha.2/can/interfaces/socketcan/socketcan.py#L722-L727) or [3.2.0](https://github.com/hardbyte/python-can/blob/3.2.0/can/interfaces/socketcan/socketcan.py#L722-L727), the code doesn't seem to match up with what you're pointing out.

If you're using a branch based off `develop`, it has changes in preparation for `4.0`, where `python-can` will be dropping support for Python 2, which doesn't support f-Strings.
