### ISSUE TITLE
can logger kcd output file format

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#61]
Originally reported by: **Brian Thorne (Bitbucket: [hardbyte](https://bitbucket.org/hardbyte), GitHub: [hardbyte](https://github.com/hardbyte))**

---

Consider writing out in [kcd](https://github.com/julietkilo/kcd).

> The KCD format was created because most CAN databases are stored in proprietary formats that are not documented and can not be used for free. The open source CAN analysis tool Kayak introduced a new and well documented XML based format: KCD (file suffix .kcd). KCD is the acronym for Kayak CAN definition.

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/61

**Comment by hardbyte** [comment]
I had an email with Jonas from the BSD licensed [can4python](https://github.com/caran/can4python) project. 

I would merge a PR if someone wants to try basing something off their [KCD implementation](https://github.com/caran/can4python/blob/master/can4python/filehandler_kcd.py). From looking at that file I don't think it is useful to us verbatim.

> Before implementing the library we studied the available alternatives. Our main requirements were to be able to extract the individual signal values from the CAN messages/frames, and to use file based configuration.
>Traditionally DBC files are used for the configuration, but that is a file format owned by Vector. That is why we use the open KCD configuration file format. There are also freely available DBC-to-KCD converters.
I think the KCD file format (proper links are found in the documentation) is really nice, and suggest that also you use it if you plan to implement file based configuration.
>We do not plan any major changes to can4python, however it has a very permissive license so feel free to use any parts of it. Please keep the copyright statements in the files.

As detailed above and in their license we would have to keep the copyright in place and add an acknowledgement if we directly use any of their code.

**Comment by christiansandberg** [comment]
KCD is a signal database format, not a CAN log format. I don't know how it would be applicable for python-can.
