### ISSUE TITLE
Experimenting with DoS attack

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#62]
Originally reported by: **Abdul Malik (Bitbucket: [abdulmalik_hmd](https://bitbucket.org/abdulmalik_hmd), GitHub: Unknown)**

---

Hello,
I'm trying to test a Denial of Service (DoS) attack such that legitimate messages cannot be received because the network is flooded with high priority IDs. 

My experiment consists of two programs, each of which simulates an ECU:

ECU1: sends periodic messages with the ID 0x009.
It also has 0x009 as a filter in order to receive it  to confirm other ECUs also received it.

ECU2: Malicious program that sends a very large number of 0x008 IDs whenever a 0x009 ID is detected in the can bus.

My problem is this: ECU1 always receives 0x009 ID, even though the network is flooded with 0x008 ID that intended to prevent such successful transmission!

Any help would be greatly appreciated.

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/62

**Comment by felixdivo** [comment]
Is this still relevant? I guess it is a problem with SocketCAN rather than with this library, since it doesn't even use `python-can`.

**Comment by hardbyte** [comment]
Yeah good point... closing.
