### ISSUE TITLE
Time usage Message.__iter__

### ISSUE THREAD

**Issue by kvwoerden** [hardbyte/python-can#630]
I am using python-can@develop to read all CAN messages of a rather large (200 MB) blf file. Since I need to optimize the runtime, I profiled this using `cProfile`. It turns out that 36% of the total runtime is spent in `Message.__iter__` and its subfunction calls, of which 20% is spent in `Message.__iter__` itself. I was wondering whether I could optimize this, and where all this time in `Message.__iter__` might be spend, because this is not clear to me from the code.

**Comment by christiansandberg** [comment]
can.Message doesn’t have that method right? 🤔

**Comment by felixdivo** [comment]
Closing this since we cannot follow your report of your problem.
