### ISSUE TITLE
stop_all_periodic_tasks skipping every other task

### ISSUE THREAD

**Issue by mikado98765** [hardbyte/python-can#634]
It seems like the logic for stop_all_periodic_tasks in bus.py removes each task from self._periodic_tasks as it goes through the loop. But if it removes and increments each time through it would skip every other task (if the remove_task flag is true).

**Comment by felixdivo** [comment]
You are right, this is not OK, since modifying a list while iterating over it results in unspecified order.

**Comment by ovianao** [comment]
Hi all, is there a plan to include this fix in a 3.3.x version?

**Comment by karlding** [comment]
I've cherry-picked the two changes and put a PR against the `release-3.3.4` branch. Hopefully we can get this in!

**Comment by ovianao** [comment]
Thanks so much, @karlding and @hardbyte!
