### ISSUE TITLE
Flushing buffer should include timeout

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#64]
Originally reported by: **Brian Thorne (Bitbucket: [hardbyte](https://bitbucket.org/hardbyte), GitHub: [hardbyte](https://github.com/hardbyte))**

---

The `Bus.flush_tx_buffer` method doesn't take a timeout but it probably should.

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/64

**Comment by cowo78** [comment]
If the flush() operation is meant to wait for all the queued data to be transmitted, you're right. If OTOH flush() is really a wipe, then the timeout is of course not needed (see discussion on #127).

**Comment by hardbyte** [comment]
Sounds good @cowo78. Looks like we need to update the documentation to make it clearer as well.
