### ISSUE TITLE
Read The Docs is missing some versions

### ISSUE THREAD

**Issue by felixdivo** [hardbyte/python-can#666]
@karlding noted this in #665

> It seems like the ReadTheDocs site is missing the docs for versions following 3.1.1.. 🤔 Should 3.2.0, 3.2.1, 3.3.0 and 3.3.1 be available there as well?

What has caused this?

Here might be some more info (see other tabs as well): https://readthedocs.org/projects/python-can/versions/

**Comment by hardbyte** [comment]
Thanks, I've fixed the webhook and now we have docs 3.3.1 and 3.2.1

**Comment by hardbyte** [comment]
Fastest issue resolution! ⏲
