### ISSUE TITLE
How to use low-speed on an Ixxat Automotive adapter. 

### ISSUE THREAD

**Issue by tobiasht** [hardbyte/python-can#700]
I am using a Ixxat CAN-TO-USB Automotive adapter. This adapter supports both hi- and low-speed ports for channel 0, but how can I tell python-can to use low-speed instead of hi-speed?
Any help is much appreciated!

**Comment by felixdivo** [comment]
Doesn't this just correspond to the bitrate? [That one can be set.](https://python-can.readthedocs.io/en/develop/interfaces/ixxat.html) If you meant something else, please feel free to comment again or open a new issue.
