### ISSUE TITLE
Ixxat driver ignores UniqueHardwareID and [r|t]xFifoSize from configuration

### ISSUE THREAD

**Issue by cranium-xx** [hardbyte/python-can#702]
The Ixxat canlib ignores UniqueHardwareID, rxFifoSize and txFifoxSize from the configuration file. 
The reason is that the driver requests the configuration with CamelCase but it has to use lower case.

**Comment by felixdivo** [comment]
Can you provide a pull request solving the problem?

**Comment by cranium-xx** [comment]
Of course, I can. I just need the rights to create an branch for it. How do I get them?

**Comment by felixdivo** [comment]
Cool! The usual workflow is to fork (upper right corner of the page) and then apply the changes to the forked develop branch of `cranium-xx/python-can`. Then in your fork, you should see a button for merging it back into `hardbyte/python-can`.

**Comment by felixdivo** [comment]
@cranium-xx This is very old. Do you plan on providing a patch?

**Comment by cranium-xx** [comment]
Hi,
I just provided a patch.

**Comment by felixdivo** [comment]
Great I'll have a look over there.
