### ISSUE TITLE
XL_ERR_NOT_IMPLEMENTED when calling xlGetSyncTime on VN8900

### ISSUE THREAD

**Issue by danielhrisca** [hardbyte/python-can#732]
Hello,

I'm trying to use a VN8900 device but get this error during the __init__ https://github.com/hardbyte/python-can/blob/release-3.3.2/can/interfaces/vector/canlib.py#L209 (using version 3.3.2). 

I have multiple VN devices connected (including a VN7600), but I don't use the serial number, I just assign a custom applciation name in the vector hardware configuration utility.

**Comment by christiansandberg** [comment]
Could be that some hardware does not support reading the current timestamp. In that case we could just fall back to relative timestamps.

**Comment by danielhrisca** [comment]
It seems that there is a dedicated functionf or the VN8900 family (see 3.2.22 xlGetChannelTime
in https://assets.vector.com/cms/content/products/XL_Driver_Library/Docs/XL_Driver_Library_Manual_EN.pdf )

I will try to see if this fixes the problem

**Comment by danielhrisca** [comment]
@christiansandberg 

Using the fix from the PR I was able to access the bus and read messages.
