### ISSUE TITLE
Issue in recognizing the pcan with python code

### ISSUE THREAD

**Issue by queen97king2019** [hardbyte/python-can#735]
from __future__ import print_function
import serial
import can
print("first step")

def send_one():
    print("Second Step")

    bus = can.interface.Bus(bustype='pcan', channel='PCAN_USBBUS1', bitrate=250000)
  
    print("Third step")

    msg = can.Frame(arbitration_id=0x123, is_extended_id=False,
                      data=[0x11, 0x22, 0x33])
    print("Fourth step")

     try:
        #bus1.send_periodic(msg,10)
         bus.send(msg)
         print("Message sent on {}".format(bus.PCAN-USBBUS1_info))
    except can.CanError:
         print("Message NOT sent")
send_one()

WE are able to enter the function. But in the next step," **bus = can.interface.Bus(bustype='pcan', channel='PCAN_USBBUS1', bitrate=250000)"**  the bustype and channel is not being recognised. How do we proceed further?

**Comment by tamenol** [comment]
Can you try this:

`bus = can.Bus(channel='PCAN_USBBUS1', bustype='pcan', bitrate=250000)`

**Comment by queen-king** [comment]
It's giving attribute error.
It says "module can has no attribute bus".

**Comment by tamenol** [comment]
It's `Bus` with a capital letter. Maybe that's it? But I get a different error when I try that. What version are you running?

```
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import can
>>> bus = can.Bus(channel="PCAN_USBBUS1", bustype="pcan")
>>> bus
<can.interfaces.pcan.pcan.PcanBus object at 0x000002367FE2C358>
>>> print(bus)
PCAN_USBBUS1
```

```
~ $ pip show python-can
Name: python-can
Version: 3.2.0
```

**Comment by queen-king** [comment]
I am using 3.8 version. i have used capital 'B' in the code. It still says attribute error.

**Comment by queen-king** [comment]
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import can
>>> bus1 = can.Bus(channel="PCAN_USBBUS1", bustype="pcan")


This is the error we are getting for the same code.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'can' has no attribute 'Bus'
>>>

**Comment by tamenol** [comment]
You do that in a clean (new) python interpreter shell? No other files called `can.py` in that directory? What is the output of `pip show python-can`?

It's weird. I can even do `b = can.interface.Bus(bustype="pcan")` in a new shell and it runs without errors.

**Comment by queen-king** [comment]
There was a dll path missing in the basic.py. After the path was changed,we got the output. Thank you

**Comment by natek512** [comment]
Hi! Can you tell me what your exact fix was? I am having the same issue and I am not really sure where you are setting this dll path. Thanks!

**Comment by felixdivo** [comment]
If the problem persists, please open a new issue where you for example state on what platform you are working.

**Comment by tarunkumar3096** [comment]
I'm getting same error "AttributeError: module 'can' has no attribute 'Bus'"
@queen97king2019 Can you tell exact fix to resolve this error

**Comment by felixdivo** [comment]
It's probably importing some other module that's also named can. Please inspect `can.__file__` or similar attributes to find out ehere it is imported from.
