### ISSUE TITLE
Incorrect pypi wheel which might destroy other packages

### ISSUE THREAD

**Issue by chrisoro** [hardbyte/python-can#738]
When installing your released pypi packaged it will install the following taken from RECORD:

> ../../Scripts/__pycache__/can_logger.cpython-37.pyc,,
> ../../Scripts/__pycache__/can_player.cpython-37.pyc,,
> ../../Scripts/__pycache__/can_viewer.cpython-37.pyc,,
> ../../Scripts/can_logger.py,sha256=mLcSR0czHD0kWfA-zRXy_VT64OsiJewRfvtcQB1lL38,166
> ../../Scripts/can_player.py,sha256=PW1zDei0tTGKpqRQLw1ZSyiMyuZM2R7p9Iwzks2EUYo,166
> ../../Scripts/can_viewer.py,sha256=2iiEVNNM6WBhiBOLwHWPU9qn4Sq0R38AJxTBtjjfZQA,166
> can/CAN.py,sha256=gm1FzhF3QVj_5W7HQkPrhIkZrqAb13vi9S6Rxicuuh8,941
> can/__init__.py,sha256=UaX_PSKHNZbHRg9visUW5k1wWj0CbjlC3CCgpqoBONo,1227
> can/__pycache__/CAN.cpython-37.pyc,,
> can/__pycache__/__init__.cpython-37.pyc,,
> can/__pycache__/broadcastmanager.cpython-37.pyc,,
> can/__pycache__/bus.cpython-37.pyc,,
> can/__pycache__/ctypesutil.cpython-37.pyc,,
> can/__pycache__/interface.cpython-37.pyc,,
> can/__pycache__/listener.cpython-37.pyc,,
> can/__pycache__/logger.cpython-37.pyc,,
> can/__pycache__/message.cpython-37.pyc,,
> can/__pycache__/notifier.cpython-37.pyc,,
> can/__pycache__/player.cpython-37.pyc,,
> can/__pycache__/thread_safe_bus.cpython-37.pyc,,
> can/__pycache__/util.cpython-37.pyc,,
> can/__pycache__/viewer.cpython-37.pyc,,
> can/broadcastmanager.py,sha256=aK7ACLJqXEijHfAp6HFZxhlQRQAe0V_y-lo6Sh2RAqk,5184
> can/bus.py,sha256=zRnIsqI8u42DoIN5Gk9KK3LN4O7tDrbwEvcnI8_P27w,13594
> can/ctypesutil.py,sha256=0gXuSRHeUvliDZpgRAY4HwR9b58ZFM4RORqpBN_C4to,2826
> can/interface.py,sha256=W7G9_HxF9iODgHHpF4yT5GEK1ZNBdtvdMac98HHBmuc,6049
> can/interfaces/__init__.py,sha256=v9jv3MnHx50bmDfYF_73RF3fBbhwVVzJqRCdUTirnwg,1863
> can/interfaces/__pycache__/__init__.cpython-37.pyc,,
> can/interfaces/__pycache__/canalystii.cpython-37.pyc,,
> can/interfaces/__pycache__/iscan.cpython-37.pyc,,
> can/interfaces/__pycache__/nican.cpython-37.pyc,,
> can/interfaces/__pycache__/slcan.cpython-37.pyc,,
> can/interfaces/__pycache__/virtual.cpython-37.pyc,,
> can/interfaces/canalystii.py,sha256=26sM44vjeqhvueo8-k7gTN3O_J0_F9LYEFwuIBzsb14,5292
> can/interfaces/ics_neovi/__init__.py,sha256=L9JPBhdEszuLZF1PX8DSWTUkwsUU3TP2WVsSi0zzWNo,82
> can/interfaces/ics_neovi/__pycache__/__init__.cpython-37.pyc,,
> can/interfaces/ics_neovi/__pycache__/neovi_bus.cpython-37.pyc,,
> can/interfaces/ics_neovi/neovi_bus.py,sha256=NpXt4IifSGLzWHx4HjpPFY9tJeXxQLhjkHeG0He1_Ow,12375
> can/interfaces/iscan.py,sha256=cBaDWCl8WwW6DfOCRFBFhHwX2wE7DklBOPd-W0KDp2Y,5740
> can/interfaces/ixxat/__init__.py,sha256=9mPf6xj7g2e3VHq7QAS1_Ni3bvbb57JyMYusw8YsP-4,222
> can/interfaces/ixxat/__pycache__/__init__.cpython-37.pyc,,
> can/interfaces/ixxat/__pycache__/canlib.cpython-37.pyc,,
> can/interfaces/ixxat/__pycache__/constants.cpython-37.pyc,,
> can/interfaces/ixxat/__pycache__/exceptions.cpython-37.pyc,,
> can/interfaces/ixxat/__pycache__/structures.cpython-37.pyc,,
> can/interfaces/ixxat/canlib.py,sha256=Gra7biamkXIEylOsvkRLCrFQPmFvd5zmz2hHPI0rDUk,28099
> can/interfaces/ixxat/constants.py,sha256=_lT2lN6z6H0Tt2WdlNj5oAbQE441CmOZFlIShjEfqG8,4537
> can/interfaces/ixxat/exceptions.py,sha256=2qqzBT0Usr7IGmQOFfkPg3erjSgKX4T0GjNTRxFXSaY,726
> can/interfaces/ixxat/structures.py,sha256=5qJeo0aHFnkEHidIn-lW86kLzjSZi8A_sLiX9Du1tIM,4573
> can/interfaces/kvaser/__init__.py,sha256=ri6sk6zxt74cpch8dnM3i-jFYSteG_blgVWUgBiboG0,69
> can/interfaces/kvaser/__pycache__/__init__.cpython-37.pyc,,
> can/interfaces/kvaser/__pycache__/canlib.cpython-37.pyc,,
> can/interfaces/kvaser/__pycache__/constants.cpython-37.pyc,,
> can/interfaces/kvaser/__pycache__/structures.cpython-37.pyc,,
> can/interfaces/kvaser/canlib.py,sha256=V-n8okDdYSQmJNDmSshqcxOx5XzHH2w49Sp6DGXan3Y,25968
> can/interfaces/kvaser/constants.py,sha256=BAhuf9BOlzidGgJBKzaJc02U5-Bo_Uy9aKtkjsst2GM,6918
> can/interfaces/kvaser/structures.py,sha256=FaMFbdFtZVTxopvh0IOgYSWO6sArJ_mlXfI4cahV2nE,2021
> can/interfaces/nican.py,sha256=y_RPLVSdYgpSIeGQNKrlF6qsntsPh5rDE4t5CDtmiU0,10909
> can/interfaces/pcan/__init__.py,sha256=Vg9ZLRxX6muTOCHqqAdsANC4Zexjg2PRBUs9dA3VgMo,71
> can/interfaces/pcan/__pycache__/__init__.cpython-37.pyc,,
> can/interfaces/pcan/__pycache__/basic.cpython-37.pyc,,
> can/interfaces/pcan/__pycache__/pcan.cpython-37.pyc,,
> can/interfaces/pcan/basic.py,sha256=Gy0wB5z6eRQeojBoj-UAU7QSYggkxADTyYjA2uTYfcU,35390
> can/interfaces/pcan/pcan.py,sha256=5SqkTWHW6WuvSzVqa54gjHAxpGGHTa5A5iPYmVgVXo4,15528
> can/interfaces/serial/__init__.py,sha256=Xje2qNOlrcpJOcLPz3UdU4x5Y7ygRW9Mj63bpmSGoHQ,88
> can/interfaces/serial/__pycache__/__init__.cpython-37.pyc,,
> can/interfaces/serial/__pycache__/serial_can.cpython-37.pyc,,
> can/interfaces/serial/serial_can.py,sha256=WKhAUl035QpQpKC-0R5SjGmj1sMknXxjKBrHJlqcnBk,4913
> can/interfaces/slcan.py,sha256=vw-BH_fH3dzwaaxxkV-58HvMMgdgIKRs2ceM_4egMaI,6215
> can/interfaces/socketcan/__init__.py,sha256=rzKAQK4sZQfREFEPXyGw-xDu55o_yMnN5j-oy229hnI,192
> can/interfaces/socketcan/__pycache__/__init__.cpython-37.pyc,,
> can/interfaces/socketcan/__pycache__/constants.cpython-37.pyc,,
> can/interfaces/socketcan/__pycache__/socketcan.cpython-37.pyc,,
> can/interfaces/socketcan/__pycache__/utils.cpython-37.pyc,,
> can/interfaces/socketcan/constants.py,sha256=ToxIlLITDueU_o7XwXig7E4mq642qrJ9gpBxXzx0a0A,1307
> can/interfaces/socketcan/socketcan.py,sha256=oavomN5ICY6zhNfXfkJ_r-gcnVltJv5AFYYIj92SKjo,25667
> can/interfaces/socketcan/utils.py,sha256=1jCyQ9TK9skPE03O_mJTENtncRM6H5eyKkq-i2FhYhc,2760
> can/interfaces/systec/__init__.py,sha256=2AsMFEEi5Mt0BNfVHqIX7e6boyYP_gu08YzQJmBrl54,76
> can/interfaces/systec/__pycache__/__init__.cpython-37.pyc,,
> can/interfaces/systec/__pycache__/constants.cpython-37.pyc,,
> can/interfaces/systec/__pycache__/exceptions.cpython-37.pyc,,
> can/interfaces/systec/__pycache__/structures.cpython-37.pyc,,
> can/interfaces/systec/__pycache__/ucan.cpython-37.pyc,,
> can/interfaces/systec/__pycache__/ucanbus.cpython-37.pyc,,
> can/interfaces/systec/constants.py,sha256=dgObXkNjrXIoT3ywbjuwj5QOjngtCPsq97_pHuba6L0,22744
> can/interfaces/systec/exceptions.py,sha256=dGRhM5Eish58frlbUNgg9oiG05M0yW0PCh9PPCrcXdE,5088
> can/interfaces/systec/structures.py,sha256=-g6e8wm95P31oIRiRRltkMbkk7PRmRGcJJ-9a7e-Sto,11753
> can/interfaces/systec/ucan.py,sha256=ZfIYCkf6ooHacU9n_GpXXql0N1oDlOhcyNrzO-FG89E,45620
> can/interfaces/systec/ucanbus.py,sha256=RQIvi34GJkUq9Xak24yL8-Cy6hwhPvCSlBqN-3FkuGY,9678
> can/interfaces/usb2can/__init__.py,sha256=v9r46sGvr9mlgQ4heCdSR2kjA7dASONGGoLO09NuMOM,168
> can/interfaces/usb2can/__pycache__/__init__.cpython-37.pyc,,
> can/interfaces/usb2can/__pycache__/serial_selector.cpython-37.pyc,,
> can/interfaces/usb2can/__pycache__/usb2canInterface.cpython-37.pyc,,
> can/interfaces/usb2can/__pycache__/usb2canabstractionlayer.cpython-37.pyc,,
> can/interfaces/usb2can/serial_selector.py,sha256=xUbNhgoHetFaUmcT-Tp6Ykk_4H5kqoqMgYMSt7hTT0Q,1414
> can/interfaces/usb2can/usb2canInterface.py,sha256=RXP9SwzQQ-qFzK91BLJOfR4uV49GlsTeh6uGWyetlzI,5380
> can/interfaces/usb2can/usb2canabstractionlayer.py,sha256=Luf_0w6E0PV4NwthCgD0irbTozJKcWpwS6LcCPaqsF8,5650
> can/interfaces/vector/__init__.py,sha256=Q5KI_BDFSU81LXVzT1x56nMjrdjxjMKds2ZkvbTF4zs,92
> can/interfaces/vector/__pycache__/__init__.cpython-37.pyc,,
> can/interfaces/vector/__pycache__/canlib.cpython-37.pyc,,
> can/interfaces/vector/__pycache__/exceptions.cpython-37.pyc,,
> can/interfaces/vector/__pycache__/vxlapi.cpython-37.pyc,,
> can/interfaces/vector/canlib.py,sha256=lj27bPvtgyPjonzCuq-27a8-ZvDprh4oZ6ijBm_9Kfw,17612
> can/interfaces/vector/exceptions.py,sha256=S3amitAXb1ePMLaqHdg1z8EqXCbBHc09RZTMHRVSi_s,287
> can/interfaces/vector/vxlapi.py,sha256=oZb3OH6SMqF5fPWDdqsxyPFOSiMSsIkP269Tfam0Xfg,12078
> can/interfaces/virtual.py,sha256=7-iYnJx16FERaapBQjYfUK2WSz1wvShDrxxWojcQLt4,4202
> can/io/__init__.py,sha256=qhta5wqqemmWF3jEBmGz4O4Ig2TPFI7ESfpYfnmr4B4,513
> can/io/__pycache__/__init__.cpython-37.pyc,,
> can/io/__pycache__/asc.cpython-37.pyc,,
> can/io/__pycache__/blf.cpython-37.pyc,,
> can/io/__pycache__/canutils.cpython-37.pyc,,
> can/io/__pycache__/csv.cpython-37.pyc,,
> can/io/__pycache__/generic.cpython-37.pyc,,
> can/io/__pycache__/logger.cpython-37.pyc,,
> can/io/__pycache__/player.cpython-37.pyc,,
> can/io/__pycache__/printer.cpython-37.pyc,,
> can/io/__pycache__/sqlite.cpython-37.pyc,,
> can/io/asc.py,sha256=KbxLTMtmYTqyii-SUZSSMA3zwdzRaYs1j1fKIMYTEPU,7872
> can/io/blf.py,sha256=1rkZ-SLqQUDZ0VMzkCW8iX7BgKXRtQMhwEIVS2ga1gg,18232
> can/io/canutils.py,sha256=-byxU2nuegItLtNtsQ5gzRI3hDSGm31GkwegkOrrPgo,4925
> can/io/csv.py,sha256=SnyIAgmOKoUT7_Ewp4FUTxI37z8nE5SBZXjVkz4L2fc,3905
> can/io/generic.py,sha256=EbiGN3TuPX7_VwpUEtLmQOgZjxEktHXDL5pX8FfBzko,1352
> can/io/logger.py,sha256=qoYzJAgEOLaOUUgS9FEGOqAKIdQ-SeWbfx9Kd0QN_iA,2097
> can/io/player.py,sha256=8tFoP6Yhu0BhDNs9m76dOjYCNpLyjWObWEq52I5fFvY,3477
> can/io/printer.py,sha256=GjXN77WJYWMJy5uKBFJ_G3VQtRPr5cKmB87-o2CoWj4,1269
> can/io/sqlite.py,sha256=YtY4sZE9I3US9v4C11QW4WQbs6lwHqQzlFQhQe6Fmr0,8738
> can/listener.py,sha256=N-Zz4Qls_WLwszZ_8oai5gB13H-68HgZs2V-G6M7Cjg,4789
> can/logger.py,sha256=Y52hR-5kcxpDhkZzjvHY6rFK2BllPAknXH329845AAs,4342
> can/message.py,sha256=rURWQhcWOSzyqU-hM7dWS4ChG9Sq4APFx_Iz7YZlyv0,13163
> can/notifier.py,sha256=03oT1BaOvYYqqt7eL85OVSapMLl942NZ1bgIA_83fcM,5007
> can/player.py,sha256=8YeosdTPPoA4ka6t8tpEuc2b6rtQdZNQT1_yLTgWOoU,3360
> can/thread_safe_bus.py,sha256=Xp7efg9o8P8MosfDpZwUhOrjtDzOPdtbzklhNAaKT74,3411
> can/util.py,sha256=PpBTlqaO4ywjdNzN1oW_3KZW3CBtT3_NKOl0CMLvx5E,7350
> can/viewer.py,sha256=LLuZq9wJXdecp5L7aM2bOSXr2P9jfG4n2rlGUUdxxZM,22590
> python_can-3.3.2.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
> python_can-3.3.2.dist-info/LICENSE.txt,sha256=2n6rt7r999OuXp8iOqW9we7ORaxWncIbOwN1ILRGR2g,7651
> python_can-3.3.2.dist-info/METADATA,sha256=nPcEBt8m0ujlcqP2ZlswjvY6R7kWshfOPSa5e7B6TBI,6523
> python_can-3.3.2.dist-info/RECORD,,
> python_can-3.3.2.dist-info/WHEEL,sha256=JZXtYepZFsf4IoivNpnSgKIc4qTHan08DRd56koo_DM,116
> python_can-3.3.2.dist-info/top_level.txt,sha256=tPwJHaIFJDNlJCfW47fReDKSCcRMBXS_rYcARliFueA,9
> test/data/__init__.py,sha256=KwGiZWhwug0K5ngnoP3y1Xx0RPSHLojsRIGCd5uMMB0,38
> test/data/__pycache__/__init__.cpython-37.pyc,,
> test/data/__pycache__/example_data.cpython-37.pyc,,
> test/data/example_data.py,sha256=kJCVCGUVm3ee2vcIe_4DxLI1MN2MSizrRWIHrQ7JZDQ,5472

As you can see it will create a "test" folder in site-packages with your tests.

This results in the following:

since some projects use the deprecated test_suite syntax they will overwrite each other in the site-packages\test
conflicts when having this installed in site-packages and running your own projects tests, which are very often in test folder. it will now run your tests instead of own projects tests
additional unneeded disk space usage and takes longer to install

All in all it's recommended to exclude tests when uploading to pypi.

**Comment by christiansandberg** [comment]
It would seem that the test package is correctly excluded but test.data is not. We should add test.* to the exclude list as well.

**Comment by chrisoro** [comment]
I already did that, will link PR

**Comment by karlding** [comment]
Closing since the PR associated with this is released as part of [v3.3.3](https://github.com/hardbyte/python-can/tree/3.3.3).
