### ISSUE TITLE
Discard error frames to be saved by SqliteWriter

### ISSUE THREAD

**Issue by khvalov** [hardbyte/python-can#742]
I would like to save into Sqlite (SqliteWriter process) only valid messages passed thru the filter. 
At this moment I have in DB mix of messages passed the filter and error messages. Is any way to discard error messages to be saved into the DB ?

**Comment by felixdivo** [comment]
You could create a writer, and manually call `on_message_received()` on it on each message, after you have filtered. If you have a suggestion on some missing documentation, please open anouther issue for that.
