### ISSUE TITLE
send_periodic for multiple messages

### ISSUE THREAD

**Issue by khvalov** [hardbyte/python-can#744]
Have to pull some ODB-II related data periodicaly, like Speed every 1 second, rpm every 2nd second, temp every X second. 
When I doing:
```
#Calculated engine load
    msg = can.Message(arbitration_id=0x7df,data=[0x2, 0x1, 0x4, 0x55, 0x55, 0x55, 0x55, 0x55],extended_id=False)
    bus.send_periodic(msg, 2)
    #Engine coolant temperature
    msg = can.Message(arbitration_id=0x7df,data=[0x2, 0x1, 0x5, 0x55, 0x55, 0x55, 0x55, 0x55],extended_id=False)
    bus.send_periodic(msg, 10)
    #Fuel pressure
    msg = can.Message(arbitration_id=0x7df,data=[0x2, 0x1, 0xa, 0x55, 0x55, 0x55, 0x55, 0x55],extended_id=False)
    bus.send_periodic(msg, 10)
```
looks like the periodic params overrided and run only the last one. 
So what is the best way to run multiple send_periodic messages ?

**Comment by hardbyte** [comment]
Closing as this issue is a duplicate. Please see #720 and #721 - we could do with documenting this better.
