### ISSUE TITLE
Tests fail on develop

### ISSUE THREAD

**Issue by marcel-kanter** [hardbyte/python-can#746]
Using commit dcd694efb56d503ed9387edc5cfba9c523d559bf the tests fail.
Windows 10 Pro Version 1909
Python 3.7.6, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
pytest plugins: timeout-1.3.3, cov-2.8.1, hypothesis-4.57.0

output of python setup.py test:

test/test_message_class.py::TestMessageClass::test_methods PASSED        [ 62%]
test/test_message_filtering.py::TestMessageFiltering::test_match_all PASSED [ 62%]
test/test_message_filtering.py::TestMessageFiltering::test_match_example_message PASSED [ 63%]
test/test_message_filtering.py::TestMessageFiltering::test_match_filters_is_empty PASSED [ 63%]
test/test_message_sync.py::TestMessageSync::test_general PASSED          [ 64%]
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++

After commenting out the pytest timeout detorator for the test, it results in:

test/simplecyclic_test.py::SimpleCyclicSendTaskTest::test_cycle_time FAILED [ 42%]
test/test_scripts.py::TestLoggerScript::test_do_commands_exist FAILED    [ 72%]
test/test_scripts.py::TestPlayerScript::test_do_commands_exist FAILED    [ 73%]
================= 3 failed, 194 passed, 29 skipped in 36.53s ==================
================================== FAILURES ===================================
__________________ SimpleCyclicSendTaskTest.test_cycle_time ___________________

self = <test.simplecyclic_test.SimpleCyclicSendTaskTest testMethod=test_cycle_time>

    @unittest.skipIf(
        IS_CI,
        "the timing sensitive behaviour cannot be reproduced reliably on a CI server",
    )
    def test_cycle_time(self):
        msg = can.Message(
            is_extended_id=False, arbitration_id=0x123, data=[0, 1, 2, 3, 4, 5, 6, 7]
        )
    
        with can.interface.Bus(bustype="virtual") as bus1:
            with can.interface.Bus(bustype="virtual") as bus2:
    
                # disabling the garbage collector makes the time readings more reliable
                gc.disable()
    
                task = bus1.send_periodic(msg, 0.01, 1)
                self.assertIsInstance(task, can.broadcastmanager.CyclicSendTaskABC)
    
                sleep(2)
                size = bus2.queue.qsize()
                # About 100 messages should have been transmitted
                self.assertTrue(
                    80 <= size <= 120,
                    "100 +/- 20 messages should have been transmitted. But queue contained {}".format(
>                       size
                    ),
                )
E               AssertionError: False is not true : 100 +/- 20 messages should have been transmitted. But queue contained 66

test\simplecyclic_test.py:49: AssertionError
___________________ TestLoggerScript.test_do_commands_exist ___________________

self = <test.test_scripts.TestLoggerScript testMethod=test_do_commands_exist>

    def test_do_commands_exist(self):
        """This test calls each scripts once and verifies that the help
        can be read without any other errors, like the script not being
        found.
        """
        for command in self._commands():
            try:
                subprocess.check_output(command.split(), stderr=subprocess.STDOUT)
            except subprocess.CalledProcessError as e:
                return_code = e.returncode
                output = e.output
            else:
                return_code = 0
                output = "-- NO OUTPUT --"
    
            allowed = [0, errno.EINVAL]
            self.assertIn(
                return_code,
                allowed,
                'Calling "{}" failed (exit code was {} and not SUCCESS/0 or EINVAL/22):\n{}'.format(
>                   command, return_code, output
                ),
            )
E           AssertionError: 1 not found in [0, 22] : Calling "python -m can.logger --help" failed (exit code was 1 and not SUCCESS/0 or EINVAL/22):
E           b'Traceback (most recent call last):\r\n  File "C:\\Program Files\\Python37\\lib\\runpy.py", line 183, in _run_module_as_main\r\n    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)\r\n  File "C:\\Program Files\\Python37\\lib\\runpy.py", line 109, in _get_module_details\r\n    __import__(pkg_name)\r\n  File "D:\\git\\python-can\\can\\__init__.py", line 7, in <module>\r\n    from typing import Dict, Any\r\n  File "c:\\program files\\python37\\lib\\site-packages\\typing.py", line 1357, in <module>\r\n    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\r\n  File "c:\\program files\\python37\\lib\\site-packages\\typing.py", line 1005, in __new__\r\n    self._abc_registry = extra._abc_registry\r\nAttributeError: type object \'Callable\' has no attribute \'_abc_registry\'\r\n'

test\test_scripts.py:44: AssertionError
___________________ TestPlayerScript.test_do_commands_exist ___________________

self = <test.test_scripts.TestPlayerScript testMethod=test_do_commands_exist>

    def test_do_commands_exist(self):
        """This test calls each scripts once and verifies that the help
        can be read without any other errors, like the script not being
        found.
        """
        for command in self._commands():
            try:
                subprocess.check_output(command.split(), stderr=subprocess.STDOUT)
            except subprocess.CalledProcessError as e:
                return_code = e.returncode
                output = e.output
            else:
                return_code = 0
                output = "-- NO OUTPUT --"
    
            allowed = [0, errno.EINVAL]
            self.assertIn(
                return_code,
                allowed,
                'Calling "{}" failed (exit code was {} and not SUCCESS/0 or EINVAL/22):\n{}'.format(
>                   command, return_code, output
                ),
            )
E           AssertionError: 1 not found in [0, 22] : Calling "python -m can.player --help" failed (exit code was 1 and not SUCCESS/0 or EINVAL/22):
E           b'Traceback (most recent call last):\r\n  File "C:\\Program Files\\Python37\\lib\\runpy.py", line 183, in _run_module_as_main\r\n    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)\r\n  File "C:\\Program Files\\Python37\\lib\\runpy.py", line 109, in _get_module_details\r\n    __import__(pkg_name)\r\n  File "D:\\git\\python-can\\can\\__init__.py", line 7, in <module>\r\n    from typing import Dict, Any\r\n  File "c:\\program files\\python37\\lib\\site-packages\\typing.py", line 1357, in <module>\r\n    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\r\n  File "c:\\program files\\python37\\lib\\site-packages\\typing.py", line 1005, in __new__\r\n    self._abc_registry = extra._abc_registry\r\nAttributeError: type object \'Callable\' has no attribute \'_abc_registry\'\r\n'

test\test_scripts.py:44: AssertionError

**Comment by marcel-kanter** [comment]
N.B. During writing some CANopen python code and switching between OSes I noticed that Windows 10 is a bit slower than Windows 7...

Regarding the timeout decorator:
The timeout for the test should NOT be used as test criterea. If there is a timing requirement for a test, then it should be tested within the test. So the timeout decoration should be removed, the time increased or the timing requirement (I don't see one here) be moved into the test code.

**Comment by marcel-kanter** [comment]
test/simplecyclic_test.py::SimpleCyclicSendTaskTest::test_cycle_time
fails because  there are not messages passing through. I got only 51, sometimes 66 of 100.
How much is this in non ci linux?

**Comment by christiansandberg** [comment]
Could be worth investigating if we can use [timeBeginPeriod](https://docs.microsoft.com/sv-se/windows/win32/api/timeapi/nf-timeapi-timebeginperiod) to increase timer resolution on Windows.

**Comment by marcel-kanter** [comment]
I think it's not the timer resolution, I'll try to investigate in what happens at every time step.
Because the thread switching time on my small Odroid C2 is below 1ms (more or less in 0.2ms range), but something makes the timing bad on the CI maschines.
Additionally i found that under Ubuntu 18.04 LTS the test fail too:
[odroidc2.txt](https://github.com/hardbyte/python-can/files/4023494/odroidc2.txt)

**Comment by christiansandberg** [comment]
The CI machines are heavily loaded by lots of tasks so it is useless running timing critical tests on those.

**Comment by marcel-kanter** [comment]
ok

**Comment by marcel-kanter** [comment]
Ok. Got it fixed. There is a problem with the Python 3.7.4.1 install on Windows which comes with a module typing.py and this is the source of the bug.
To fix this typing issue do:
python -m pip uninstall typing
