### ISSUE TITLE
UniqueHardwareId parameter for Ixxat is not working with Python27

### ISSUE THREAD

**Issue by josef-vachal** [hardbyte/python-can#756]
I got this error when using the UniqueHardwareId parameter:
`File "build\bdist.win32\egg\can\interfaces\ixxat\canlib.py", line 331, in __init__
    if (UniqueHardwareId is None) or (self._device_info.UniqueHardwareId.AsChar == bytes(UniqueHardwareId, 'ascii')):
TypeError: str() takes at most 1 argument (2 given)`

It might be wrong refactoring of code for Python27. In the code (File can\interfaces\ixxat\canlib.py), there is actually this:
`if (UniqueHardwareId is None) or (self._device_info.UniqueHardwareId.AsChar == bytes(UniqueHardwareId, 'ascii')):`

which, I think, is not correct for Python27. I replaced it with this:
`if (UniqueHardwareId is None) or (self._device_info.UniqueHardwareId.AsChar == bytes(UniqueHardwareId.encode('ascii'))):`

and it is working now.

**Comment by felixdivo** [comment]
If it is a Python 2.7 problem, I think there will be no effort for fixing this. I appreciate your effort here, but that Python version reached EOL some while ago and `python-can` already removed support for it from the develop branch.
