### ISSUE TITLE
Does the example receive_all.py actually receive all messages on a highly loaded bus?

### ISSUE THREAD

**Issue by AndySchroder** [hardbyte/python-can#768]
Does the example `receive_all.py` actually receive all on a highly loaded bus? It is unclear to me when I run `bus.recv()` if that will only catch the most recent message prior to when the function is run, or if there is some kind of buffer. It appears to me as if there is no buffer, so maybe `receive_all.py` actually just receives "all that it can"?

Even on a lightly loaded bus, if there are three messages that burst in a short time on the bus, could I miss one of the three, if the messages are sent faster than the python loop will run (say I've got a slow CPU and/or I need to put some other things in my loop besides `bus.recv()` )?

Or, on a medium loaded bus, where some messages are sent at a low frequency, is it possible I will miss a number of the low frequency messages, such that they appear to be transmitted at an even lower frequency?

If there is some kind of receive buffer, what keeps it from totally filling up the system's RAM if it is never read but there is still traffic on the bus?

**Comment by christiansandberg** [comment]
The buffering handled by the underlying driver, so yes you should be able to read all messages as long as the calls to recv are not too far apart. Usually there is some small buffer on the actual hardware, then a larger buffer in the driver that is sometimes configurable. If you never call recv or do blocking operations in between calls the buffer may become full.
