### ISSUE TITLE
Inconsistencies between interfaces

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#77]
Originally reported by: **Christian Sandberg (Bitbucket: [sandberg](https://bitbucket.org/sandberg), GitHub: [sandberg](https://github.com/sandberg))**

---

Found some inconsistencies between implementations.
1. `send()` should raise can.CanError on failed transmissions according to documentation.
- [x] a)  PCAN logs a warning and returns False
- [x] b) socketcan_native logs a warning
- [x] c)socketcan_ctypes ?
- [x] d) usb2can logs a warning
2. [x] serial does not implement `send()` and `recv()`
3. [x] socketcan_native does not implement `shutdown()`, implements `__del__` instead.
4. [x] usb2can uses argument `baud` specified in kbit/s while others use bitrate and bits/s.
5. [x] On Kvaser recv() when timeout is None, the call should block indefinitely until a message is received. Now it returns immediately.

---
- Bitbucket: https://bitbucket.org/hardbyte/python-can/issue/77

**Comment by christiansandberg** [comment]
Issues 1a and 5 have been fixed now.

**Comment by hardbyte** [comment]
Would you mind doing a quick sanity check Christian? If you're happy please close this issue.

**Comment by christiansandberg** [comment]
I'm happy! :thumbsup:
