### ISSUE TITLE
No way to log multiple channels to single BLF file.

### ISSUE THREAD

**Issue by mcdonl1** [hardbyte/python-can#770]
The BLF logging format allows for multiple channels to be logged to the same file. Currently the BLFWriter only allows writing to one channel - the channel that the logger is initialized for. There should be a way to pass in the channel of the corresponding message at write time.

**Comment by mcdonl1** [comment]
I'm going to work to see if I can make a fix.

**Comment by christiansandberg** [comment]
Individual messages can have a channel associated and in that case that information will be used instead.
