### ISSUE TITLE
BLF padding/alignment incorrect for CAN_FD_MESSAGE_64

### ISSUE THREAD

**Issue by MartinStellmacher** [hardbyte/python-can#786]
In blf.py all messages are padded by obj_size % 4. This assumption doesn't hold for all types of messages. I experienced a parsing error while reading a file which contained CAN_FD_MESSAGE_64 items. They are not padded at all, as you can see in Toby Lorenz C++ implementation.

Issue #459 is closed, but the problem still persists. Solution might be as simple as:

                    if header[4] == CAN_FD_MESSAGE_64 or header[4] == ETHERNET_FRAME_EX: 
                        next_pos = pos + obj_size #no padding
                    else:
                        next_pos = pos + obj_size + (obj_size % 4)  #weird padding

In Toby Lorenz implementation the padding is handled separately for each frame type...

**Comment by christiansandberg** [comment]
This fix (for FD frames only) is not released, you need to use develop.

**Comment by JuicyPussy** [comment]
faced the same problem, how could I contribute to fix it?

**Comment by christiansandberg** [comment]
A log file would be helpful. You can e-mail it to me if you don’t want to share it publicly: christiansandberg at me dot com.

**Comment by MartinStellmacher** [comment]
Hi Christian, thank you, but I think this fix isn't enough. In the BLF files I have at hand I found three different kinds of padding: 
1. none, like for the CAN_FD, 
2. crazy padding with `length%4` (mostly used) and 
3. correct padding with `(4-length%4)%4` (I think these were Ethernet-Frames). Even if you don't wan't to read them, your parser will fail, if they are contained within the file.

My final solution is to assume no padding and correct it by searching the LOBJ-mark with offsets from 0-3. Doing it this way I can separate the container format completely from the payload formats. I couldn't measure any increase in parsing times.

**Comment by christiansandberg** [comment]
Yeah that’s probably the best solution. Just need to make sure it handles padding spanning over two containers.

**Comment by MartinStellmacher** [comment]
Yes, I would do the check before reading the header, after fixing the start again for the header and than again to ensure that the payload is in the same container.

**Comment by christiansandberg** [comment]
If you could make a pull request with your solution that would be awesome.
