### ISSUE TITLE
default can message pass extended_id=None, will make message to be extended

### ISSUE THREAD

**Issue by zhupumpkin** [hardbyte/python-can#787]
in file can\message.py
line 83 function __init__ for Message 
pass is_extended_id=None also extended_id=None which are all defaul. 
And from meaning, it means no extended.
However line 113 in the same file 
            self.is_extended_id = True if extended_id is None else extended_id
this logic makes extended true as extended_id is None which is logical error.

expect should be 
self.is_extended_id = True if extended_id is not 
![logical_error](https://user-images.githubusercontent.com/9413303/76044210-9a7e7a00-5f94-11ea-8cd4-95962e672a5b.png)
None else extended_id

**Comment by christiansandberg** [comment]
Older versions had extended_id which was True default. Then it was renamed to is_extended_id but to keep backwards compatibility the old was kept and we allowed both during a transition period. That’s why it is a little complicated.

**Comment by felixdivo** [comment]
The current version on master already has this simplified and dropped backwards compatibility, see [here](https://github.com/hardbyte/python-can/blob/develop/can/message.py#L81). So I think there is no need for action here.
