### ISSUE TITLE
How to check the specific ID and data to react

### ISSUE THREAD

**Issue by CSG2019** [hardbyte/python-can#834]
Hello,
I want to get the specific ID and data then send a request.
For example, once i get the ID 0x2ED and this ID's data[1] is 0x26, i want to send a command on the vehicle bus.
When I try to run below code, it showed "Not receive", but in acutal vehicle CAN bus, i can find the ID 0x2ED and data[1]=0x26 was correct. and ID 0x2ED periodic cycle time is 10ms.
Could you please give me some suggestions or method which can fix it?
thank you.
```
import can

bus = can.interface.Bus(bustype='vector', app_name='CANalyzer', channel=[0])

rec_msg = bus.recv(1)
if rec_msg.arbitration_id == 0x2ED and rec_msg.data[0] == 0x26:
    print('Receive!')
else:
    print('Not receive!')
```

**Comment by christiansandberg** [comment]
When you need to do things repeatedly you should use a loop. Your code only receives a single message then exits.
