### ISSUE TITLE
How can record the TX(send) message in log.

### ISSUE THREAD

**Issue by hmq2018** [hardbyte/python-can#838]
Hi

Using PCAN-USB adaptor and the following code, the program can only log the received message to the log.
How to record the TX message into the log, thank you!

```
        self.bus = can.interface.Bus(bustype=self.interface, channel=self.channel, bitrate=self.bitrate, PCAN_BUSOFF_AUTORESET=True) 
        self.logger = can.Logger(test.asc)
        self.notifier = can.Notifier(self.bus, [self.logger, can.Printer()])
```

**Comment by tamenol** [comment]
`self.logger.info(msg)` in your send function? The thing is that you have control when sending a message, so appending that message to a log somewhere should be trivial.

**Comment by hmq2018** [comment]
Thanks.
But how can use can.Printer() to print RX and TX msg in same time?

**Comment by christiansandberg** [comment]
Some interfaces support the `receive_own_messages` argument but PCAN unfortunately does not seem to have a way to accomplish this.

It needs to be done by the driver so that order and timestamp is correct.

**Comment by hmq2018** [comment]
@christiansandberg 
Thanks for your explanation
