### ISSUE TITLE
Possible to Port Multiple Cyclic Messages in Task to 3.x Release

### ISSUE THREAD

**Issue by aquatsr** [hardbyte/python-can#842]
Regarding the features added in #610 will there be a 3.x release which includes these changes? If not, is there a timeline on when the 4.x release will be cut? Would like to use a pypi-provided release which includes these changes instead of building the `develop` branch for our projects.

Thanks

**Comment by hardbyte** [comment]
I've started a branch for a `3.3.4` release if you would like to open a backporting PR.

You're right that we should probably cut a pre-release of 4.0 soon too.

**Comment by felixdivo** [comment]
You can use the `4.0.0-dev.0` release for now if you want exactly that feature.
