### ISSUE TITLE
Socketcan update is broken

### ISSUE THREAD

**Issue by james-goin** [hardbyte/python-can#845]
Socketcan no longer works since this commit: https://github.com/hardbyte/python-can/commit/0e3812d218f03947d5fc7db59c61981b53e5b6e1

Throws [Errno 22] Invalid argument exception on line 365 of socketcan.py

**Comment by karlding** [comment]
Ugh, this only happens on Python 2, right? Do you see this on Python 3?

Looking at the source code for the `socket` module, I see that in 3.3 they changed the exception being thrown from `socket.error` to `OSError`. I suspect that's what's happening.

Here's the relevant [link in the docs](https://docs.python.org/3/library/socket.html#socket-families):

> All errors raise exceptions. The normal exceptions for invalid argument types and out-of-memory conditions can be raised; starting from Python 3.3, errors related to socket or address semantics raise OSError or one of its subclasses (they used to raise socket.error).

If this is the issue, then here's a patch that you can try applying on `3.3.3`.

```diff
diff --git i/can/interfaces/socketcan/socketcan.py w/can/interfaces/socketcan/socketcan.py
index b671f92..4bb989d 100644
--- i/can/interfaces/socketcan/socketcan.py
+++ w/can/interfaces/socketcan/socketcan.py
@@ -363,7 +363,7 @@ class CyclicSendTask(LimitedDurationCyclicSendTaskABC,
         )
         try:
             self.bcm_socket.send(check_header)
-        except OSError as e:
+        except (socket.error, OSError) as e:
             if e.errno != errno.EINVAL:
                 raise e
         else:
```
