### ISSUE TITLE
Add #621 to a 3.3.X release

### ISSUE THREAD

**Issue by pierreluctg** [hardbyte/python-can#846]
Can we have a new 3.3.x release that includes #621

This PR was closed long time ago but never made it to master.

Thank you

**Comment by hardbyte** [comment]
Does it need to be backported to support Python 2, or would a 4.x release be fine?

**Comment by pierreluctg** [comment]
@hardbyte Python 2.x is not required. However, if possible I would like to have it in release sooner than later. Not sure when 4.x will be ready for a release,

**Comment by hardbyte** [comment]
I've released a dev version of 4.0.0 - https://pypi.org/project/python-can/4.0.0.dev0/
