### ISSUE TITLE
BLFParseError

### ISSUE THREAD

**Issue by AllenGHL** [hardbyte/python-can#857]
hi,
    I need to read a canoe created blf file , but the feedback is :
  File "D:\MyTool\blf2asc\test\blf2asc.py", line 35, in <module>
    for msg in can_log:
  File "D:\ProgramFiles\anaconda3\lib\site-packages\can\io\blf.py", line 195, in __iter__
    raise BLFParseError()
can.io.blf.BLFParseError

the blf file could convert asc by canoe tool sucessfully.
I am blocked by this problem for a long time
thanks 
[attach file is the blf file]
[test.zip](https://github.com/hardbyte/python-can/files/4770104/test.zip)

**Comment by AllenGHL** [comment]
this is my first comment in the github, I'm new , I don't know how could I sent the error blf file to you? How could I upload the file ?  Could you give me a e-mail? 
Thanks

**Comment by AllenGHL** [comment]
I upload the zip file ,but I cannot see it

**Comment by AllenGHL** [comment]
[https://github.com/AllenGHL/blf-file
[test.zip](https://github.com/hardbyte/python-can/files/4770099/test.zip)
](url)

**Comment by AllenGHL** [comment]
if the attach file has problem , I also upload my repository 
https://github.com/AllenGHL/blf-file

**Comment by christiansandberg** [comment]
Have you tried with develop?

```sh
pip install https://github.com/hardbyte/python-can/archive/develop.zip
```

**Comment by AllenGHL** [comment]
> 

I tried the develop version ,  it worked. Thank you for your reply so quickly. Thank you , thank you.
