### ISSUE TITLE
can.interfaces.pcan.pcan.PcanError: A PCAN Channel has not been initialized yet or the initialization process has failed

### ISSUE THREAD

**Issue by catmemo** [hardbyte/python-can#868]
Hi, I tried to use python-can to wakeup a device by PCAN but failed.
But I found nothing wrong when I compared with the examples:

`self.bus = can.interface.Bus(bustype='pcan', channel = 'PCAN_USBBUS'+ str(int(self.channel)+1), bitrate = int(self.baudRate))`

self.channel == 0 and self.baudRate == 500000.

Could anyone help to check? Thanks in advance!

Traceback (most recent call last):
  File "D:\General\Learning\Ifan\Programme\python-can\CAN_Tool.py", line 251, in onStart
    self.bus = can.interface.Bus(bustype='pcan', channel = 'PCAN_USBBUS'+ str(int(self.channel)+1), bitrate = int(self.baudRate))
  File "D:\AIDA\Test_Tools\Python\lib\site-packages\can\interface.py", line 127, in __new__
    return cls(channel, *args, **kwargs)
  File "D:\AIDA\Test_Tools\Python\lib\site-packages\can\interfaces\pcan\pcan.py", line 198, in __init__
    raise PcanError(self._get_formatted_error(result))
can.interfaces.pcan.pcan.PcanError: A PCAN Channel has not been initialized yet or the initialization process has failed 

@christiansandberg

**Comment by bmeisels** [comment]
Hi @catmemo ,
have you installed the PCAN drivers and the PCANBasic API DLLs?

**Comment by catmemo** [comment]
> Hi @catmemo ,
> have you installed the PCAN drivers and the PCANBasic API DLLs?

Hi Bmeisels,

Thanks for your reply.
I have installed the PCAN drivers.
But I did not install the  PCANBasic API DLLs. 
I'll try and feedback to you, thks again!

**Comment by bmeisels** [comment]
Yes.
Have you opened the same PCAN channel with another tool?

**Comment by tamenol** [comment]
AFAIK this is no bug in python-pcan. I sometimes get this error too, and it's due to I have the channel open in PCAN-View or my PCAN object didn't get closed/deleted properly.

**Comment by catmemo** [comment]
> Yes.
> Have you opened the same PCAN channel with another tool?

Yes, this PCAN tool was used with PCAN-Exploer5 but not at the same time.

**Comment by catmemo** [comment]
> AFAIK this is no bug in python-pcan. I sometimes get this error too, and it's due to I have the channel open in PCAN-View or my PCAN object didn't get closed/deleted properly.

Thank you very much! I open the PCAN channel with PCAN-Exploer and closed it again, then it's normal with python-can.
Is that the root cause?
