### ISSUE TITLE
Facing an issue with "send_periodic" and "modify_data" for CAN messages

### ISSUE THREAD

**Issue by PrasannaByrappa** [hardbyte/python-can#876]
Hi,

   I'm facing an issue with api's "send_periodic" and "modify_data" in Python CAN, where the unintended CAN message (usually the next message ID) gets modified to the data (byte) for the targeted CAN message ID for which i intend to modify and transmit.

Basically i'm building a test framework, where i program functions / routine to
1) Initialize the system - send periodic CAN messages to initialize some default data ( ~60 CAN messages )
2) Inject Test data (Using test functions) - Pick **one** CAN message ID (lets say 0x454), modify the intended data byte and transmit (using either "Send_periodic" or "modify_data")
3) Observed using PCAN viewer that unintended CAN message (e.g 0x444 or 0x464) gets modified with data for the other intended CAN message.
4) tried to debug the code, my test functions are picking the correct message id instances to modify or send periodically and not interfering with any other CAN messages. The issue is only with APIs used, but not when i just use PCAN Viewer to TX / RX.

I'm currently using python-can 3.3.1, (python 3.7.4).

Any help would be appreciated. Thanks in advance

**Comment by hardbyte** [comment]
Thanks for posting that example. Please reopen if there is an issue.
