### ISSUE TITLE
Conversion to blf from pcan explorer query

### ISSUE THREAD

**Issue by mentaal** [hardbyte/python-can#891]
Hi All, 

I'm trying to convert a log file from the `.log` file format from PCAN-Explorer to a `.blf` file compatible with Vector CANAlyzer. 
(BTW I'm new to can and have been at this for a sum total of one day so forgive me if this is a stupid query)

I found your file conversion script and have been able to manually extract out the data from the `.log` file, create the appropriate `Message`s suitable for consumption via `can.Logger`. It works but the mapping I am using is lossy. 

For example, the file format provided by PCAN-Explorer is am using is of the form:

```
    ;Index
    ;|    Time Offset [ms]
    ;|    |             Bus
    ;|    |             |  CAN-ID (hex)
    ;|    |             |  |        Symbol                           Rx/Tx
    ;|    |             |  |        |                                |  Type       Length
    ;|    |             |  |        |                                |  |          |  Data
    ;+--- +------------ +- +------- +------------------------------- +- +--------- +- +----------------------
    1     37.935        2  702                                       Rx Data       3  8A 17 5F
```

I made a little function to create `Message`s using this function:

```python
def to_msg(log_line):
    """Convert a LogLine tuple into a python-can Message"""
    return Message(timestamp=log_line.time,
                   arbitration_id=log_line.can_id,
                   is_extended_id=False,
                   is_remote_frame=False,
                   dlc=log_line.length,
                   data=log_line.data,
                   channel=log_line.bus)
```

I don't see anywhere that I can inject the RX/TX type and the Symbol. I'm also assuming that the `channel` maps to the .log file's `Bus`. 

As a result, when the output .blf file is opened within the Vector tools, the `name` field in the GUI is absent, which I assume to be because I'm not injecting the symbol anywhere. 

Any suggestions would be greatly appreciated. 

Thanks!

**Comment by mentaal** [comment]
Ah right, so after having a look in the associated `.dbc` file, the file seems to contain a mapping between the symbol name and the `CAN-ID` so therefore it makes sense then that the blf file shouldn't need this symbol at all as, ostensibly, the same .dbc could be used with the associated `.blf` file in the same manner to get the extra contextual information. 

I wonder if the tx/rx field is also merely contextual based?

**Comment by christiansandberg** [comment]
In the develop branch (upcoming 4.0 release) there is a new `is_rx` argument:
https://github.com/hardbyte/python-can/blob/develop/can/message.py#L62

**Comment by mentaal** [comment]
Thanks @christiansandberg. I was inspecting the source code within the package I pip installed. 

Another question please if I may, I am struggling to understand the nomenclature between the different tools. Is the concept of a "channel" distinct from the bus number? 

In some of Vector's documentation such as this one: https://assets.vector.com/cms/content/products/VectorCAST/Events/TechNights/CANalyzer_QuickStart.pdf it says:

> In  total,  up  to  32  channels  may  be  measured  simultaneously
> in CANalyzer.  Any  combination  of  buses  can  beconfigured  as  well.  A
> unique  identifier  is  needed  to  addressor  read-out  (measure)  specific
> channels  withinCANalyzer

So I guess they are different and perhaps a channel is just a logical mapping in that application. 
In the context of the blf file format how do these relate?

Thanks for your time

**Comment by christiansandberg** [comment]
A "channel" may have slightly different meaning depending on the context, but in your case converting from one log format to another it is basically the same thing.

**Comment by mentaal** [comment]
Thanks for taking the time @christiansandberg. Much appreciated.
