### ISSUE TITLE
detect_available_configs for pcan

### ISSUE THREAD

**Issue by martsalz** [hardbyte/python-can#894]
Hi,

does the pcan support the `detect_available_configs` function?
It returns an empty array.

https://github.com/hardbyte/python-can/blob/develop/test/test_detect_available_configs.py

Thanks

**Comment by bmeisels** [comment]
This was implemented in https://github.com/hardbyte/python-can/blob/ac6e3ef8c6722fa19b48fc35b6ba0cca8c8b5303/can/interfaces/pcan/pcan.py#L485
and seems to have been merged around 3.3.2 to develop but never released in an actual release.
Currently it is included in the 4.0.0-dev.0  tag so i guess it will be included in the 4.0.0 release.
