### ISSUE TITLE
CANoe channels are not working (xlGetApplConfig failed, xlOpenPort failed)

### ISSUE THREAD

**Issue by stefanuca** [hardbyte/python-can#898]
Hello,

I am trying to send a can message from python.
this is the code
![image](https://user-images.githubusercontent.com/56625345/90871682-21d57380-e3a4-11ea-8803-e44f34f36fe5.png)

this is vector hardware configuration
![image](https://user-images.githubusercontent.com/56625345/90871770-416c9c00-e3a4-11ea-9e33-b5e4367a98a4.png)
![image](https://user-images.githubusercontent.com/56625345/90871819-58ab8980-e3a4-11ea-8fd2-3fb17a923c79.png)

what might cause the issue?
when i use a virtual bus it works

**Comment by stefanuca** [comment]
this is the error

![image](https://user-images.githubusercontent.com/56625345/90871959-91e3f980-e3a4-11ea-9c8c-a9130420e717.png)

**Comment by stefanuca** [comment]
@zariiii9003 it is possible to have something about the order of the applications in vector hardware configuration?

**Comment by zariiii9003** [comment]
@stefanuca Were you able to resolve your problem?

Can you please install this version `pip install https://github.com/zariiii9003/python-can/archive/vector_channel_config.zip` and send me the output from the following code?

```python
import can

[print(cfg) for cfg in can.detect_available_configs(interfaces=['vector'])]
```

**Comment by felixdivo** [comment]
@zariiii9003 Can this be closed or do you suspect an error in python-can to be lurking here that needs further digging?

**Comment by zariiii9003** [comment]
@felixdivo There might be some bug. #971 also has problems connecting to a piggy interface. I will close this and leave the other one open.
