### ISSUE TITLE
Raise BLFParseError when iterate BLF file with TriggerEvent included

### ISSUE THREAD

**Issue by cucdat** [hardbyte/python-can#910]
Hi,

I get the BLFParseError when trying to iterate the blf file with TriggerEvent included.
If I exclude this event by CANalyzer, I can iterate the file perfectly.
I do not need to read this event but is there any method that we can ignore it automatically and move to the CANbus data.

Below is the TriggerEvent that included in my blf.

![image](https://user-images.githubusercontent.com/60722722/94242048-72666080-ff50-11ea-9256-408c07b2523e.png)

**Comment by christiansandberg** [comment]
Which version of python-can are you using? Have you tried with develop?

**Comment by cucdat** [comment]
I used the 3.3.3 version and it didn't work.
However, I tried with the develop branch and this issue does not show up anymore.

Thank you so much for your kind support.
I close this open issue.
