### ISSUE TITLE
Showing ImportError: cannot import name 'Message' from 'can'

### ISSUE THREAD

**Issue by rkabirx** [hardbyte/python-can#915]
I am importing CAN messages in `Python` and I am using the `python-can` library. So the line in my python code here is: 

    from can import Message

It was working fine but after I changed the folders, I am getting the below error:

    Traceback (most recent call last):
      File "/home/rafi/PycharmProjects/Right Turn/CAN_simulator_Recv.py", line 12, in <module>
        from can import Message
    ImportError: cannot import name 'Message' from 'can' (/home/rafi/.local/lib/python3.8/site-packages/can/__init__.py)

Can anyone help me with this error? Maybe it has something to do with directory or packages? The same `can` library is working fine in other Linux machines. I tried uninstalling `python-can` but it doesn't work. 
Please help.

**Comment by felixdivo** [comment]
Sorry, I cannot reproduce this. Please check if there are files called `can.py` or `can.pyc` lying around. Please comment with more information if the problem persists.
