### ISSUE TITLE
How to Log CAN FD traffic?

### ISSUE THREAD

**Issue by chuchienshu** [hardbyte/python-can#922]
I'm now wanna Log all traffic on the CAN bus, which including CAN and CAN FD message. However, it seems that [can.logger](https://python-can.readthedocs.io/en/master/scripts.html#can-logger) just record the standard CAN traffic. Is it possible to log CAN FD traffic simultaneously? Any hint will be appraciate. thx~

**Comment by christiansandberg** [comment]
You should be able to with develop:

https://python-can.readthedocs.io/en/develop/scripts.html

**Comment by felixdivo** [comment]
Also make sure to collect CAN FD messages in the first place. E.g. pass `fd=True` to the Bus constructor.

**Comment by felixdivo** [comment]
If you still have problems, feel free to create an issue with the steps you tried and what dd not work as expected.
