### ISSUE TITLE
No matching distribution found for windows-curses; platform_system == "Windows" (from python-can)

### ISSUE THREAD

**Issue by yuqizhi** [hardbyte/python-can#932]
![图片](https://user-images.githubusercontent.com/53638072/99039958-4451e400-25c3-11eb-91ff-28f80cc49f63.png)

**Comment by felixdivo** [comment]
Can you also reproduce this error on the develop branch? You should be able to install it with `pip install -e git+git://github.com/hardbyte/python-can.git@develop#egg=python-can[serial]`.

**Comment by felixdivo** [comment]
On Linux, `windows-curses` is not required since the `curses` module is present on Linux systems anyway.

**Comment by felixdivo** [comment]
If the problem persists, please comment again.
