### ISSUE TITLE
PCAN breaking change on develop

### ISSUE THREAD

**Issue by kail** [hardbyte/python-can#948]
It looks like https://github.com/hardbyte/python-can/pull/711 introduced a breaking change for OSX + latest libPCUSB driver.

The call to SetValue always returns an error code: https://github.com/hardbyte/python-can/pull/711/files#diff-83cad9b8cc7cd5a75c4020bb5a9b2403d1a960e217e5e2d14c79929224f537f9R215

Happy to make a change to make this call optional, unless there's a cleaner solution.

**Comment by felixdivo** [comment]
I assume this is fixed by #976.
