### ISSUE TITLE
initializing can.interface.Bus() with "fd" parameter as type bool always resolves to fd-enabled configuration

### ISSUE THREAD

**Issue by s0kr4t3s** [hardbyte/python-can#954]
when initializing Bus with fd as a bool parameter `can.interface.Bus(fd=False, ...)`, function `load_file_config` mistakenly creates fd=True configuraton

[File: can/util.py](https://github.com/hardbyte/python-can/blob/develop/can/util.py)
[go to `load_file_config` Line 198](https://github.com/hardbyte/python-can/blob/974d8a8bd97e75cf6656e6396373edc2b4d1a914/can/util.py#L198) 

```python
if "fd" in config:
    config["fd"] = config["fd"] not in ("0", "False", "false")
```
resolution:
```python
if "fd" in config:
    config["fd"] = config["fd"] not in ("0", "False", "false", False)
```
@christiansandberg

**Comment by christiansandberg** [comment]
Thanks for finding that bug. Are you able to make a pull request with that fix?
