### ISSUE TITLE
How to use the set_filter to get the data

### ISSUE THREAD

**Issue by CSG2019** [hardbyte/python-can#962]
Hi,

I want to send a command to the BUS, then get the response of the special ID and data then do something.
please help to have a look for below code:

``` 
import can


def main():
    bus = can.interface.Bus(bustype='vector', app_name='CANoe', channel=[0])
    test_msg = can.Message(arbitration_id=0x18DA10F1, dlc=8,
                               data=[0x04, 0x18, 0x00, 0xFF, 0x00, 0x00, 0x00, 0x00])
    bus.send(test_msg)

    can_filters = [{"can_id": 0x18DAF110, "can_mask": 0x1FFFFFFF, "extended": False}]
    bus = can.Bus(bustype='vector', app_name='CANoe', channel=[0], can_filters=can_filters)

    try:
        while True:
            message = bus.recv(timeout=2)
            if message is None:
                print('no response')
                break
            elif message.arbitration_id == 0x18DAF110:
                print(hex(message.arbitration_id), hex(message.data[0]), hex(message.data[1]), hex(message.data[2]),
                      hex(message.data[3]), hex(message.data[4]))
                break
            else:
                pass
    finally:
        bus.shutdown()


if __name__ == "__main__":
    main()
```

this is from CAN BUS screenshot :
![image](https://user-images.githubusercontent.com/53852255/103201392-c192a780-492a-11eb-9b52-a87973a6466d.png)

my question is:
1,I can find the response on CAN, but I can't print the id&data I want to get. could you please help to guide me?
2, I set the timeout=2, after the bus.recv(timeout=2), why didn't the While loop exit.

thank you in advance.

**Comment by christiansandberg** [comment]
You create the second bus after you sent the message, so it will not be able to see the message. You have also specified extended to False in your filter but the ID is clearly 29-bit.

**Comment by CSG2019** [comment]
Hi christiansandberg,

Thank for the help.
yes, as you said, I created the 2 buses, so it caused I can't get the data I want. After deleted one, it seems to be working well.

about the extended question, yes, my ID should be 29-bit, but when I run below code, I can't print the filter message ,and If I set the extended to False, it can print the filter message. so I don't understand. If you can help to find the reason, please let me know. thank you.
```
def main():
    can_filters = [{"can_id": 0x18DAF110, "can_mask": 0x1FFFFFFF, "extended": True}]
    bus = can.Bus(bustype='vector', app_name='CANoe', channel=[0], can_filters=can_filters)

    for msg in bus:
        print(msg)


if __name__ == "__main__":
    main()
```
the result:

![image](https://user-images.githubusercontent.com/53852255/103267150-1e09cb80-49ec-11eb-8316-1cb1ea97f17b.png)

---------------------------------------------------------------
```
def main():
    can_filters = [{"can_id": 0x18DAF110, "can_mask": 0x1FFFFFFF, "extended": False}]
    bus = can.Bus(bustype='vector', app_name='CANoe', channel=[0], can_filters=can_filters)

    for msg in bus:
        print(msg)


if __name__ == "__main__":
    main()
```
the result:
![image](https://user-images.githubusercontent.com/53852255/103267437-79d45480-49ec-11eb-9a5c-484cb878397b.png)

**Comment by felixdivo** [comment]
Please comment if this is still relevant (as the question is several months old).
