### ISSUE TITLE
What are the limitations of CAN FD support?

### ISSUE THREAD

**Issue by MaratSabitov** [hardbyte/python-can#963]
I have a question regarding CAN FD support.

"Limited CAN FD support" declared.
What does it mean,
what are the limitations?

**Comment by felixdivo** [comment]
I think this refers to the README (right?). AFAIK, the support for CAN FD is rather complete. Some drivers may not fully support it, but in the general scheme of things this, they should work just fine. Also with the included scripts and file format IO capabilities.

@hardbyte @christiansandberg  Would you approve to removing the "limited" from the README?

**Comment by hardbyte** [comment]
@christiansandberg you're the expert so happy to defer to you. I'm inclined to agree with @felixdivo

**Comment by christiansandberg** [comment]
I'm definitely no expert but I would say that CAN FD support is about the same status as a lot of other things in python-can. Some implementations are more complete than others and there are certainly aspects of FD that could be implemented if desired. So yes you can remove that disclaimer.
