### ISSUE TITLE
viewer.py with options to publish scaled & labeled CAN signals to MQTT

### ISSUE THREAD

**Issue by dalklein** [hardbyte/python-can#967]
Hello,   thanks for this nice working python CAN code!
     I modified the  python-can/can/viewer.py  (renamed to viewmqtt.py),  to listen on CAN and publish signals out to MQTT.
Any interest to include it?    I'm not sure my changes are up to any standard, may be a little hacky, but it works as before unless the different command line option is given and labels are added to the signal decode parameter file.

If there's any interest, please let me know and I'll do a pr after any further improvements needed.  Or say if there's anything recommended to update or change to make it acceptable.  Or if there's some existing tool for the purpose, that I didn't see.

high level changes / notes
imports paho-mqtt,  and publishes to mqtt on localhost:1883    (needs mosquitto or broker running locally if -q is used)
added arg parsing to label signals (assuming they have been filtered & scaled, then see if labels are there for them
-q  option for 'quiet',  enables publishing to mqtt, and stops use of stdscr, so it can be run in the background.
I did not do anything yet to downsample potentially high rate CAN signals appropriately for MQTT.  This could be needed for signals at higher rate than .5 or .1 sec, to avoid too many MQTT messages.

Changes are here, based on last release I think, on branch can2mqtt:     https://github.com/dalklein/python-can/tree/can2mqtt                 new file  can/viewmqtt.py,   and new example decode file si-decode_label.txt

Thanks,   Dale

![Screenshot_20210112_014047](https://user-images.githubusercontent.com/49771139/104278871-4cb98480-5477-11eb-87ec-63b0320d4aba.png)

![Screenshot_20210112_014542](https://user-images.githubusercontent.com/49771139/104279228-f1d45d00-5477-11eb-9775-cd8047103d1c.png)

**Comment by felixdivo** [comment]
This looks like a neat tool. However IMHO, this does not quite fit into the scope of this library.

I think it would be useful to have a "other nice CAN-related (Python) tools". Your script would fit there.

**Comment by felixdivo** [comment]
I added this idea to #1041. It will be tracked there.
