### ISSUE TITLE
Installation Error with SEEED Package

### ISSUE THREAD

**Issue by gatordevin** [hardbyte/python-can#969]
I can't install the extra seeed-studio package for some reason. I am on windows.

python3.7 -m pip install python-can[seeed-studio]

Collecting python-can[seeed-studio]
  python-can 3.3.4 does not provide the extra 'seeed-studio'

**Comment by zariiii9003** [comment]
It is available in the develop branch and in version 4.0.0.dev0 on PyPI

**Comment by felixdivo** [comment]
Closing this for now. Please comment if the solution by @zariiii9003  did not solve the problem. If works locally on my machine too, **but** with a typo fixed: `python3.8 -m pip install "python-can[seeedstudio]==4.0.0.dev0"`.
