### ISSUE TITLE
blf read header information to get start date of measurement

### ISSUE THREAD

**Issue by nexulm** [hardbyte/python-can#973]
Did I miss something? 
How can I extract the header lines from a .blf files to get the date of measurement start?
.asc starts always with this first line, i.e:
date Fre Jan 22 13:20:12.005 2021

I need the information of date and time for measurement start.
start_timestamp returns only "13:20:12.005" and not the date (here: 2021/01/22)

**Comment by christiansandberg** [comment]
The start_timestamp is in seconds since the Epoch (Unix timestamp). What is the raw float value?

**Comment by nexulm** [comment]
Good hint, didn't realize this. :-(

Code is up and running now. ;-)
!!!
    fCANin      = can.io.BLFReader(infile)
    # read measurement start_timestamp from .blf file
    dt_mtstart  = format(datetime.fromtimestamp(fCANin.start_timestamp), '%Y-%m-%dT%H:%M:%S.%f')
!!!
