### ISSUE TITLE
How to parse can frameID from the msg = bus.recv(1)

### ISSUE THREAD

**Issue by itsanjan** [hardbyte/python-can#988]
I am using the following sample code to read CAN data from an ixxat device. 

`
def receive_all():

    bus = can.interface.Bus(bustype='ixxat', channel=0, bitrate=125000)

    # bus.state = BusState.ACTIVE  # or BusState.PASSIVE
    BusState.PASSIVE
    try:
        while True:
            msg = bus.recv(1)
            if msg is not None:
                print(msg)
                print(msg.data)
    except KeyboardInterrupt:
        pass
`

I am able to obtain the CAN data using msg.data however the documentation does not offer anything for the frameID's.
I am sure there is a native way, would be good if anyone can point me to the correct documentation. 👍 
Image for reference, i wish to extract the ID information.
![image](https://user-images.githubusercontent.com/6011627/110915894-3aa47700-833e-11eb-8ee6-e6cb6141e44b.png)

**Comment by KloolK** [comment]
That's the arbitration ID: https://python-can.readthedocs.io/en/master/message.html#can.Message.arbitration_id

**Comment by itsanjan** [comment]
Thank you so much for the quick revert @KloolK . Cheers for the days !!
