### ISSUE TITLE
Refactor CAN.py

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#99]
- [ ] move the listeners into own file
- [ ] move logging function into `util.py`

**Comment by christiansandberg** [comment]
My idea is to move the log readers and writers to their own modules. Suggestion:

can.log.sqlite
can.log.asc
can.log.csv
etc

**Comment by hardbyte** [comment]
Agree, this sounds sensible. Perhaps `can.io` instead of `can.log` though.
