### ISSUE TITLE
pcan: neutral/german error messages cause logger exceptions

### ISSUE THREAD

**Issue by XelaRellum** [hardbyte/python-can#993]
Any return value other than `PCAN_ERROR_OK` for _PCAN_ SDK functions will be translated to the corresponding error text.

The parameter to the SDK function `GetErrorText` specifiying the language is `0` (neutral language). This seems to mean the language of the system, because on my German Windows 10 system this results in a Germany message.

There seems to be a bug in the decoding of the error message to UTF-8.

It seems to be easier for me to use language code `0x9` (English) instead of fixing the decoding bug since the exceptions use English texts as well without using to localize them.

**Comment by felixdivo** [comment]
Fixed by #994.
