### ISSUE TITLE
Virtual Bus documentation example

### ISSUE THREAD

**Issue by polfeliu** [hardbyte/python-can#998]
Hello, I'm using the virtual bus to test an application.

I learnt to use it with this example: https://github.com/hardbyte/python-can/blob/2.1.0/doc/interfaces/virtual.rst
I thought I had something wrong since the example raises an assertion error. Taking a closer look the messages "are not equal" because the timestamp and channels are different. The other data is identical and thus it works :). I would suggest to change the assertion of the example to comparison of data and dlc, or removing the assertion entirely as it may produce confusion.

**Comment by polfeliu** [comment]
Oh! I didn't see that. Thank you! 
Readthedocs has the old example for some reason. https://python-can.readthedocs.io/en/master/interfaces/virtual.html
And the link to github points to the same example.

**Comment by hardbyte** [comment]
Probably means we need a new release!
