### ISSUE TITLE
Checking if Tx has was ever ACKed

### ISSUE THREAD

**Issue by ValaJeyhani** [hardbyte/python-can#999]
My system uses SocketCAN CAN adaptor. I am wondering if there is any way to check whether a previously sent message was ever ACKed by a receiver. I know I can get different types errors from the driver. But that doesn't seem sufficient to determine if a transmitted message was eventually received and ACKed.

Alternatively, is there any way to determine if a transmission is in progress? That can be helpful in figuring out if a message is still being retransmitted or was ACKed at some point.

Thanks in advance!

**Comment by felixdivo** [comment]
First of all, ACKing and receiving should be equivalent in CAN.

have a look at [`BusABC.send`](https://python-can.readthedocs.io/en/develop/bus.html#can.BusABC.send):

> timeout (Optional[float]) – If > 0, wait up to this many seconds for message to be ACK’ed or for transmit queue to be ready depending on driver implementation. If timeout is exceeded, an exception will be raised. Might not be supported by all interfaces. None blocks indefinitely.

And, socketcan should support this kind of checking. The transmission is in progress as long as the `bus.send()` has not yet returned.

If you find out that this does not work as indented, feel free to file bug report.
